#!/bin/sh
# 

SCRIPT="load-tnet-org-N"   

./load-org-extra.pl 1301 
./load-org-extra.pl 1302 
./load-org-extra.pl 1303 
./load-org-extra.pl 1304 
./load-org-extra.pl 1305 
./load-org-extra.pl 1306 
./load-org-extra.pl 1307 
./load-org-extra.pl 1308 
./load-org-extra.pl 1309 
./load-org-extra.pl 1310
./load-org-extra.pl 1311 
./load-org-extra.pl 1312  

./load-org-extra.pl 1401 
./load-org-extra.pl 1402 
./load-org-extra.pl 1403 
./load-org-extra.pl 1404 
./load-org-extra.pl 1405 
./load-org-extra.pl 1406 
./load-org-extra.pl 1407 
./load-org-extra.pl 1408 
./load-org-extra.pl 1409 
./load-org-extra.pl 1410 
./load-org-extra.pl 1411
./load-org-extra.pl 1412 
 
 
echo ${SCRIPT} | mail -s "Script ${SCRIPT} finished  " robertf@c.net

echo "Done..."
echo ""




