#!/bin/sh
# 
# runs all org scripts
# this will take a while and need to check all imports as they go
# run as  ./load-tnet-org YYMM 
  
if [ -z $1 ]
 then
 echo ""
 echo "Missing date: YYMM"
 echo ""
 exit;
fi

source /usr/wt/reload.sh
 
FDATE=$1

echo ""
echo "Date: ${FDATE}"
echo ""
  
echo "Site + Site with Cov" 
./load-org-drill-tnet-site-new.pl ${FDATE}
echo "------------------------------------" # 

echo "Adv" 
./load-org-drill-tnet-adv.pl ${FDATE} 
echo ""
echo "------------------------------------" #

echo "Cat" 
./load-org-drill-tnet-cat.pl ${FDATE} 
echo ""
echo "------------------------------------" #

echo "Cat Wiz" 
./load-org-drill-tnet-cat-wiz.pl ${FDATE} 
echo ""
echo "------------------------------------" #
 
echo "News" 
./load-org-drill-news.pl ${FDATE} 
echo ""
echo "------------------------------------"

#echo "Product Search" 
#./load-org-drill-PS-adv.pl ${FDATE} 
#echo ""
#echo "------------------------------------"

echo "Flat Catnav" 
./load-org-drill-tnet-flatcatnav.pl ${FDATE} 
./catnav-visitor-combo-extra  ${FDATE}    # delete is already in script
echo "" 
echo "------------------------------------"
 
echo "Extra" 
./load-org-extra.pl ${FDATE} 
echo ""
echo "------------------------------------"

 
echo "Check Tables Script. Look for missing data.";
./checktables.pl ${FDATE}
echo "------------------------------------"


echo ${FDATE} | mail -s "Script load-tnet-org finished for ${FDATE}   " robertf@c.net

echo "Done..."


 
