#!/bin/sh
#
# cat reg Registration History


if [ -z $1 ]
 then
 echo ""
 echo "Missing date: yymm"
 echo ""
 exit;
fi

 


# Load new tnet reg data
LOGFILE="catreglog.txt" 
rm -f ${LOGFILE}
echo "Loading ${LOGFILE}" 
echo "  SELECT date, heading, tinid, 'TNET'  from tnetlogREGCAT where date='$1'  "  | mysql -A tgrams > ${LOGFILE}
mysqlimport tgrams ${LOGFILE}
 
 
./mk-catreg-history.pl 


./mk-catreg-loadco.pl

 

