#!/usr/bin/perl
#
# update orgs that have been not flaged as isps

$year     = $ARGV[0];
if($year eq "") {print "\n\nForgot to add isp and or Year YY\n\n"; exit;}
$outfile="orgs-flag.log";
  
$ADDDATE="  date>''  "; 
 
# Connect to mysql database
use DBI;
$dbh      = DBI->connect("", "", "");

$unixtime    = time();
$z           = 1;  
$i           = 0;  
 
$ORGLIST="
'2k transportation llc',
'3plus logistics company',
'a cooper logistics inc',
'abc logistics corporation',
'able transportation',
'able transportation inc',
'abs freight transportation',
'abx logistics ltd',
'accurate logistics llc',
'accurate logistics ltd',
'ace logistics inc',
'ace transportation company inc',
'action logistics inc',
'ads logistics company llc',
'advanced logistics group sa',
'advanced transportation',
'advantage ground transportation corporation',
'aero transportation products inc',
'aerostar global logistics inc',
'afc logistics inc',
'afs logistics llc',
'agility project logistics pte ltd',
'agunsa logistics & distribution inc',
'aim logistics inc',
'air ground transportation',
'air logistics inc',
'ait worldwide logistics inc',
'alco transportation inc',
'all girls tranportation & logistics inc',
'all logistics cargo inc',
'all points logistics inc',
'all points logistics llc',
'allure transportation',
'alpinos logistics and distribution inc',
'alte transportation sl',
'alternative logistics inc',
'american logistics company llc',
'american logistics group inc',
'american logistics international llc',
'american shipping & logistics group inc',
'american transportation inc',
'american transportation technology distribution corporation',
'amerifleet transportation inc',
'ams logistics inc',
'amware logistics',
'amware logistics services inc',
'anaheim transportation network',
'andrews logistics inc',
'apc postal logistics llc',
'apex global logistics inc',
'apl logistics inc',
'apple transportation inc',
'archilla transportation',
'ard logistics llc',
'ardmore power logistics llc',
'aries global logistics',
'armada logistics inc',
'armstrong transportation inc',
'ars transportation company',
'art logistics inc',
'asbury transportation company',
'asf logistics llc',
'atco structures & logistics inc',
'atlantic transportation services inc',
'atlantis logistics inc',
'atlas sn logistics inc',
'ats logistics inc',
'atthowe transportation company inc',
'b & b transportation inc',
'b & c transportation inc',
'b & g transportation inc',
'b2b transportation services inc',
'bandstra transportation systems ltd',
'barnhart transportation llc',
'bb logistics inc',
'bear transportation services lp',
'becker logistics',
'best transportation llc',
'best transportation services inc',
'bestocean worldwide logistics inc',
'better environmentally sound transportation',
'bgi worldwide logistics inc',
'billet transportation inc',
'bison global logistics',
'blackhawk logistics llc',
'blakeman transportation inc',
'bonded transportation solutions inc',
'border pro logistics llc',
'bouchard transportation company inc',
'bounce logistics inc',
'bowen logistics inc',
'boyd brothers transportation inc',
'bradco transportation inc',
'brenny transportation inc',
'bridge logistics llc',
'bridgeport transportation & warehousing inc',
'broadrange logistics llc',
'brokerage and logistics solutions inc',
'brokerage transportation',
'broussard logistics llc',
'builders transportation company llc',
'bulk transportation',
'bullocks express transportation inc',
'burris logistics',
'busy bee transportation services inc',
'c mac transportation llc',
'cabrera logistics inc',
'calyx transportation group inc',
'campbell transportation company inc',
'capital transportation inc',
'capital transportation logistics inc',
'capital transportation logistics inc',
'capital transportation logistics llc',
'capital transportation logistics llc',
'capital transportation sols',
'capricorn logistics inc',
'caravan logistics inc',
'cardinal logistics',
'cardinal logistics management corporation',
'cardinal logistics management inc',
'cargo cargo logistics inc',
'cargo logistics inc',
'cargo logistics network company',
'cargo one logistics llc',
'carlile transportation systems inc',
'carroll fulmer logistics corporation',
'carter logistics llc',
'cas transportation inc',
'cavalier transportation services inc',
'cavalry logistics llc',
'cbsltransportation services inc',
'cds logistics management inc',
'central jersey transportation inc',
'central states logistics inc',
'century transportation inc',
'certified freight logistics inc',
'ceva logistics',
'ceva logistics netherlands bv',
'ceva logistics us inc',
'champagne logistics lp',
'champion logistics group inc',
'champion transportation service',
'chela logistics inc',
'chemical logistics inc',
'chenega logistics llc',
'choice logistics inc',
'chtl logistics llc',
'chung lung freight transportation co ltd',
'churchill transportation inc',
'circle 8 logistics inc',
'circle city logistics ltd inc',
'cita logistics llc',
'city logistics & transport inc',
'classic transportation',
'coastal international logistics llc',
'coastal logistics',
'coastal logistics inc',
'command transportation llc',
'commodity logistics',
'community transportation association of america',
'complete transportation',
'complete transportation llc',
'computer transportation services ltd',
'continental logistics',
'convoy logistics providers ltd',
'corporate transportation group ltd',
'corsair logistics inc',
'cortrans logistics llc',
'coyote logistics llc',
'creative logistics',
'creative transportation',
'crestline transportation inc',
'crh transportation inc',
'crossroads usa logistics inc',
'crowley logistics inc',
'crystal creek logistics llc',
'ctc logistics inc',
'cts global logistics inc',
'cubic transportation systems ltd',
'cw logistics llc',
'data2logistics europe bv',
'data2logistics llc',
'dawson logistics inc',
'dean transportation inc',
'dedicated logistics inc',
'denbeste transportation inc',
'design transportation',
'detroit transportation corporation',
'development logistics group',
'diversified logistics inc',
'diversified transportation services inc',
'dot-line transportation inc',
'double d transportation company',
'douglas transportation inc',
'drive logistics ltd',
'driveforce transportation of tulsa',
'driveforce transportation services llc',
'drt transportation llc',
'dsc logistics inc',
'dws logistics inc',
'dynamic transportation llc',
'dynamic worldwide logistics',
'e & b transportation',
'eagle transportation services inc',
'earl paddock transportation inc',
'eastern logistics inc',
'ec transportation corporation',
'echo global logistics inc',
'ecu-logistics nv',
'ej logistics',
'elite logistics inc',
'encompass global logistics llc',
'england logistics',
'england logistics inc',
'eno transportation foundation inc',
'ep logistics llc',
'equs logistics llc',
'evans transportation service',
'evergreen systems logistics inc',
'evergreen transportation llc',
'excel transportation inc',
'executive transportation service inc',
'expedited logistics and freight services ltd',
'express logistics llc',
'express transportation services',
'extra mile transportation llc',
'extron logistics llc',
'facilities logistics inc',
'fairway logistics inc',
'falls transportation service',
'fashion logistics inc',
'fast lane transportation inc',
'fastrans logistics inc',
'fcc logistics inc',
'federated logistics inc',
'fetch logistics inc',
'first class logistics',
'five star global logistics ll',
'florida marine transportation',
'focus logistics inc',
'fontana logistics',
'forrest transportation service inc',
'fort transportation & service company',
'four star transportation company',
'fourstar transportation',
'fowler transportation ltd',
'freedom logistics inc',
'freight management logistics llc',
'frontline logistics inc',
'fst logistics inc',
'g & d transportation inc',
'gb logistics inc',
'gencom transportation inc',
'general logistics systems netherlands bv',
'genesis transportation inc',
'getgo transportation company llc',
'gilgen logistics ag',
'global alliance logistics inc',
'global expo logistics',
'global group logistics llc',
'global link logistics inc',
'global logistics & distributor',
'global logistics inc',
'global logistics solutions inc',
'global marine logistics pte ltd',
'global shipping & logistics',
'globe logistics inc',
'gmg transportation corporation',
'gps logistics llc',
'grace blue logistics',
'grane transportation lines ltd',
'gray transportation inc',
'greystone logistics inc',
'griffin & company logistics',
'grimes logistics services inc',
'groome transportation inc',
'gsl logistics corporation',
'gt logistics llc',
'gulick freight service logistics inc',
'h & m international transportation inc',
'ha logistics inc',
'hampton roads transportation inc',
'hanzo logistics inc',
'hartley transportation llc',
'hartt transportation systems',
'havi logistics is gmbh',
'haymarket transportation inc',
'haynes transportation company',
'hecny transportation inc',
'helix logistics llc',
'hellmann worldwide logistics gmbh',
'hellmann worldwide logistics inc',
'hellmann worldwide logistics ltd',
'hellmann worldwide logistics sa',
'heniff transportation systems llc',
'henry county transportation',
'highland transportation inc',
'hill brothers intermodal logistics inc',
'hill brothers transportation inc',
'hodges transportation inc',
'hoekstra transportation inc',
'hoffman transportation',
'hollingsworth logistics management llc',
'holt logistics corporation',
'home delivery logistics inc',
'horizon north logistics inc',
'hotfoot logistics llc',
'hybrid building logistics inc',
'hyder transportation llc',
'hydra transportation of louisville inc',
'hyperlogistics group inc',
'icat logistics inc',
'illini logistics',
'industrial transportation inc',
'infinity logistics inc',
'in-line transportation inc',
'inline transportation llc',
'innovative logistics inc',
'integra logistics',
'integrated logistics solu',
'integrated transportation solution',
'integration logistics llc',
'integrity logistics inc',
'interchez logistics systems inc',
'inter-logistics llc',
'international logistics management inc',
'international marine transportation ltd',
'international procurement and logistics ltd',
'international transportation service inc',
'interport logistics llc',
'interstar transportation services inc',
'interstate logistics inc',
'interturbine logistics solutions gmbh',
'ioplus logistics llc',
'isg transportation inc',
'island transportation corporation',
'ital logistics ltd',
'itochu logistics corporation',
'iwd transportation llc',
'j & l transportation inc',
'j.v. transportation consultants inc',
'jd logistics inc',
'jimmy cowart transportation services llc',
'jj son & logistics inc',
'jka logistics llc',
'jrc transportation inc',
'js logistics corporation',
'justina dunn transportation services',
'jw logistics llc',
'k & k transportation inc',
'k line logistics inc',
'k line logistics ltd',
'kace logistics llc',
'kayla logistics corporation',
'kc transportation inc',
'kce logistics inc',
'kenco logistics',
'keppel logistics pte ltd',
'keystone dedicated logistics company llc',
'kk integrated logistics inc',
'kl harring transportation llc',
'knapp logistics automation inc',
'knichel logistics',
'krystal logistics usa inc',
'ktl transportation corporation',
'kuecker logistics group inc',
'kuehne nagel logistics bv',
'l.w. miller transportation inc',
'lacny logistics inc',
'lady logistics corporation',
'lakeside logistics inc',
'lakeside transportation company',
'langham logistics inc',
'lantrax logistics ltd',
'latek logistics usa inc',
'lawrence transportation',
'leading edge logistics llc',
'legacy transportation services inc',
'lemmen transportation company',
'lesaint logistics llc',
'lewis transportation group llc',
'lexington logistics llc',
'liberty transportation inc',
'lien transportation company',
'life science logistics llc',
'lightning logistics llc',
'linc logistics company',
'linehaul logistics inc',
'lionheart project logistics inc',
'lmd integrated logistics services inc',
'load delivered logistics llc',
'lodestar logistics corporation',
'logistics insight corporation',
'logistics international inc',
'logistics international llc',
'logistics management',
'logistics management information',
'logistics management institute',
'logistics management resources inc',
'logistics management solutions inc',
'logistics plus inc',
'logistics worldwide usa inc',
'lone star transportation llc',
'longistics transportation inc',
'lp transportation inc',
'lta logistics inc',
'lth logistics',
'lth logistics pte ltd',
'luckey logistics llc',
'lynden international logistics company',
'm & w transportation company inc',
'maersk logistics usa inc',
'malark logistics inc',
'mallory alexander international logistics llc',
'mamo transportation inc',
'marine transport logistics',
'marino transportation services',
'marquette transportation company llc',
'marquis transportation llc',
'material technology & logistics inc',
'materials transportation company',
'maxim transportation services inc',
'mbm logistics inc',
'mcallister towing & transportation company inc',
'mch logistics llc',
'md logistics inc',
'medical transportation management inc',
'menlo logistics inc',
'mercury transportation inc',
'metro transportation inc',
'metropolitan transportation authority',
'metropolitan transportation inc',
'mexpress transportation inc',
'mgn logistics inc',
'miami warehouse logistics inc',
'mid america freight logistics llc',
'mid-arctic transportation company ltd',
'midwest specialized transportation inc',
'milogistics llc',
'miq logistics llc',
'mitsubishi logistics corporation',
'moe-mentum transportation inc',
'mohawk global logistics',
'monroe transportation ltd',
'montgomery transportation brokers inc',
'moose logistics inc',
'moran transportation company',
'moran transportation corporation',
'moulton logistics management',
'mtc logistics inc',
'multi group logistics inc',
'multi-mode logistics llc',
'mv transportation',
'mvp logistics llc',
'mw logistics llc',
'mystic logistics inc',
'n and d transportation company inc',
'n.c. logistics inc',
'naca logistics inc',
'naegeli transportation inc',
'napa transportation inc',
'national transportation safety board',
'nats north america&#39;s transportation service inc',
'nec logistics america inc',
'neighborhood logistics company inc',
'network global logistics llc',
'new age transportation distribution and warehousing inc',
'new age transportation inc',
'new century transportation inc',
'nin logistics llc',
'noble supply & logistics',
'norbert dentressangle logistics ltd',
'nordic logistics and warehousing llc',
'north arm transportation ltd',
'north park transportation company inc',
'northern logistics inc',
'northern transportation company ltd',
'nova natie logistics nv',
'nrs logistics',
'nuclear logistics inc',
'nuna logistics ltd',
'nyborg integrated logistics inc',
'odw logistics inc',
'omg logistics llc',
'omni logistics inc',
'orthman logistics company',
'overdrive logistics inc',
'ozburn-hessey logistics llc',
'p & s transportation inc',
'p.a.m. transportation services inc',
'pacific air logistics inc',
'pacific logistics corporation',
'pacific rim transportation ltd',
'pacific transportation services inc',
'pallet logistics inc',
'palmetto state transportation company inc',
'paramount transportation systems inc',
'park city transportation servi',
'park transportation inc',
'pathfinder logistics inc',
'payment logistics llc',
'pds transportation',
'pegasus transportation inc',
'penn transportation services inc',
'penske transportation holdings corporation',
'performance logistics llc',
'perkins specialized transportation inc',
'petrologistics lp',
'pfs transportation inc',
'phoenix logistics inc',
'phoenix transportation services llc',
'pm logistics & systems inc',
'pme logistics inc',
'polymer logistics inc',
'polymer logistics nv',
'power one logistics',
'premier logistics inc',
'price busters transportation',
'price transportation inc',
'priority logistics inc',
'priority transportation group inc',
'pro ag logistics llc',
'progressive transportation services inc',
'prominent logistics inc',
'propak logistics inc',
'prospect transportation inc',
'public logistics inc',
'pyramid logistics services inc',
'pyramid transportation systems inc',
'qhub logistics corporation',
'quality logistics inc',
'queensland health server purchasing and logistics',
'quik x transportation inc',
'r & k logistics inc',
'r & m logistics corporation',
'r & m logistics inc',
'r & r transportation inc',
'r.j.s. logistics inc',
'r2 logistics inc',
'radiant logistics inc',
'ramp logistics',
'rcs logistics inc',
're transportation inc',
'reckart logistics inc',
'redhawk transportation inc',
'redline logistics inc',
'regency transportation inc',
'regional integrated logistics inc',
'regional transportation district',
'reinauer transportation companies llc',
'reliable transportation solutions llc',
'reliable transportation specialists inc',
'remote logistics inc',
'renaissance global logistics llc',
'resource logistics inc',
'retail logistics llc',
'riegel transportation inc',
'riley transportation inc',
'rld transportation inc',
'rle logistics llc',
'rm logistics',
'roadco transportation services inc',
'roadtex transportation corporation',
'roane transportation services llc',
'roar logistics inc',
'robart transportation inc',
'ro-mar transportation systems inc',
'romark logistics of texas inc',
'rome transportation inc',
'rose chauffeured transportation ltd',
'royal cargo combined logistics inc',
'rr donnelley logistics services worldwide inc',
'rsc transportation',
'ruan transportation management systems inc',
'rush transportation inc',
'ryan transportation service inc',
'ryder crsa logistics',
'sales transportation inc',
'salson logistics inc',
'sammons transportation inc',
'samples transportation service',
'sanyo logistics corporation',
'sav logistics inc',
'scanwell logistics inc',
'scanwell logistics pvt ltd',
'schilli transportation services inc',
'schmidt transportation inc',
'schumacher cargo logistics inc',
'scott logistics corporation',
'scr medical transportation inc',
'sdv logistics inc',
'seal transportation inc',
'sealaska global logistics llc',
'secure transportation and relocation international inc',
'secure transportation company inc',
'select transportation inc',
'sentinel transportation llc',
'service first logistics corporation',
'sh cogent logistics pte ltd',
'shanahan transportation systems inc',
'shoreline transportation inc',
'silverline transportation ltd',
'simplified logistics llc',
'skye logistics llc',
'skyline transportation inc',
'sl source logistics laredo llc',
'sloan transportation products inc',
'south coast logistics',
'south coast transportation & distribution inc',
'southland logistics company inc',
'specialized transportation for outpatient services inc',
'spectrum transportation services llc',
'speedmark air transportation pte ltd',
'spirit logistics llc',
'standard transportation services inc',
'states logistics services inc',
'steelman transportation inc',
'sterling transportation service',
'stevens global logistics inc',
'stonearch logistics llc',
'stoneland global logistics inc',
'strategic logistics solutions inc',
'styer transportation company',
'styles logistics inc',
'suffolk transportation service',
'summit logistics inc',
'sunset pacific transportation inc',
'sunset transportation inc',
'sunshine logistics inc',
'superior logistics services inc',
'superior nationwide logistics ltd',
'swift transportation',
'swift transportation company',
'syfan logistics inc',
'system logistics corporation',
't.a.g. logistics llc',
't.g.r. logistics inc',
'talon logistics inc',
'tandem logistics inc',
'tbb global logistics inc',
'tcl logistics',
'tds logistics inc',
'tek transportation inc',
'the complete logistics company',
'the gateway logistics group inc',
'the rk logistics group inc',
'the walsh transportation group inc',
'thurman transportation inc',
'tiffany transportation company inc',
'tigers logistics group ltd',
'timberland transportation inc',
'timco logistics systems inc',
'time logistics inc',
'titanium logistics inc',
'tmsi logistics',
'tonami transportation co ltd',
'top logistics llc',
'top shelf logistics llc',
'total logistics',
'total logistics group inc',
'total transportation & distribution inc',
'total transportation concept',
'total transportation corporation',
'total transportation services inc',
'total transportation services llc',
'total transportation solutions inc',
'toyo logistics co ltd',
'toyo logistics pte ltd',
'tradewinds transportation llc',
'trancy logistics america corporation',
'trans global logistics llc',
'trans global logistics ltd',
'trans gulf transportation inc',
'trans logistics international inc',
'trans pacific logistics llc',
'translink transportation inc',
'trans-national transportation service inc',
'transolutions & logistics llc',
'transportation & industrial services inc',
'transportation & insurance consultants inc',
'transportation & warehouse services inc',
'transportation bureau city of nagoya',
'transportation collaborative inc',
'transportation consultants inc',
'transportation corridor agencies',
'transportation demand management inc',
'transportation department public',
'transportation equipment inc',
'transportation management dynamics inc',
'transportation marketing services',
'transportation parts unlimited',
'transportation research corporation',
'transportation security administration',
'transportation services inc',
'transportation solutions group llc',
'transportation specialists inc',
'transportation structures inc',
'transportation supply depot inc',
'transportation technology center inc',
'transtar executive transportation service inc',
'transtar transportation inc',
'treasure transportation inc',
'trinity transportation inc',
'triple r transportation inc',
'triumph logistics inc',
'turner logistics corporation',
'ultimate logistics',
'ultimate na transportation equiptment llc',
'ultra logistics inc',
'unico logistics usa inc',
'unimasters logistics scs eood',
'united global logistics inc',
'united logistics solutions',
'united transportation group inc',
'universal logistics group inc',
'urban logistics kk',
'us logistics inc',
'us messenger & logistics inc',
'us transportation llc',
'uscom logistics inc',
'uti canada contract logistics inc',
'uti integrated logistics inc',
'uti integrated logistics llc',
'uti logistics ag',
'venture logistics inc',
'venture transport logistics llc',
'veolia transportation',
'veterans transportation llc',
'victory worldwide transportation',
'victory worldwide transportation inc',
'vitran logistics ltd',
'vizion logistics llc',
'vocar transportation services llc',
'vouk transportation inc',
'vsf transportation inc',
'w logistics inc',
'wallenius wilhelmsen logistics',
'wallenius wilhelmsen logistics ab',
'wallenius wilhelmsen logistics americas llc',
'wallenius wilhelmsen logistics as',
'ward transport & logistics corporation',
'wasatch transportation inc',
'wca logistics llc',
'well worldwide energy logistics inc',
'western installation and logistics inc',
'whatcom transportation authority',
'white eagle transportation inc',
'wide range transportation services inc',
'wildernest logistics solutions inc',
'wilson transportation inc',
'wisconsin international services logistics inc',
'world logistics inc',
'worldwide logistics inc',
'wright transportation inc',
'xcelerated transportation group llc',
'xpo logistics canada inc',
'yellow transportation inc',
'yhl logistics inc',
'yusen logistics inc',
'yusen logistics ltd',
'yusen logistics pty ltd',
'zip logistics llc',
'zipline logistics llc',
'zuniga logistics ltd'
";

                
$ORGS ="  org in  ( $ORGLIST )   ";
$ORGS2 ="  co in (   $ORGLIST   )   ";
   
  

sub updateTable
{  
  $q = $_[0];
  print "$q\n"; 
  my $sth = $dbh->prepare($q);
  if (!$sth->execute) { print "Error" . $dbh->errstr . "\n"; exit(0); }
  $sth->finish;
  sleep(1);
}   

            
$i=0;
open(wf, ">>$outfile")  || die (print "Could not open $outfile\n");

  $isp =~ s/^\s+//;
  $isp =~ s/\s+$//;
  $isp =~ tr/[A-Z]/[a-z]/; 
  print "\n\n$isp\n\n";
 
 #VTOOL

 updateTable("delete from  vtool13_01   where  $ORGS   "); 
 updateTable("delete from  vtool13_02   where  $ORGS   "); 
 updateTable("delete from  vtool13_03   where  $ORGS   "); 
 updateTable("delete from  vtool13_04   where  $ORGS   "); 
 updateTable("delete from  vtool13_05   where  $ORGS   "); 
 updateTable("delete from  vtool13_06   where  $ORGS   "); 
 updateTable("delete from  vtool13_07   where  $ORGS   "); 
 updateTable("delete from  vtool13_08   where  $ORGS   "); 
 updateTable("delete from  vtool13_09   where  $ORGS   "); 
 updateTable("delete from  vtool13_10   where  $ORGS   "); 

  
  
  updateTable("update tnetlogORGPS".$year."_01   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_02   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_03   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_04   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_05   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_06   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_07   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_08   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_09   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_10   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_11   set block='Y' where  $ORGS   ");   
 updateTable("update tnetlogORGPS".$year."_12   set block='Y' where  $ORGS   ");   


   
  # CATNAV 
  updateTable("update catnav_ipn".$year."_01  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_02  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_03  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_04  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_05  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_06  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_07  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_08  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_09  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_10  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_11  set block='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_12  set block='Y' where  $ORGS2   ");
 
 
  # NEWS 
  updateTable("update newsORGSITED$year    set block='Y' where  $ORGS   and  $ADDDATE and oid>''");
  updateTable("update newsORGD$year        set block='Y' where  $ORGS    and  $ADDDATE and acct>0    and oid>''");
  
  # TNET  
  updateTable("update  tnetlogORGSITED".$year."_01   set block='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_02   set block='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_03   set block='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_04   set block='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_05   set block='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_06   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_07   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_08   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_09   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_10   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_11   set block='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_12   set block='Y' where  $ORGS    and  oid>''"); 
   
                                               
  updateTable("update  tnetlogORGD".$year."_01  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_02  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_03  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_04  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_05  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_06  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");  
  updateTable("update  tnetlogORGD".$year."_07  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_08  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_09  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_10  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_11  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_12  set block='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");    
 

  updateTable("update tnetlogORGCATD".$year."_01    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_02    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_03    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_04    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_05    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_06    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_07    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_08    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_09    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_10    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_11    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_12    set block='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  
  updateTable("update tnetlogORGN$year  set block='Y' where  $ORGS    and   $ADDDATE ");
  updateTable("update tnetlogORGCATN$year  set block='Y' where  $ORGS    and   $ADDDATE ");
  updateTable("delete from tnetlogADviewsServerOrg$year  where  $ORGS   ");
  
  # Reach local
   updateTable("delete from Campaign_IP  where  $ORGS2   and universal_id >''");

 # news image
  updateTable("delete from adcvmaster where  $ORGS   ");
 
 
 # Visitor Tool
  updateTable("update visitor_tool     set block='Y' where  $ORGS     and oid>''");
  updateTable("update visitor_cat_tool set block='Y' where  $ORGS     and oid>''");

 updateTable("delete from tnetlogADviewsServerOrg$year  where  $ORGS  ");
    
close(wf);
  

print "\nDone...\n";

 



