#!/usr/bin/perl
#
# update orgs that have been not flaged as isps

$year     = $ARGV[0];
if($year eq "") {print "\n\nForgot to add isp and or Year YY\n\n"; exit;}
$outfile="orgs-flag.log";
  
$ADDDATE="  date>''  "; 
 
# Connect to mysql database
use DBI;
$dbh      = DBI->connect("", "", "");

$unixtime    = time();
$z           = 1;  
$i           = 0;  
 
$ORGS =" org in  (
'(previously known as CyberWay Pte Ltd)',
'013 Netvision Ltd',
'1001943 Ontario Ltd',
'123.Net',
'15b 53 55 corporate drive bridgewater nj 08807 usa',
'24Online Broadband Server',
'3BB Broadband',
'Aamra Networks Limited',
'Abissnet sh.a.',
'Abovenet Communications Inc',
'Acantho S.p.a',
'Access Broadband',
'Access Kenya Group Ltd',
'ACD.net',
'Ace',
'Adams CATV',
'Adept Internet (Pty) Ltd CT',
'Administracion Nacional de Telecomunicaciones',
'Advanced Colocation',
'Advanced Tel Inc',
'Aero Group Inc',
'af net',
'AF NET Internet Services',
'Aflac',
'Aftab IT Limited',
'Agence Tunisienne Internet - ATI',
'AGT',
'Air Advantage LLC',
'Airband Communications Inc',
'Airespring',
'Airtel',
'Airtel Broadband',
'Airwave Networks Incorporated',
'AJAY Syscon PVT Ltd',
'Alands Datakommunikation Ab',
'Alaska Communications Systems Group',
'Albtelecom Sh.a.',
'Alenco Communications',
'Alestra S. De RL De CV',
'Algerie Telecom - FAWRI',
'Alice DSL',
'Allendale Telephone Company',
'Allhostshop.com',
'Allied Stone',
'ALLTEL Corporation',
'Alpheus Data Services, L.L.C.',
'Alternate Access Inc',
'Amazon.com',
'American Internet Services, LLC.',
'American Packaging Corporation',
'American Red Cross',
'Amerisuites',
'Amnet Broadband Pty Ltd',
'Amnet Cable San Pedro Sula',
'AMNET TEL y cia S en C de C.V.',
'AMP Corporate Telecommunications',
'Anchorage Redback DSL Dynamic Pool',
'Anchorage Redback DSL Pool',
'ANEKS d.o.o.',
'Antietam Cable Television Inc',
'Apollo Telecom (Pvt.) Ltd.',
'Arab Company For Internet & Communications Service',
'Arcor AG',
'Areti Internet LLC',
'Armstrong Utilities Inc',
'Arqiva Communications Ltd',
'Art Matrix - Lightlink',
'ARtelecom',
'Ascus Telecom GmbH',
'Asianet is a cable ISP providing',
'ASK4 Ltd',
'Aston University',
'AT&T',
'AT&T AMS GIDC External Range',
'AT&T Enhanced Network Services',
'AT&T Global Network Services',
'AT&T Global Network Services Asia Pacific',
'AT&T IDC Redditch',
'AT&T Internet Services',
'AT&T Managed Firewall Network Based - Sydney',
'AT&T Managed Firewall Services NB2',
'AT&T MFS-NB 2.0-- Mesa, AZ - Trial',
'AT&T Mobility LLC',
'AT&T Services',
'AT&T U-verse',
'AT&T Worldnet IP Services',
'AT&T Worldnet Services',
'Athens',
'Atlanta Customer Market Allocation',
'Atlantic Broadband',
'Atlantic Telephone Membership Corp.',
'Atos IT Solutions and Services GmbH',
'Atria Convergence Technologies Pvt. Ltd.',
'Att Bco Mcrc',
'Att Corp-intra-legacy T Legal',
'ATX Telecommunications Services',
'Augere Wireless Broadband Bangladesh Limited',
'Axis Telekom Indonesia Pt',
'AXTEL',
'Axtel, S.A.B. de C. V.',
'Axtel, S.A.B. de C.V.',
'B2X Online',
'Bahnhof Internet AB',
'Bahrain Telecommunication Company',
'Baja Broadband',
'Baldwin County Internet',
'baldwin telecom inc',
'bandwidth communications ltd',
'Bandwidth.com',
'Banglalion WiMAX',
'Barracuda Networks Inc',
'Batelco ADSL service',
'Batelco Jordan',
'Bayan Telecommunications Incorporated',
'Bayanat Al-Oula For Network Services',
'BB BROADBAND CO., LTD.',
'Bce',
'BCL EAST,Infinity Building, Tower One, 1st Floor',
'BDCOM Online Limited',
'Be Un Limited',
'Beam Telecom Pvt Ltd',
'Beam Telecom Pvt Ltd, Hyderabad',
'Beehive Telephone Company',
'Beeline',
'Beijing Teletron Telecom Engineering Co., Ltd.',
'Belgacom Skynet',
'Belize Telemedia Ltd',
'Bell Aliant Inc',
'Bell Aliant Regional Communications Inc',
'Bell Canada',
'BellSouth.net',
'Ben Lomand Rural Telephone Coop Inc',
'Bend Cable Communications Inc',
'Bend Cable Communications, LLC',
'Bezeq',
'Bezeq International',
'BH Telecom d.d. Sarajevo',
'Bharat Sanchar Nigam Ltd',
'Bharti Airtel Limited',
'Bharti Airtel Ltd.',
'Bharti Broadband',
'Bharti Infotel Ltd',
'Bharti Telenet Ltd. Tamilnadu',
'Birch Telecom Inc',
'BitWise Systems',
'BKK Fiber AS',
'Bkk Marked AS',
'Black Oak Computers',
'Blackfoot Telephone Coop Inc',
'Blackney Hayes Architects',
'Blink Communications',
'Blue Coat Systems Inc',
'BluesMedia InfoTech',
'Botswana Telecommunications Corporation',
'Bouygues Telecom',
'Brainstorm Internet',
'Brandenburg_Telephone_Company',
'BRAS Pools - Charminar',
'Bredbandsbolaget AB',
'Bresnan Communications LLC',
'Bridge Band Communications/At',
'Bright House Networks',
'BrightHouse Networks Bakersfield',
'BrightHouse Networks Indianapolis',
'Brightview ltd',
'Bristol Tennessee Essential Services',
'British Broadcasting Corporation',
'British Telecommunications',
'Broadband for Schools project',
'Broadband VI LLC',
'Broadstripe',
'Broadview Networks',
'Broadview Networks Inc',
'Brooklyn Mutual Telecommunications Coop',
'BruNet, Jabatan Telekom Brunei Darussalam',
'Brutele SC',
'BSNL',
'BT Communications Bangladesh Ltd',
'BT Corporate',
'Bt Latam Brasil Ltda',
'BT Ltd',
'BTC Broadband Service',
'Buckeye Cablevision Inc',
'Bulgarian Telecommunications Company Plc.',
'Bulloch Telephone',
'Bullseye Telecom Inc',
'Burlington Telecom',
'Business Internet',
'Business Static Allocation',
'Business Static Service',
'Buttrey Food & Drug',
'BZQINT-DC',
'Cable & Wireless (Barbados) Limited',
'Cable & Wireless Americas Operations',
'Cable & Wireless Global',
'Cable & Wireless Jamaica Ltd',
'Cable & Wireless Ltd',
'Cable & Wireless Panama',
'Cable & Wireless Panama S.A.',
'Cable & Wireless Telecommunication Services GmbH',
'Cable and Wireless Jamaica',
'Cable Bahamas',
'Cable Bahamas Ltd',
'Cable Onda',
'Cable One',
'Cable One Inc',
'Cable Tica',
'Cable Tv Elpos Ltd.',
'Cablecom GmbH',
'Cablecom Networking Limited',
'Cablelink Internet Sservices Inc.',
'Cablemas Telecomunicaciones SA de CV',
'CablevisiÃ³n SA De CV',
'Cablevision S.A.',
'Cablevision Systems Corp.',
'CAIW Diensten B.V.',
'California Technology',
'Cameroon Telecommunications',
'Canaca-Com Inc',
'Canadian Department of Education',
'Canton Public Library',
'Capitol Construction',
'Caprock UK Limited ISP Infrastructure',
'Caprock UK Ltd',
'Caribou Coffee',
'Cass Cable TV',
'CAT TELECOM Data Comm. Dept, Intrenet Office',
'CAT Telecom public company Ltd',
'Caucasus Online LLC',
'Caucasus Online Ltd.',
'Cavalier Telephone',
'Cbeyond Communications',
'Cbeyond Communications LLC',
'CC Communications',
'Celcom Internet Service Provider',
'Cell C (Pty) Ltd',
'Cellular South Inc',
'Celtel Nigeria Limited t.a ZAIN',
'Central Wisconsin Communications LLC',
'Centrin Internet Service Provider',
'Century Link',
'CEZ ICT Services a.s.',
'Charlotte Customer Market Allocation',
'Charming Shoppes',
'Charter Communications',
'Chickasaw Nation',
'China Education and Research Network',
'China Mobile Communications Corporation',
'China Netcom Group Beijing Communication Company',
'CHINA RAILWAY TELECOMMUNICATIONS CENTER',
'China TieTong Telecommunications Corporation',
'China Unicom AnHui province network',
'China Unicom Beijing province network',
'China Unicom Fujian Province Network',
'China Unicom Guangdong province network',
'China Unicom Guangxi province network',
'China Unicom Hebei province network',
'China Unicom Heibei Province Network',
'China Unicom Henan province network',
'China Unicom IP network',
'China Unicom Jiangsu province network',
'China Unicom Liaoning province network',
'China Unicom Neimeng Province Network',
'China Unicom Shandong province network',
'China Unicom Shannxi Province Network',
'China Unicom Shanxi province network',
'China Unicom XinJiang province network',
'China Unicom Zhejiang Province Network',
'China United Telecommunications Corporation',
'CHINANET Anhui PROVINCE NETWORK',
'Chinanet Fujian Province Network',
'ChinaNet Guangdong Province Network',
'CHINANET hebei province network',
'CHINANET henan province network',
'Chinanet Hubei Province Network',
'Chinanet Hunan Province Network',
'Chinanet Jiangsu Province Network',
'Chinanet Jiangxi Province Network',
'CHINANET liaoning province network',
'Chinanet Shaanxi Province Network',
'CHINANET SHANDONG PROVINCE NETWORK',
'ChinaNet Shanghai Province Network',
'CHINANET SHANXI PROVINCE NETWORK',
'CHINANET Sichuan province network',
'Chinanet Tianjin Province Network',
'CHINANET Zhejiang province network',
'CHINANET-ZJ Hangzhou node network',
'CHINANET-ZJ Huzhou node network',
'CHINANET-ZJ Jiaxing node network',
'CHINANET-ZJ Jinhua node network',
'CHINANET-ZJ Ningbo node network',
'CHINANET-ZJ Shaoxing node network',
'CHINANET-ZJ Taizhou node network',
'CHINANET-ZJ Wenzhou node network',
'Choice One Communications',
'Choopa.com',
'Cia Proc. de Dados do Estado de S Paulo - Prodesp',
'CIK Telecom Inc',
'Cinergy Communications',
'Cinergy-metronet',
'City of Albany Water, Gas & Light Commission',
'City of Alexandria',
'City of Burlington',
'City of Lebanon',
'City of Marietta',
'City of North Kansas City',
'City of Roseville',
'City of Troy',
'City of Wyandotte',
'City West Cable & Telephone Corp.',
'CityOnline Services Ltd',
'CJSC Comstar-Regions',
'CJSC ER-Telecom Holding',
'CL-TEEMSR-LACNIC',
'Claranet Ltd',
'clear wireless llc',
'Clearwire LLC.',
'CloudRadium L.L.C',
'CMA Cablevision',
'CMC Telecom Infrastructure Company',
'CNCGROUP Beijing province network',
'CNISP',
'Cogeco Cable',
'Cogeco Cable Inc',
'Cogent Communications',
'COLOMBIA TELECOMUNICACIONES S.A. ESP',
'COLT Technology Services Group Limited',
'Columbia Electric Supply',
'Columbus Communications Jamaica Limited',
'Columbus Communications Trinidad Limited.',
'Columbus Networks Panama',
'Com Hem AB',
'Comcast - Houston',
'Comcast Business Communications',
'Comcast Business Communications LLC',
'Comcast Cable',
'Comcast Of Houston LLC',
'COMCEL GUATEMALA S.A.',
'Comcen',
'Commonwealth of PA - OA / Integrated Network Manag',
'Community Antenna Service',
'Comnet Communications',
'CompaÃ±Ã­a Dominicana de TelÃ©fonos, C. por A. - CODE',
'Complete Communication Systems Inc',
'COMPLETEL SAS France',
'Computer Centre Ngee Ann Polytechnic',
'Computer Sciences',
'Computer Sciences Corporation',
'Computer Sciences UK Ltd',
'ConnecTel Internet Service Provider',
'Conseils et Systemes Informatiques',
'Consolidated Communications',
'Consolidated Communications Inc',
'Consult Dynamics Inc',
'Content Service Provider Static Network',
'Continental Broadband Pennsylvania Inc',
'Conway Corporation',
'Coollink',
'Cooperative de cablodistribution de l\\'arriere-pays',
'corelink data centers llc',
'Cornerstone Telephone Company, LLC',
'CORPORACION NACIONAL DE TELECOMUNICACIONES - CNT E',
'CORPORACION NACIONAL DE TELECOMUNICACIONES CNT S.A',
'Corporate Leased Lines users',
'Cox Communications',
'CP Internet',
'Cricket Communications',
'Cricket Communications Inc',
'CS LoxInfo Public COmpany Limited',
'CTBC',
'CTCCommunications',
'Cumberland Technologies International',
'Customer Market Allocation',
'Customer Name',
'Customer P2P interface addresses in NL',
'Cutting Edge Communications',
'Cweb.com Inc',
'cwie llc',
'CyberGate Web Solutions',
'Cyberia',
'Cyberlink AG',
'Cybernet 1 Inc',
'Cybernet Communications',
'Cybersmart',
'Cynergycomm.net',
'Cyprus Telecommuncations Authority',
'Cyprus Telecommunications Authority',
'Dai IP su dung cho mang khach hang FTTH o HCMC',
'Daisy Communications Ltd',
'Dalton Utilities',
'Danica Computing',
'Darlington Borough Council',
'Data Matters',
'Data Networks',
'Data Networks Inc',
'Data Pro Business Online',
'Data Return',
'Datacom Caribe',
'Datavo',
'Dauphin Telecom',
'Davita',
'Days Inn',
'Delphi Internet Services Corporation',
'Delta Cable Communications',
'Deltacom',
'dery telecom inc',
'DetectNetwork.US',
'Detroit Public Schools',
'Deutsche Telekom AG',
'Dfw Internet Services Inc',
'Dialin fixed IP',
'Dialog Axiata Plc',
'Dialog Telecommunications',
'DiGi Telecommunications Sdn Bhd',
'Digial Nirvana',
'Digicel Jamaica',
'Digital Path',
'Digital Path Networks',
'Digital Telecommunications Philippines, Inc.',
'DigitelOne',
'DirectSpace Networks, LLC.',
'Dishnet Wireless Limited',
'Dishnet Wireless Ltd, India',
'Distributed Management Information Systems, Inc. (',
'Distributel Communications',
'Distributel Communications Ltd',
'DKI Jakarta',
'Dodo Australia',
'Dogan Iletisim Elektronik Servis Hizmetleri ve Yay',
'Domain Tools LLC',
'donet inc',
'Doylestown Communications',
'Dr Horton',
'DrukNet, Bhutan Telecom',
'DSL Extreme',
'D',
'E. Ritter Communications Inc',
'EarthISP Net',
'EarthLink Ltd. Communications&Internet Services',
'EarthLink Ltd. Communications&Internet Services-Or',
'Eastern Telecom Philippines Inc.',
'Eastern Telecoms Phils., Inc.',
'EastLink',
'Easynet',
'Easynet Limited',
'EasyTech',
'Ecatel LTD',
'ECL TELECOMMUNICATIONS LTD.',
'Eclipse Internet',
'Eclipse Networking',
'Edmonton Telephones Corporation',
'Eds-detroit Diesel',
'Education and Research Consortium of the Western C',
'Education Networks of America',
'Educational institution connected to SEKTORNET',
'EGIHosting',
'eGix',
'EgyNet',
'Egyptian Internet Services',
'Eircom',
'Elink Systems',
'Elion Enterprises Limited',
'Elisa Eesti AS',
'Elisa Oyj',
'Ellijay Telephone Company',
'Embarq Corporation',
'Embratel',
'EMC',
'Emerging Markets Communications Deutschland GmbH',
'Emirates Integrated Telecommunications Company PJS',
'Emirates Integrated Telecommunications Company Pjsc',
'Emirates Internet & Multimedia',
'Emirates Telecommunications Corporation',
'Energia Communications,Inc.',
'Entreprise des Postes et Telecommunications',
'EPB Telecom',
'EPM Telecomunicaciones S.A. E.S.P.',
'Epm Telecomunicaciones SA E.S.P.',
'Equant Inc',
'Equinix Asia Pacific',
'Equinix Asia Pacific PTE Ltd',
'Erie 1 Boces',
'ESA/ESTEC DATAGrid network',
'Escape Communications Corporation',
'eSpeed - Broadband DSL',
'ETB - Colombia',
'Ethio Telecom',
'Ethiopian Telecommunication corporation',
'Etihad Atheeb Telecom Company',
'ETISALAT',
'Etisalat Lanka (Private) Limited.',
'Ets Telephone Company',
'Ettihad Etisalat',
'europroNET Bosnia d.o.o.',
'Evergy S.A.',
'Excell Media Pvt Ltd',
'Execulink Telecom Inc',
'Exetel',
'Extreme Broadband Sdn. Bhd.',
'Fairbanks Redback DSL Pool',
'Fairbanks Scales',
'Fairpoint Communications',
'Fairpoint Communications Inc',
'Farmers Mutual Telephone Company',
'Farmers Telephone Coop Inc',
'Faros Trading LLC',
'Fast Telco Infra Structure IP space',
'Fast Telecommunications Company W.L.L.',
'Fasthosts Internet Limited - UK\\'s largest web host',
'Fastnet Corporation',
'Fasttrack Communications',
'Fastweb',
'Fiber Internet Center',
'Fibernetics Corporation',
'Fidelity Access Networks, LLC',
'Fidelity Communication International',
'First Media Pt Tbk',
'Fiserv',
'Fixed Broadband - Dynamic Pool',
'Florida Hospital',
'FLOW',
'FORTHnet SA',
'Four-U Technologies, LLC',
'Fox Valley Internet Inc',
'fpweb.net llc',
'France Telecom',
'Free SAS',
'Freedom To Surf plc',
'Frontier Communications',
'Frontier Communications of America Inc',
'Frontier Communications of the South LLC',
'FRY Reglet Corporation',
'FTTH GTD MANQUEHUE',
'Fulnett Limited',
'Fuse Internet Access',
'Fuzhou City, Fujian Provincial Network Of Unicom',
'Galaxy Backbone PLC',
'Gamtel Co',
'Gateway Telecoms Integrated Services Limited',
'GCOMM Pty Ltd',
'Geckotech LLC',
'Gemini Group',
'General Insulation',
'Genesis Net Limited',
'Geneva Online Inc',
'Georgia Public Web',
'Ghana Telecom',
'Ghossain & Truelock Enterprises Inc',
'Ghossain &Amp; Truelock Enterprises Inc',
'Giglinx Inc',
'GITN Sdn. Berhad',
'Giza-Zone-DSL',
'Globacom Ltd',
'Global Crossing Comunicaciones Ecuador S.A.',
'Global Internet Access',
'Global Web Intact t/a Screamer Telecoms',
'Globe Telecom',
'Globe Telecom/Innove Communication',
'Globe Telecoms',
'GLW Broadband',
'Go P.L.C.',
'Golden Lines Cable',
'Golden Telekom Tov',
'Golden West Telecommunications',
'Good Communications Co.,Ltd.',
'Government of South Africa',
'gradwell dot com Limited',
'Grafton Technologies',
'Grand County Internet Services',
'Grande Communications',
'Grande Communications Inc',
'Granite State Long Distance',
'Greenfield Communications',
'Greenlight',
'grid 4 communications inc',
'Grid4 Communications',
'Griffin Information Systems Limited',
'griffin information systems ltd',
'Griffith Company',
'Gsm Kazakhstan Ojsc kazakhtelecom Llp',
'GTEL MEXICALI',
'GTS Czech s.r.o.',
'GTS Slovakia, a.s.',
'Guadalupe Valley Telephone Coop Inc',
'Guadalupe Valley Telephone Cooperative',
'Gulfnet International Co.',
'GulfNet KSA',
'Guyana Telephone & Telegraph Co Ltd',
'Guyana Telephone & Telegraph Co.',
'GV/WFL BOCES Educational TechnologyService',
'Gvtc/gvcs-cable-cpe Dynamic Pool',
'GWI',
'ha-vel internet s.r.o.',
'Halton Borough Council',
'Hamamatsu Corporation',
'Hamilton Hydro / FibreWired',
'Hanaro Telecom Inc.',
'Hanaro Telecom, Inc.',
'Hargray Communications Group Inc',
'Harrisonville Telephone Company',
'Hastingwood Securities Ltd.',
'Hathway Cable and Datacom Pvt Ltd',
'Hathway IP Over Cable Internet Access Service',
'Haviland Telephone Company',
'Hawaiian Telcom Services Company Inc',
'Haynes Corporation',
'HEAnet Limited',
'Heartland-COG/North Central Ohio Computer Cooperat',
'Heico Aerospace Corporation',
'Hellas On Line S.A.',
'Hetzner Online AG',
'Hewlett-Packard Company',
'Hi3G Access AB',
'Hiawatha Broadband Communications Inc',
'Highland Network Ltd',
'Hilton Hotel Corporation',
'Holiday Inn Crowne Plaza',
'Home Telephone Company Inc',
'homecable-ap',
'Hong Kong Broadband Network Ltd',
'Hood Canal Communications',
'Horizon Telcom',
'Horry Telephone Coop Inc',
'Host Idaho',
'Hosting Services',
'Hosting Services Inc',
'Hughes Network Systems',
'Hughes Network Systems LLC',
'Huron Telecommunications Cooperative Limited',
'Hurricane Electric',
'Hutchison Global Communications',
'Hutchison Max Telecom Limited',
'Hydrosoft Internet',
'HyperSurf Internet Services',
'HYUNDAI COMMUNICATIONS & NETWORK',
'IBM India PVT Ltd',
'ICA Canada On-Line',
'ICONZ',
'ICPNET Cable',
'IDEA ISP Subscriber IP Pool',
'iiNet Limited',
'Imagine Telecommunications Ltd',
'Inap Zscaler',
'Inconet Data Management Sal',
'Ind. Company Cable Tv Inc',
'Indiana Fiber Network LLC',
'Indiana Fiber Network, LLC',
'Indonesia Online Access',
'Indosat Internet Service Provider',
'indosatm2 internet service provider',
'INDOSATnet Internet Service Provider',
'INDUSTRIE',
'Industry I-Net',
'Infinity Developments Limited',
'InfoChannel',
'Infocommunication Provider',
'Infocrossing',
'Infocrossing Inc',
'Infoline',
'Information Technology Company (ITC)',
'INFRA-AW',
'infrastructure in SPb',
'Inglis House',
'Inland Internet',
'InLink Communications Company',
'Inoc, LLC',
'Insight Communications Company Inc',
'Integra Telecom',
'Integrated Digital Services',
'Intelcom Group',
'Intelsat GlobalConnex Solutions',
'Interbel Telephone Cooperative',
'Interconnection with RAEI backbone',
'Internet America Inc',
'Internet Cable Plus C. A.',
'Internet Connect Inc',
'Internet Initiative Japan',
'Internet Service Provider',
'Internet Solutions',
'Internet technologies Namibia',
'Interneta pasaule SIA',
'INTERNEXA S.A. E.S.P',
'Internode',
'Interoute Deutschland GmbH',
'Interstate Telecommunications Cooperative',
'Intervolve',
'Intred S.p.A.',
'Invitel Tavkozlesi Zrt.',
'IO Data Centers',
'Ip Apple Computer Ro19',
'Ip House',
'IP Matrix, S.A. de C.V.',
'IPNetZone',
'IRECTONPC--ISP-NETBLK',
'Iseek Communications Pty Ltd',
'ISHAN\\'S IP POOL',
'ISN Communications',
'ISP',
'ISP Alliance',
'ISP Cote d\\'Ivoire',
'Ispn Inc',
'ITC Deltacom',
'IWeb Technologies',
'Jacobs Engineering',
'Jamii Telecommunications Limited',
'Japan Network Information Center',
'Jazz Telecom S.A.',
'Jb Wireless Inc',
'JCI Jones Chemicals Inc',
'Jervis B Webb Company Ltd',
'Jones Lang Lasalle',
'JSC Ukrtelecom',
'JTGlobal',
'Jump Network Services S.R.L.',
'Kabel Baden-Wuerttemberg GmbH & Co. KG',
'Kansas City Customer Market Allocation',
'Kaplan Telephone Company',
'Karaamin Shiraz ADSL ussrs Pool',
'Karib-cable-kelcom-international-slu',
'KC Web',
'Kcom',
'KDDI CORPORATION',
'Kenya Data Networks',
'Kenya Education Network',
'Kenyan Post & Telecommunications Company / Telkom',
'Keyways',
'Kinex Networking Solutions',
'King County Library System',
'KISTI',
'Klein Independent School District',
'Knology',
'Knology Inc',
'Korea Telecom',
'ksc commercial internet co. ltd',
'KSC Commercial Internet Co. Ltd.',
'Kuentos Communications',
'Kujtesa Internet Services',
'Kuwait Electronic and Messaging Services Company',
'Kuwait Telecommunication Company (Under Associatio',
'L-3 Communications',
'Lambeau Telecom',
'latisys-chicago llc',
'Laurel Highland Telephone Company',
'Leased Line customers',
'Leased Line- LAN Range',
'LeaseWeb B.V.',
'LEK Internet Services',
'Level 3 Communications',
'Lg Powercomm',
'LGfL Internet J',
'Libantelecom',
'Liberty Bell Telecom, LLC',
'Libyan Telecom and Technology',
'Ligtel Communications',
'Limestone Cable Vision',
'Ling Wang Internet Co',
'Link Egypt',
'LINKdotNET Telecom Limited',
'Linkem SPA',
'LinkLINE Communications',
'Linkoping',
'Linode',
'Linode, LLC',
'Local Infrastructure Expansion For Dsl (pppoe)',
'LocalNet',
'LocalTel Communications',
'Lodgenet',
'Logan_Telephone_Cooperative',
'Logix Communications',
'Logix Communications Lp',
'Logosoft OnLine ISP',
'Los Angeles Unified School District',
'Louisiana Board of Regents/Louisiana Optical Netwo',
'LUMOS Networks',
'lumos networks corporation',
'Lutheran Medical Center',
'M1 Connect Pte Ltd',
'M1 Ltd',
'Madison Telephone Company',
'Magyar Telekom plc.',
'Mahanagar Telephone Nigam Ltd',
'Maine Libraries/Dept. of Education',
'Manage5nines Ltd',
'Manitoba NetSet',
'Maritime Telecommunications Network',
'Massillon Cable Communications',
'Maxis Broadband Sdn Bhd',
'MCSNet',
'Mediacom Communications Corp',
'Mediacom Communications Corporation',
'Medical and Educational Data Network',
'Megalan Network Ltd.',
'Megapath',
'Melbourne Server Hosting Ltd',
'Melita Plc',
'Memphis Publishing Company',
'Meridian Business Centers',
'Meridian Telekoms Inc.',
'Meriplex Communications Ltd',
'Merit Network',
'Messagelabs Inc',
'MessageLabs Limited',
'MessageLabs Sydney',
'METRO-E PAMPANGA',
'MetroCast Cablevision',
'Metrocast Communications',
'Metronet (UK) Limited',
'MetroPCS Wireless',
'MetroPCS Wireless Inc',
'Michelin Manufacture Francaise, Telecommunication',
'Michwave Technologies',
'Microsoft Bingbot',
'Microsoft Corporation',
'Mid-mo Internet Solutions, LLC',
'Midcontinent Media Inc',
'Middle Michigan Network for Educational Telecommun',
'Mikrotec Internet Services',
'Milleni.com',
'Millington Catv Inc',
'Minet',
'MLS Projetos de Informatica',
'Mobile Interim Co -1- Sal',
'Mobile Services',
'Mobily Corp.',
'MOBISTAR',
'Mobitel',
'Monroe County Library System',
'Montage Beverly Hills',
'Montana Sky Networks',
'Moonbeam Equipment Communicati',
'Mora Telematika Indonesia Pt',
'Moretrench American Corporation',
'Morgan Building & Spa Manufacturing Corporation',
'Morrow-Meadows Corporation',
'Moscanet SAL',
'Moscow Institute of Physics and Technology',
'Motricity Inc',
'Mount Royal University',
'Mount Sinai School of Medicine',
'Mountain Cablevision',
'MPInet',
'Mpower Communications Corp.',
'MSN Wireless',
'MSN Wireless Inc',
'MTN Business Solutions (Pty) Ltd',
'MTN Network Solutions Pty Ltd',
'Mto Telecom Inc',
'MTS Allstream',
'Multacom Corporation',
'Multi-Links Telecommunications Limited',
'Mumbai Network Operations',
'MWEB Connect',
'myLoc managed IT AG',
'nacamar GmbH',
'Namincheon Brodcasting Co., Ltd.',
'nandani house 58 cha 1',
'Nanosolar',
'National Informatics Centre',
'National Oilwell Varco',
'National Telecom Corporation',
'Navega.com S.A.',
'NC Numericable S.A.',
'Nebula Oy',
'NEC BIGLOBE Ltd.',
'Nec Corporation',
'Neda Gostar Saba Data Transfer Company Private Joi',
'Neostrada Plus',
'Neotel Ltd',
'Neotelekom Zao',
'Nerim SAS',
'Net Access Corporation',
'Net1',
'Net2Net Corp.',
'NetAccess Systems',
'Netco Solutions',
'Netcom Africa Limited',
'Netelligent Hosting Services',
'Netelligent Hosting Services Inc',
'Neterra Ltd.',
'Netia SA',
'netINS',
'NetNet',
'netpage inc',
'Netriplex LLC',
'Netscalibur UK Ltd',
'NetVision',
'Netvision\\'s BroadBand service',
'NetWest Online',
'Network Billing Systems LLC',
'Network For Net Based Firewall Service',
'Network Operations Center',
'Network Solutions LLC',
'Network Tallahassee',
'Network Technology (AUST) P/L',
'Networktel Telephone',
'New Age Consulting Service',
'New Bridge Technologies',
'New Edge Network',
'New England School of Law',
'New Technologies Group N.V.',
'New Wave Communications',
'New West Consumer ADSL',
'Newroz Telecom Ltd.',
'Newsat Ltd',
'nextera communications llc',
'Nextgen Communications SRL',
'Nextgen Networks',
'Nianet A/S',
'Nildram',
'Nildram IP\\'s',
'Nile Online',
'Nobis Technology Group, LLC',
'Nokia Corporation',
'Norfolk County Council',
'North American Telecommunications Corporation',
'North Central Communications',
'Northern Telecom',
'Northern Valley Communications',
'Northland Cable Television Inc',
'Northwood University',
'North_Central_Telephone_Cooperative',
'NOVIS TELECOM, S.A.',
'Novus Entertainment',
'NSS S.A.',
'NTT Communications',
'Ntt Communications Corporation',
'Ntt Singapore Pte Ltd',
'NuLink',
'Nysernet/WebGenesis',
'Oarnet',
'OC3 Networks & Web Solutions, LLC',
'Oglecom',
'OJSC MegaFon',
'OJSC North-West Telecom',
'OJSC Rostelecom',
'OK-NET Co,. Ltd',
'Oklahoma State Regents for Higher Education',
'Oktopusnet Ooo',
'Olypen',
'Omani Qatari Telecommunications Company SAOC',
'Omantel',
'Omnicom Group Inc',
'ON S.A.',
'One Communications Corporation',
'OneXS International B.V.',
'Onitelecom - Infocomunicacoes, S.A.',
'ONO',
'Onyx Internet Ltd',
'Open Computer Network',
'Opera Mini Proxies',
'Opera Software Asa',
'Operbes, S.A. de C.V.',
'Optimum Online',
'Optimum WiFi',
'Orange DOMINICANA',
'Orange Home UK',
'Orange mobile',
'Orange Moldova Network',
'Orange Uganda Ltd',
'Orange WBC Broadband',
'Orange-jordan',
'Orca Communications',
'Orcon Corporation',
'Oregon Steel Mills - Rock Mtn',
'Orion Telekom Tim ADSL Pool',
'Orion Telekom Tim Doo',
'Oshean Inc',
'osnatel GmbH',
'OTEnet S.A.',
'OVH',
'Ovh Systems',
'Ovi Services',
'Oxford County Telephone & Telegraph Company Inc',
'Ozburn Hessey',
'Pacific Coast Container',
'Pacific Internet (Australia) Pty Ltd',
'Pacific Internet Limited',
'Pacific One Net Limited',
'Packerland Broadband',
'Pacnet',
'Pacnet Ltd',
'Pacnet Services (Japan) Corp.',
'Paetec',
'PAETEC Communications',
'Paetec Communications Inc',
'Partner Communications',
'Pathway Communications',
'PCCW Business Internet Access',
'Peg Tech',
'PenTeleData',
'Peoples Communications',
'PERN-Pakistan Education & Research Network is an',
'Persona Communications',
'Persona Communications Inc',
'Petersburg Internet Network Llc',
'Philippine Long Distance Telephone',
'philippine long distance telephone company',
'Phonoscope',
'Pioneer Elabs Ltd.',
'Pioneer Long Distance',
'Pioneer Wireless',
'PJSC Badr Rayan Jonoob',
'PLDT Sampaloc',
'Pleasant Valley Baptist Church',
'Plexus',
'plot 325 lane 22 new dohs',
'Plusnet PLC',
'PlusNet plc.',
'PlusNet Technologies Ltd',
'PO TURBHE',
'Pocketinet Communications',
'Point To Point Broadband',
'Point to Point Links',
'Pool',
'pool of addresses assigned to dsl lines with',
'Popp.Com Inc',
'Posta dhe telekomi i Kosoves',
'PoundHost Internet Services',
'PowerNet',
'Prima S.A.',
'Prime Signal',
'Primus Telecommunications Canada',
'Primus Telecommunications Canada Inc',
'Private Joint Stock Company datagroup',
'Professional Communications',
'Project Mutual Telephone Cooperative Association',
'Pronea AS',
'Provider Lir',
'Provider SoluÃ§Ãµes TecnolÃ³gicas Ltda',
'Przedsiebiorstwo Uslug Specjalistycznych Alamein Sp Zoo',
'PT Excelcomindo Pratama',
'PT INDOSAT MEGA MEDIA',
'PT Indosat Tbk.',
'PT Jembatan Citra Nusantara',
'PT QIANDRA INFORMATION TECHNOLOGY',
'PT Telkom Divisi Regional V Jawa Timur',
'PT Telkom Indonesia',
'PT UNINET Media Sakti',
'PT Varnion Technology Semesta',
'PT. Comtronics Systems',
'PT. Core Mediatech (DNET)',
'PT. Khasanah Timur Indonesia',
'PT. Media Antar Nusa',
'PT. TELEKOMUNIKASI INDONESIA',
'PT. Wireless Indonesia',
'PTCL',
'Public Service Data',
'Publix Super Markets',
'Puerto Rico Telephone Company',
'Pune Network Operations',
'Putian City A Broadband',
'Pyramid.Net',
'Q9 Networks',
'Q9 Networks Inc.',
'Qrixseodaemuncable, Inc.',
'Qtel',
'Quadro Communications Co-Operative',
'Quantum Communications LLC',
'QuickNet AB',
'Quicksilver Resources',
'Qwest Communications',
'R Cable y Telecomunicaciones Galicia S.A.',
'Radiant Communications 32482',
'RADIOGRAFICA COSTARRICENSE',
'Railtel Corporati0n of India Ltd',
'Rainbow Broadband',
'Rainy Day Software Corp.',
'Ramapo College of New Jersey',
'RASER',
'Ratt Internet Kapacitet i Sverige AB',
'RAYA Telecom',
'RCOM-Static-DIA',
'Readylink Internet Services Pvt. Limited',
'Red Cientifica Peruana',
'Redstone Managed Solutions Ltd',
'REDtone',
'Reliablehosting.com',
'Reliance Communications',
'Reliance Communications Ltd',
'RENATER',
'Reserve Long Distance Company',
'Reserved for I-Way / Claranet Customers in Clarane',
'Residence Inn',
'Respina Networks & Beyond PJSC',
'Rio Grande Communications',
'RIOMEDIA Frydek Mistek',
'RKWL AUTOM/DS 3 INTERNET',
'Rm Education PLC',
'Road Runner',
'Robert Half International',
'Rock Hill Telephone Company Inc',
'Rogers Cable',
'Rolled Alloys',
'Romtelecom Data Network',
'romtelecom s.a',
'Routcom',
'Routit-wap-e',
'Rural Telephone Service Company',
'Rural Telephone Service Company Inc',
'Russian Central Telegraph, Moscow',
'SAC Affaires VL',
'Saddle Mountain Wireless',
'Saero Network Service LTD',
'Safaricom',
'Sago Networks',
'SAIC Inc',
'SAINET Internet',
'Salsgiver Engineering',
'Salt Palace Convention Center',
'SAN JOSE',
'Sandefjord, Norway',
'Sarl ICOSNET',
'Saskatchewan Telecommunications Holding Corporation',
'SaskTel',
'Saturn R Internet Ooo',
'Saturn R Internet Ooov',
'Satyam Infoway (P) Ltd.',
'SaudiNet, Saudi Telecom Company',
'Savage Communications',
'SAVVIS Communications Corporation',
'ScanSafe',
'ScanSafe COP',
'ScanSafe FRA',
'ScanSafe LON',
'ScanSafe PAR',
'ScopeSky Communication and Internet Ltd.',
'Secure-24 Inc',
'Select System Infrastructure of Sumperk region',
'SelectNet, Inc.',
'Seokyung Cable Television Co.. Ltd.',
'SERCOM de Honduras',
'Server Suites LLC',
'SFR',
'Shared-Fortigate-Project',
'SHATEL Ent. DSL Network',
'Shenandoah Cable Television LLC',
'Shrewsbury Electric & Community Cable',
'Si.mobil D.d.',
'Sierra Advantage',
'Sify Limited',
'sigecom llc',
'Silo Wireless',
'Simbanet (T) Ltd',
'Singapore Telecommunications',
'SingNet Pte Ltd',
'Singtel',
'SingTel Internet Exchange',
'SiOL d.o.o. (Slovenia Online)',
'Sistema Shyam Teleservices Ltd',
'SITA-Societe Internationale de Telecommunications',
'SITA-Societe Internationale de Telecommunications Aeronautiques',
'Sky Broadband',
'SkyBest Communications',
'Skylogic S.p.A.',
'Skynet Belgium',
'Skyriver Communications',
'Skytel Networks Ireland Ltd',
'Skyvision Global Networks Ltd',
'Skyway West',
'Slovak Telecom, a. s.',
'Slovanet a.s.',
'Smart Broadband Incorporated',
'Smart Telecom',
'Smart Telecom Pt',
'SmarTone Mobile Communications Ltd',
'Smitcoms N.v.',
'Snap Net',
'So-net Service',
'SOFTNET d.o.o.',
'Software Technology Parks of India',
'Solcon Internetdiensten B.V.',
'Solutions Manufacturing',
'Somerville Board of Education',
'SONATEL Societe Nationale Des Telecommunications D',
'Sonic.net',
'Sophidea',
'Source Cable',
'South Carolina Telecommunications Group Holding LLC',
'South Slope Coop Telephone Company',
'South West Communications Group Ltd',
'Southern Billing Service',
'South_Central_Rural_Telephone_Cooperative',
'Spansion LLC',
'Speakeasy Inc',
'Specialty Rental Tools & Supply',
'Spectra Isp Networks PVT Ltd',
'Spectranet Ltd',
'Speed Buggy',
'SpeedCast Limited',
'SPiDiGO',
'Spring City Cable',
'Sprint',
'Sprint/United Information Service',
'Sri Lanka Telecom',
'SRT Communications Inc',
'SSP Yhtiot Oy',
'St Mary\\'s University',
'St. Louis Customer Market Allocation',
'St.Petersburg',
'Stage Networks Llc',
'Starhub Broadband',
'Starhub SWE Business',
'State Street Investment Trust',
'Static Business - Cinergy MetroNet',
'Static Business Pool - Cinergy MetroNet',
'STE ISP Network 1',
'Steadfast Networks',
'Stratos Global Communications',
'STUDIO 6',
'Subscriber Block 2 (Dedicated for all H3G ROI serv',
'Sudatel',
'Suddenlink Communications',
'sungard availability services lp',
'SUNRISE',
'Super Broadband Network',
'Super iMax',
'Super Radiator Coils',
'SUPERNET Limited',
'SureWest Broadband',
'Surfcontrol',
'Surfnet',
'Surfnet Communications',
'Susquehanna Data Services Inc',
'SWAZILAND PTC',
'Swift Networks Limited',
'Swisscom Fixnet AG',
'Symbio Networks',
'Syrian Telecommunications Establishment ( STE)',
'Systemmetrics Corporation',
'T-2 Access Network',
'T-on Telecom Co Ltd',
'T-Online ADSL clients',
'T-Systems ITS, Internet',
'Talk Internet Limited',
'TalkTalk',
'TANZANIA TELECOMMUNICATIONS CO. LTD',
'Tata Communications',
'Tata Teleservices Limited -GSM Division',
'Tata Teleservices Maharashtra Ltd',
'Tbaytel',
'TDC BB-ADSL users',
'TDC Oy Finland',
'TDC Sverige AB',
'TDS Computing Services',
'TDS Telecom',
'TDS Telecommunication Corporation',
'TE Data',
'Technocraft Industries Ltd',
'TECINFO',
'Tek Channel Consulting LLC',
'Teklinks Inc',
'TekSavvy Solutions',
'Teksavvy Solutions Inc',
'Teksystems Inc',
'Telco In A Box',
'Telconet S.A',
'TelCove, Inc.',
'Tele Danmark',
'tele-fonika cable americas corporation',
'Tele-Media Corporation',
'Tele2 Mobile',
'Tele2 SWIPnet',
'Tele2/SWIPnet',
'TELEBUCARAMANGA S.A. E.S.P.',
'Telecom Algeria',
'Telecom Argentina S.A.',
'Telecom Corporation Of New Zealand Ltd',
'Telecom Italia',
'Telecom Italia NET',
'Telecom Italia S.p.A.',
'Telecom Italia S.p.A. TIN EASY LITE',
'Telecom Italia SPA',
'Telecom Italia Wireline Services',
'Telecommunication Company of Iran',
'Telecommunication Services of Trinidad and Tobago',
'telecomplus',
'Telecomputing Norway AS',
'TELEFLEX AEROSPACE MANUFACTURING GROUP (Sermatech',
'Telefonica Data S.A.',
'Telefonica de Argentina',
'Telefonica del Peru',
'Telefonica del Peru S.A.',
'Telefonica Empresas',
'Telefonica O2 UK',
'Telefonos del Noroeste, S.A. de C.V.',
'Telekom Austria',
'Telekom Malaysia Berhad',
'Telekom Slovenije D.D.',
'TELEKOM SRBIJA a.d.',
'Telenor Norge AS',
'Telepacific Communications',
'Telepak Networks',
'Telesat Canada',
'Teleset Servis Ooo',
'Telesphere Networks',
'Telewest Ltd',
'Telgua',
'TeliaSonera Finland Oyj',
'Telkom SA Limited',
'Telkom SA Ltd',
'Telkomsel',
'Tellcom Iletisim Hizmetleri A.s.',
'Telmex Chile Internet S.A.',
'Telmex Colombia S.A.',
'Telnes Broadband.-hq',
'Telnet Worldwide',
'Telone',
'Telone PVT Ltd',
'Telstra Internet',
'TelstraClear Ltd',
'Telus Communications',
'Telus Communications Inc',
'Telus Quebec',
'TeraGo Networks',
'Terago Networks Inc',
'TeraGo PTP Networks',
'Texas Broadband',
'Texas Health Resources',
'The Bahamas Telecommunications Company',
'The Cloud Networks Ltd',
'The Internet Connection',
'The Jackson Laboratory',
'The Middleby Corporation',
'The Narragansett Electric Company',
'The Noor Group',
'The Reynolds Company',
'The Venetian Macao-Resort-Hotel',
'This field was added to fix syntax error',
'This space is statically assigned.',
'Three Indonesia',
'Tikona Digital Networks Pvt. Ltd.',
'Tikona Infinet Ltd',
'TIME dotCom Berhad',
'TIME Telecommunications Sdn Bhd',
'time warner cable inc',
'Timico Limited',
'Tire-1 Ip Transit Provider Of Bangladesh - 1',
'TM VADS DC Hosting',
'TMNET',
'TMnet Telekom Malaysia',
'Tng Worldwide',
'TOKAI Corporation',
'TOT Public Company Limited',
'Totelcom Communications Llc',
'Towerstream I',
'Toyota Motor Corporation',
'TPG Internet Pty Ltd.',
'Traci Network Solutions Inc',
'Trane Company',
'Transit Wireless Llc',
'Transmision de Datos TELNOR',
'Transtelco Inc',
'Transvision Reseau',
'TRE-FOR Bredbaand A/S',
'Triple T Internet PCL',
'True Broadband',
'True Broadband by True Online',
'True Internet',
'True internet Co., Ltd.',
'True Internet, Ltd.',
'TT&T, Internet Service Provider, Bangkok, Thailand',
'Tullahoma Utilities Board',
'Turk Telekom',
'Turk Telekom ADSL-200K 2',
'Turkcell Internet',
'Turner Broadcasting System',
'Tussa IKT AS',
'TVCABO Mocambique',
'Tvnetwork Inc.',
'TW Fresno Customers',
'TW Houston Customers',
'TW Ontario Customers',
'TW Phoenix Customers',
'tw telecom holdings',
'U\\'s Communications Corp.',
'U-NET Internet Ltd',
'UAB Baltnetos komunikacijos',
'Ubiquity Server Solutions Chicago',
'Ubiquity Server Solutions Dallas',
'Ubiquity Server Solutions New York',
'Ubiquity Server Solutions Seattle',
'UBTANET',
'UCC Corporate Customer',
'UCN',
'Ucweb Technologies',
'Ucwebhost Inc',
'UKOnline DSL customers',
'Ultimate Internet Access',
'unallocated',
'Unet B.V.',
'Uni2',
'UNICOM ZheJiang Province Network',
'Uninet',
'Uninet S.A. de C.V.',
'United Technologies',
'United Telephone Company',
'University of Nebraska Medical Center',
'Unwired',
'Unwired Broadband',
'Unwired Broadband Inc',
'Upc Austria GmbH',
'UPC Ceska Republica, s.r.o.',
'UPC Ireland',
'UPC Norge',
'UPC Polska Sp. z o.o.',
'UPC Romania BUCURESTI FIBER',
'UPC Romania SRL',
'Upper Peninsula Telephone Company',
'US Department of Energy',
'US Signal Company, L.L.C.',
'USAi.net',
'USDA',
'used for static broadband customers in hyderabad',
'Utility Telephone',
'UUNET Non-Portable Customer Assignment',
'Vanco GmbH',
'Varna, Bulgaria',
'Vault Networks Inc',
'VDC',
'Vectra S.A.',
'Vegasnap Llc',
'Velocity Network Inc',
'Ventelo AS',
'Veraciti',
'Veracity Networks LLC',
'Verat DOO',
'Verizon Business',
'Verizon Communications',
'Verizon FiOS',
'Verizon Internet Services',
'Vermont Telephone Company',
'Versatel Deutschland',
'Videotron Ltee',
'Viettel Corporation',
'VimpelCom',
'Vineyard Christian Fellowship',
'Virgin Media',
'Virtela Technology Services Inc',
'Visafone Communications Limited',
'Vision Communications',
'Visionary Communications',
'visionary services inc',
'vividwireless Pty Ltd',
'Vizada Networks AS',
'VMware Inc',
'Vocus Pty Ltd',
'Vodacom',
'Vodacom Ltd',
'Vodafone Australia Pty.',
'Vodafone Data',
'Vodafone Essar Spacetel Ltd',
'Vodafone India',
'Vodafone ISP',
'Vodafone Italia',
'Vodafone New Zealand Broadband',
'Voicecom Telecommunications Llc',
'Volia',
'Voonami Inc',
'Vox Datapro',
'voxclever ltd',
'VTR Banda Ancha S.A.',
'VTX Communications',
'VTX Services SA',
'Wananchi Online Limited',
'Wandering WIFI',
'Warid Telecom Uganda',
'Wash NOC First Network',
'Washington State Board for Community & Technical C',
'Wataniya Telecom',
'Wateen Telecom Ltd',
'Wave Broadband',
'Wave-Speed Networks, Inc.',
'Wavespeed',
'Waveworks Limited',
'Web Africa',
'Web Force Systems',
'WEBPASS',
'webroot inc',
'Webroot Services Ltd',
'Webroot Software',
'Websense Hosted Security Network',
'Wells Fargo & Company',
'west ip communications inc',
'West Wisconsin Telcom Cooperative',
'Wharf T&T Limited',
'WideOpenWest',
'WightFibre',
'Wildblue Communications',
'Wilhelm.Tel GmbH',
'WiLine Networks',
'Wilkes Communications',
'willamette valley internet',
'Wilogic Inc',
'Wind Hellas Telecommunications SA',
'WIND Telecom S.A.',
'WIND Telecomunicazioni S.p.A',
'Windstream Communications',
'Windstream Communications Inc',
'Windstream Nuvox Inc',
'Wins, LLC',
'Wireless Broadband Access Network',
'Wireless Broadband of Oklahoma',
'Wireless Data Service Provider Corporation',
'Wireless Solution India Pvt Ltd.',
'Wireless-HSD',
'Wireless/Satellite Division of Day',
'Wisper Isp Inc',
'Wood County Telephone Company Inc',
'Woodforest National Bank',
'Woolstock Mutual Telephone Association',
'World Access / Planet Internet',
'World Phone Internet Services Private Limited',
'WorldNet Telecommunications',
'Worldpath Internet Services',
'WorldWide Web Services',
'www.funknetz.at GmbH',
'Wwz Telekom Ag',
'Wyoming.com',
'XO Communications',
'Xplornet Communications',
'Xplornet Communications Inc',
'Xpressweb Internet Services',
'XS4ALL Internet BV',
'XTom WebHosting LLC',
'Yatanarpon Teleport',
'YHC Corporation',
'YMCA',
'YOU Telecom India Pvt Ltd',
'YTL Communications Sdn Bhd',
'Zain Data-Jordan',
'ZAMTEL',
'Zen Internet',
'Ziggo BV',
'Zimmerman Communications',
'Zito Media',
'ZON TV Cabo',
'Zscaler',
'Zscaler Inc',
'zscaler inc.',
'[ CBB - IP pool for customers ]' 
) ";
 

$ORGS2 =" co in  (
 '(previously known as CyberWay Pte Ltd)',
'013 Netvision Ltd',
'1001943 Ontario Ltd',
'123.Net',
'15b 53 55 corporate drive bridgewater nj 08807 usa',
'24Online Broadband Server',
'3BB Broadband',
'Aamra Networks Limited',
'Abissnet sh.a.',
'Abovenet Communications Inc',
'Acantho S.p.a',
'Access Broadband',
'Access Kenya Group Ltd',
'ACD.net',
'Ace',
'Adams CATV',
'Adept Internet (Pty) Ltd CT',
'Administracion Nacional de Telecomunicaciones',
'Advanced Colocation',
'Advanced Tel Inc',
'Aero Group Inc',
'af net',
'AF NET Internet Services',
'Aflac',
'Aftab IT Limited',
'Agence Tunisienne Internet - ATI',
'AGT',
'Air Advantage LLC',
'Airband Communications Inc',
'Airespring',
'Airtel',
'Airtel Broadband',
'Airwave Networks Incorporated',
'AJAY Syscon PVT Ltd',
'Alands Datakommunikation Ab',
'Alaska Communications Systems Group',
'Albtelecom Sh.a.',
'Alenco Communications',
'Alestra S. De RL De CV',
'Algerie Telecom - FAWRI',
'Alice DSL',
'Allendale Telephone Company',
'Allhostshop.com',
'Allied Stone',
'ALLTEL Corporation',
'Alpheus Data Services, L.L.C.',
'Alternate Access Inc',
'Amazon.com',
'American Internet Services, LLC.',
'American Packaging Corporation',
'American Red Cross',
'Amerisuites',
'Amnet Broadband Pty Ltd',
'Amnet Cable San Pedro Sula',
'AMNET TEL y cia S en C de C.V.',
'AMP Corporate Telecommunications',
'Anchorage Redback DSL Dynamic Pool',
'Anchorage Redback DSL Pool',
'ANEKS d.o.o.',
'Antietam Cable Television Inc',
'Apollo Telecom (Pvt.) Ltd.',
'Arab Company For Internet & Communications Service',
'Arcor AG',
'Areti Internet LLC',
'Armstrong Utilities Inc',
'Arqiva Communications Ltd',
'Art Matrix - Lightlink',
'ARtelecom',
'Ascus Telecom GmbH',
'Asianet is a cable ISP providing',
'ASK4 Ltd',
'Aston University',
'AT&T',
'AT&T AMS GIDC External Range',
'AT&T Enhanced Network Services',
'AT&T Global Network Services',
'AT&T Global Network Services Asia Pacific',
'AT&T IDC Redditch',
'AT&T Internet Services',
'AT&T Managed Firewall Network Based - Sydney',
'AT&T Managed Firewall Services NB2',
'AT&T MFS-NB 2.0-- Mesa, AZ - Trial',
'AT&T Mobility LLC',
'AT&T Services',
'AT&T U-verse',
'AT&T Worldnet IP Services',
'AT&T Worldnet Services',
'Athens',
'Atlanta Customer Market Allocation',
'Atlantic Broadband',
'Atlantic Telephone Membership Corp.',
'Atos IT Solutions and Services GmbH',
'Atria Convergence Technologies Pvt. Ltd.',
'Att Bco Mcrc',
'Att Corp-intra-legacy T Legal',
'ATX Telecommunications Services',
'Augere Wireless Broadband Bangladesh Limited',
'Axis Telekom Indonesia Pt',
'AXTEL',
'Axtel, S.A.B. de C. V.',
'Axtel, S.A.B. de C.V.',
'B2X Online',
'Bahnhof Internet AB',
'Bahrain Telecommunication Company',
'Baja Broadband',
'Baldwin County Internet',
'baldwin telecom inc',
'bandwidth communications ltd',
'Bandwidth.com',
'Banglalion WiMAX',
'Barracuda Networks Inc',
'Batelco ADSL service',
'Batelco Jordan',
'Bayan Telecommunications Incorporated',
'Bayanat Al-Oula For Network Services',
'BB BROADBAND CO., LTD.',
'Bce',
'BCL EAST,Infinity Building, Tower One, 1st Floor',
'BDCOM Online Limited',
'Be Un Limited',
'Beam Telecom Pvt Ltd',
'Beam Telecom Pvt Ltd, Hyderabad',
'Beehive Telephone Company',
'Beeline',
'Beijing Teletron Telecom Engineering Co., Ltd.',
'Belgacom Skynet',
'Belize Telemedia Ltd',
'Bell Aliant Inc',
'Bell Aliant Regional Communications Inc',
'Bell Canada',
'BellSouth.net',
'Ben Lomand Rural Telephone Coop Inc',
'Bend Cable Communications Inc',
'Bend Cable Communications, LLC',
'Bezeq',
'Bezeq International',
'BH Telecom d.d. Sarajevo',
'Bharat Sanchar Nigam Ltd',
'Bharti Airtel Limited',
'Bharti Airtel Ltd.',
'Bharti Broadband',
'Bharti Infotel Ltd',
'Bharti Telenet Ltd. Tamilnadu',
'Birch Telecom Inc',
'BitWise Systems',
'BKK Fiber AS',
'Bkk Marked AS',
'Black Oak Computers',
'Blackfoot Telephone Coop Inc',
'Blackney Hayes Architects',
'Blink Communications',
'Blue Coat Systems Inc',
'BluesMedia InfoTech',
'Botswana Telecommunications Corporation',
'Bouygues Telecom',
'Brainstorm Internet',
'Brandenburg_Telephone_Company',
'BRAS Pools - Charminar',
'Bredbandsbolaget AB',
'Bresnan Communications LLC',
'Bridge Band Communications/At',
'Bright House Networks',
'BrightHouse Networks Bakersfield',
'BrightHouse Networks Indianapolis',
'Brightview ltd',
'Bristol Tennessee Essential Services',
'British Broadcasting Corporation',
'British Telecommunications',
'Broadband for Schools project',
'Broadband VI LLC',
'Broadstripe',
'Broadview Networks',
'Broadview Networks Inc',
'Brooklyn Mutual Telecommunications Coop',
'BruNet, Jabatan Telekom Brunei Darussalam',
'Brutele SC',
'BSNL',
'BT Communications Bangladesh Ltd',
'BT Corporate',
'Bt Latam Brasil Ltda',
'BT Ltd',
'BTC Broadband Service',
'Buckeye Cablevision Inc',
'Bulgarian Telecommunications Company Plc.',
'Bulloch Telephone',
'Bullseye Telecom Inc',
'Burlington Telecom',
'Business Internet',
'Business Static Allocation',
'Business Static Service',
'Buttrey Food & Drug',
'BZQINT-DC',
'Cable & Wireless (Barbados) Limited',
'Cable & Wireless Americas Operations',
'Cable & Wireless Global',
'Cable & Wireless Jamaica Ltd',
'Cable & Wireless Ltd',
'Cable & Wireless Panama',
'Cable & Wireless Panama S.A.',
'Cable & Wireless Telecommunication Services GmbH',
'Cable and Wireless Jamaica',
'Cable Bahamas',
'Cable Bahamas Ltd',
'Cable Onda',
'Cable One',
'Cable One Inc',
'Cable Tica',
'Cable Tv Elpos Ltd.',
'Cablecom GmbH',
'Cablecom Networking Limited',
'Cablelink Internet Sservices Inc.',
'Cablemas Telecomunicaciones SA de CV',
'CablevisiÃ³n SA De CV',
'Cablevision S.A.',
'Cablevision Systems Corp.',
'CAIW Diensten B.V.',
'California Technology',
'Cameroon Telecommunications',
'Canaca-Com Inc',
'Canadian Department of Education',
'Canton Public Library',
'Capitol Construction',
'Caprock UK Limited ISP Infrastructure',
'Caprock UK Ltd',
'Caribou Coffee',
'Cass Cable TV',
'CAT TELECOM Data Comm. Dept, Intrenet Office',
'CAT Telecom public company Ltd',
'Caucasus Online LLC',
'Caucasus Online Ltd.',
'Cavalier Telephone',
'Cbeyond Communications',
'Cbeyond Communications LLC',
'CC Communications',
'Celcom Internet Service Provider',
'Cell C (Pty) Ltd',
'Cellular South Inc',
'Celtel Nigeria Limited t.a ZAIN',
'Central Wisconsin Communications LLC',
'Centrin Internet Service Provider',
'Century Link',
'CEZ ICT Services a.s.',
'Charlotte Customer Market Allocation',
'Charming Shoppes',
'Charter Communications',
'Chickasaw Nation',
'China Education and Research Network',
'China Mobile Communications Corporation',
'China Netcom Group Beijing Communication Company',
'CHINA RAILWAY TELECOMMUNICATIONS CENTER',
'China TieTong Telecommunications Corporation',
'China Unicom AnHui province network',
'China Unicom Beijing province network',
'China Unicom Fujian Province Network',
'China Unicom Guangdong province network',
'China Unicom Guangxi province network',
'China Unicom Hebei province network',
'China Unicom Heibei Province Network',
'China Unicom Henan province network',
'China Unicom IP network',
'China Unicom Jiangsu province network',
'China Unicom Liaoning province network',
'China Unicom Neimeng Province Network',
'China Unicom Shandong province network',
'China Unicom Shannxi Province Network',
'China Unicom Shanxi province network',
'China Unicom XinJiang province network',
'China Unicom Zhejiang Province Network',
'China United Telecommunications Corporation',
'CHINANET Anhui PROVINCE NETWORK',
'Chinanet Fujian Province Network',
'ChinaNet Guangdong Province Network',
'CHINANET hebei province network',
'CHINANET henan province network',
'Chinanet Hubei Province Network',
'Chinanet Hunan Province Network',
'Chinanet Jiangsu Province Network',
'Chinanet Jiangxi Province Network',
'CHINANET liaoning province network',
'Chinanet Shaanxi Province Network',
'CHINANET SHANDONG PROVINCE NETWORK',
'ChinaNet Shanghai Province Network',
'CHINANET SHANXI PROVINCE NETWORK',
'CHINANET Sichuan province network',
'Chinanet Tianjin Province Network',
'CHINANET Zhejiang province network',
'CHINANET-ZJ Hangzhou node network',
'CHINANET-ZJ Huzhou node network',
'CHINANET-ZJ Jiaxing node network',
'CHINANET-ZJ Jinhua node network',
'CHINANET-ZJ Ningbo node network',
'CHINANET-ZJ Shaoxing node network',
'CHINANET-ZJ Taizhou node network',
'CHINANET-ZJ Wenzhou node network',
'Choice One Communications',
'Choopa.com',
'Cia Proc. de Dados do Estado de S Paulo - Prodesp',
'CIK Telecom Inc',
'Cinergy Communications',
'Cinergy-metronet',
'City of Albany Water, Gas & Light Commission',
'City of Alexandria',
'City of Burlington',
'City of Lebanon',
'City of Marietta',
'City of North Kansas City',
'City of Roseville',
'City of Troy',
'City of Wyandotte',
'City West Cable & Telephone Corp.',
'CityOnline Services Ltd',
'CJSC Comstar-Regions',
'CJSC ER-Telecom Holding',
'CL-TEEMSR-LACNIC',
'Claranet Ltd',
'clear wireless llc',
'Clearwire LLC.',
'CloudRadium L.L.C',
'CMA Cablevision',
'CMC Telecom Infrastructure Company',
'CNCGROUP Beijing province network',
'CNISP',
'Cogeco Cable',
'Cogeco Cable Inc',
'Cogent Communications',
'COLOMBIA TELECOMUNICACIONES S.A. ESP',
'COLT Technology Services Group Limited',
'Columbia Electric Supply',
'Columbus Communications Jamaica Limited',
'Columbus Communications Trinidad Limited.',
'Columbus Networks Panama',
'Com Hem AB',
'Comcast - Houston',
'Comcast Business Communications',
'Comcast Business Communications LLC',
'Comcast Cable',
'Comcast Of Houston LLC',
'COMCEL GUATEMALA S.A.',
'Comcen',
'Commonwealth of PA - OA / Integrated Network Manag',
'Community Antenna Service',
'Comnet Communications',
'CompaÃ±Ã­a Dominicana de TelÃ©fonos, C. por A. - CODE',
'Complete Communication Systems Inc',
'COMPLETEL SAS France',
'Computer Centre Ngee Ann Polytechnic',
'Computer Sciences',
'Computer Sciences Corporation',
'Computer Sciences UK Ltd',
'ConnecTel Internet Service Provider',
'Conseils et Systemes Informatiques',
'Consolidated Communications',
'Consolidated Communications Inc',
'Consult Dynamics Inc',
'Content Service Provider Static Network',
'Continental Broadband Pennsylvania Inc',
'Conway Corporation',
'Coollink',
'Cooperative de cablodistribution de l\\'arriere-pays',
'corelink data centers llc',
'Cornerstone Telephone Company, LLC',
'CORPORACION NACIONAL DE TELECOMUNICACIONES - CNT E',
'CORPORACION NACIONAL DE TELECOMUNICACIONES CNT S.A',
'Corporate Leased Lines users',
'Cox Communications',
'CP Internet',
'Cricket Communications',
'Cricket Communications Inc',
'CS LoxInfo Public COmpany Limited',
'CTBC',
'CTCCommunications',
'Cumberland Technologies International',
'Customer Market Allocation',
'Customer Name',
'Customer P2P interface addresses in NL',
'Cutting Edge Communications',
'Cweb.com Inc',
'cwie llc',
'CyberGate Web Solutions',
'Cyberia',
'Cyberlink AG',
'Cybernet 1 Inc',
'Cybernet Communications',
'Cybersmart',
'Cynergycomm.net',
'Cyprus Telecommuncations Authority',
'Cyprus Telecommunications Authority',
'Dai IP su dung cho mang khach hang FTTH o HCMC',
'Daisy Communications Ltd',
'Dalton Utilities',
'Danica Computing',
'Darlington Borough Council',
'Data Matters',
'Data Networks',
'Data Networks Inc',
'Data Pro Business Online',
'Data Return',
'Datacom Caribe',
'Datavo',
'Dauphin Telecom',
'Davita',
'Days Inn',
'Delphi Internet Services Corporation',
'Delta Cable Communications',
'Deltacom',
'dery telecom inc',
'DetectNetwork.US',
'Detroit Public Schools',
'Deutsche Telekom AG',
'Dfw Internet Services Inc',
'Dialin fixed IP',
'Dialog Axiata Plc',
'Dialog Telecommunications',
'DiGi Telecommunications Sdn Bhd',
'Digial Nirvana',
'Digicel Jamaica',
'Digital Path',
'Digital Path Networks',
'Digital Telecommunications Philippines, Inc.',
'DigitelOne',
'DirectSpace Networks, LLC.',
'Dishnet Wireless Limited',
'Dishnet Wireless Ltd, India',
'Distributed Management Information Systems, Inc. (',
'Distributel Communications',
'Distributel Communications Ltd',
'DKI Jakarta',
'Dodo Australia',
'Dogan Iletisim Elektronik Servis Hizmetleri ve Yay',
'Domain Tools LLC',
'donet inc',
'Doylestown Communications',
'Dr Horton',
'DrukNet, Bhutan Telecom',
'DSL Extreme',
'D',
'E. Ritter Communications Inc',
'EarthISP Net',
'EarthLink Ltd. Communications&Internet Services',
'EarthLink Ltd. Communications&Internet Services-Or',
'Eastern Telecom Philippines Inc.',
'Eastern Telecoms Phils., Inc.',
'EastLink',
'Easynet',
'Easynet Limited',
'EasyTech',
'Ecatel LTD',
'ECL TELECOMMUNICATIONS LTD.',
'Eclipse Internet',
'Eclipse Networking',
'Edmonton Telephones Corporation',
'Eds-detroit Diesel',
'Education and Research Consortium of the Western C',
'Education Networks of America',
'Educational institution connected to SEKTORNET',
'EGIHosting',
'eGix',
'EgyNet',
'Egyptian Internet Services',
'Eircom',
'Elink Systems',
'Elion Enterprises Limited',
'Elisa Eesti AS',
'Elisa Oyj',
'Ellijay Telephone Company',
'Embarq Corporation',
'Embratel',
'EMC',
'Emerging Markets Communications Deutschland GmbH',
'Emirates Integrated Telecommunications Company PJS',
'Emirates Integrated Telecommunications Company Pjsc',
'Emirates Internet & Multimedia',
'Emirates Telecommunications Corporation',
'Energia Communications,Inc.',
'Entreprise des Postes et Telecommunications',
'EPB Telecom',
'EPM Telecomunicaciones S.A. E.S.P.',
'Epm Telecomunicaciones SA E.S.P.',
'Equant Inc',
'Equinix Asia Pacific',
'Equinix Asia Pacific PTE Ltd',
'Erie 1 Boces',
'ESA/ESTEC DATAGrid network',
'Escape Communications Corporation',
'eSpeed - Broadband DSL',
'ETB - Colombia',
'Ethio Telecom',
'Ethiopian Telecommunication corporation',
'Etihad Atheeb Telecom Company',
'ETISALAT',
'Etisalat Lanka (Private) Limited.',
'Ets Telephone Company',
'Ettihad Etisalat',
'europroNET Bosnia d.o.o.',
'Evergy S.A.',
'Excell Media Pvt Ltd',
'Execulink Telecom Inc',
'Exetel',
'Extreme Broadband Sdn. Bhd.',
'Fairbanks Redback DSL Pool',
'Fairbanks Scales',
'Fairpoint Communications',
'Fairpoint Communications Inc',
'Farmers Mutual Telephone Company',
'Farmers Telephone Coop Inc',
'Faros Trading LLC',
'Fast Telco Infra Structure IP space',
'Fast Telecommunications Company W.L.L.',
'Fasthosts Internet Limited - UK\\'s largest web host',
'Fastnet Corporation',
'Fasttrack Communications',
'Fastweb',
'Fiber Internet Center',
'Fibernetics Corporation',
'Fidelity Access Networks, LLC',
'Fidelity Communication International',
'First Media Pt Tbk',
'Fiserv',
'Fixed Broadband - Dynamic Pool',
'Florida Hospital',
'FLOW',
'FORTHnet SA',
'Four-U Technologies, LLC',
'Fox Valley Internet Inc',
'fpweb.net llc',
'France Telecom',
'Free SAS',
'Freedom To Surf plc',
'Frontier Communications',
'Frontier Communications of America Inc',
'Frontier Communications of the South LLC',
'FRY Reglet Corporation',
'FTTH GTD MANQUEHUE',
'Fulnett Limited',
'Fuse Internet Access',
'Fuzhou City, Fujian Provincial Network Of Unicom',
'Galaxy Backbone PLC',
'Gamtel Co',
'Gateway Telecoms Integrated Services Limited',
'GCOMM Pty Ltd',
'Geckotech LLC',
'Gemini Group',
'General Insulation',
'Genesis Net Limited',
'Geneva Online Inc',
'Georgia Public Web',
'Ghana Telecom',
'Ghossain & Truelock Enterprises Inc',
'Ghossain &Amp; Truelock Enterprises Inc',
'Giglinx Inc',
'GITN Sdn. Berhad',
'Giza-Zone-DSL',
'Globacom Ltd',
'Global Crossing Comunicaciones Ecuador S.A.',
'Global Internet Access',
'Global Web Intact t/a Screamer Telecoms',
'Globe Telecom',
'Globe Telecom/Innove Communication',
'Globe Telecoms',
'GLW Broadband',
'Go P.L.C.',
'Golden Lines Cable',
'Golden Telekom Tov',
'Golden West Telecommunications',
'Good Communications Co.,Ltd.',
'Government of South Africa',
'gradwell dot com Limited',
'Grafton Technologies',
'Grand County Internet Services',
'Grande Communications',
'Grande Communications Inc',
'Granite State Long Distance',
'Greenfield Communications',
'Greenlight',
'grid 4 communications inc',
'Grid4 Communications',
'Griffin Information Systems Limited',
'griffin information systems ltd',
'Griffith Company',
'Gsm Kazakhstan Ojsc kazakhtelecom Llp',
'GTEL MEXICALI',
'GTS Czech s.r.o.',
'GTS Slovakia, a.s.',
'Guadalupe Valley Telephone Coop Inc',
'Guadalupe Valley Telephone Cooperative',
'Gulfnet International Co.',
'GulfNet KSA',
'Guyana Telephone & Telegraph Co Ltd',
'Guyana Telephone & Telegraph Co.',
'GV/WFL BOCES Educational TechnologyService',
'Gvtc/gvcs-cable-cpe Dynamic Pool',
'GWI',
'ha-vel internet s.r.o.',
'Halton Borough Council',
'Hamamatsu Corporation',
'Hamilton Hydro / FibreWired',
'Hanaro Telecom Inc.',
'Hanaro Telecom, Inc.',
'Hargray Communications Group Inc',
'Harrisonville Telephone Company',
'Hastingwood Securities Ltd.',
'Hathway Cable and Datacom Pvt Ltd',
'Hathway IP Over Cable Internet Access Service',
'Haviland Telephone Company',
'Hawaiian Telcom Services Company Inc',
'Haynes Corporation',
'HEAnet Limited',
'Heartland-COG/North Central Ohio Computer Cooperat',
'Heico Aerospace Corporation',
'Hellas On Line S.A.',
'Hetzner Online AG',
'Hewlett-Packard Company',
'Hi3G Access AB',
'Hiawatha Broadband Communications Inc',
'Highland Network Ltd',
'Hilton Hotel Corporation',
'Holiday Inn Crowne Plaza',
'Home Telephone Company Inc',
'homecable-ap',
'Hong Kong Broadband Network Ltd',
'Hood Canal Communications',
'Horizon Telcom',
'Horry Telephone Coop Inc',
'Host Idaho',
'Hosting Services',
'Hosting Services Inc',
'Hughes Network Systems',
'Hughes Network Systems LLC',
'Huron Telecommunications Cooperative Limited',
'Hurricane Electric',
'Hutchison Global Communications',
'Hutchison Max Telecom Limited',
'Hydrosoft Internet',
'HyperSurf Internet Services',
'HYUNDAI COMMUNICATIONS & NETWORK',
'IBM India PVT Ltd',
'ICA Canada On-Line',
'ICONZ',
'ICPNET Cable',
'IDEA ISP Subscriber IP Pool',
'iiNet Limited',
'Imagine Telecommunications Ltd',
'Inap Zscaler',
'Inconet Data Management Sal',
'Ind. Company Cable Tv Inc',
'Indiana Fiber Network LLC',
'Indiana Fiber Network, LLC',
'Indonesia Online Access',
'Indosat Internet Service Provider',
'indosatm2 internet service provider',
'INDOSATnet Internet Service Provider',
'INDUSTRIE',
'Industry I-Net',
'Infinity Developments Limited',
'InfoChannel',
'Infocommunication Provider',
'Infocrossing',
'Infocrossing Inc',
'Infoline',
'Information Technology Company (ITC)',
'INFRA-AW',
'infrastructure in SPb',
'Inglis House',
'Inland Internet',
'InLink Communications Company',
'Inoc, LLC',
'Insight Communications Company Inc',
'Integra Telecom',
'Integrated Digital Services',
'Intelcom Group',
'Intelsat GlobalConnex Solutions',
'Interbel Telephone Cooperative',
'Interconnection with RAEI backbone',
'Internet America Inc',
'Internet Cable Plus C. A.',
'Internet Connect Inc',
'Internet Initiative Japan',
'Internet Service Provider',
'Internet Solutions',
'Internet technologies Namibia',
'Interneta pasaule SIA',
'INTERNEXA S.A. E.S.P',
'Internode',
'Interoute Deutschland GmbH',
'Interstate Telecommunications Cooperative',
'Intervolve',
'Intred S.p.A.',
'Invitel Tavkozlesi Zrt.',
'IO Data Centers',
'Ip Apple Computer Ro19',
'Ip House',
'IP Matrix, S.A. de C.V.',
'IPNetZone',
'IRECTONPC--ISP-NETBLK',
'Iseek Communications Pty Ltd',
'ISHAN\\'S IP POOL',
'ISN Communications',
'ISP',
'ISP Alliance',
'ISP Cote d\\'Ivoire',
'Ispn Inc',
'ITC Deltacom',
'IWeb Technologies',
'Jacobs Engineering',
'Jamii Telecommunications Limited',
'Japan Network Information Center',
'Jazz Telecom S.A.',
'Jb Wireless Inc',
'JCI Jones Chemicals Inc',
'Jervis B Webb Company Ltd',
'Jones Lang Lasalle',
'JSC Ukrtelecom',
'JTGlobal',
'Jump Network Services S.R.L.',
'Kabel Baden-Wuerttemberg GmbH & Co. KG',
'Kansas City Customer Market Allocation',
'Kaplan Telephone Company',
'Karaamin Shiraz ADSL ussrs Pool',
'Karib-cable-kelcom-international-slu',
'KC Web',
'Kcom',
'KDDI CORPORATION',
'Kenya Data Networks',
'Kenya Education Network',
'Kenyan Post & Telecommunications Company / Telkom',
'Keyways',
'Kinex Networking Solutions',
'King County Library System',
'KISTI',
'Klein Independent School District',
'Knology',
'Knology Inc',
'Korea Telecom',
'ksc commercial internet co. ltd',
'KSC Commercial Internet Co. Ltd.',
'Kuentos Communications',
'Kujtesa Internet Services',
'Kuwait Electronic and Messaging Services Company',
'Kuwait Telecommunication Company (Under Associatio',
'L-3 Communications',
'Lambeau Telecom',
'latisys-chicago llc',
'Laurel Highland Telephone Company',
'Leased Line customers',
'Leased Line- LAN Range',
'LeaseWeb B.V.',
'LEK Internet Services',
'Level 3 Communications',
'Lg Powercomm',
'LGfL Internet J',
'Libantelecom',
'Liberty Bell Telecom, LLC',
'Libyan Telecom and Technology',
'Ligtel Communications',
'Limestone Cable Vision',
'Ling Wang Internet Co',
'Link Egypt',
'LINKdotNET Telecom Limited',
'Linkem SPA',
'LinkLINE Communications',
'Linkoping',
'Linode',
'Linode, LLC',
'Local Infrastructure Expansion For Dsl (pppoe)',
'LocalNet',
'LocalTel Communications',
'Lodgenet',
'Logan_Telephone_Cooperative',
'Logix Communications',
'Logix Communications Lp',
'Logosoft OnLine ISP',
'Los Angeles Unified School District',
'Louisiana Board of Regents/Louisiana Optical Netwo',
'LUMOS Networks',
'lumos networks corporation',
'Lutheran Medical Center',
'M1 Connect Pte Ltd',
'M1 Ltd',
'Madison Telephone Company',
'Magyar Telekom plc.',
'Mahanagar Telephone Nigam Ltd',
'Maine Libraries/Dept. of Education',
'Manage5nines Ltd',
'Manitoba NetSet',
'Maritime Telecommunications Network',
'Massillon Cable Communications',
'Maxis Broadband Sdn Bhd',
'MCSNet',
'Mediacom Communications Corp',
'Mediacom Communications Corporation',
'Medical and Educational Data Network',
'Megalan Network Ltd.',
'Megapath',
'Melbourne Server Hosting Ltd',
'Melita Plc',
'Memphis Publishing Company',
'Meridian Business Centers',
'Meridian Telekoms Inc.',
'Meriplex Communications Ltd',
'Merit Network',
'Messagelabs Inc',
'MessageLabs Limited',
'MessageLabs Sydney',
'METRO-E PAMPANGA',
'MetroCast Cablevision',
'Metrocast Communications',
'Metronet (UK) Limited',
'MetroPCS Wireless',
'MetroPCS Wireless Inc',
'Michelin Manufacture Francaise, Telecommunication',
'Michwave Technologies',
'Microsoft Bingbot',
'Microsoft Corporation',
'Mid-mo Internet Solutions, LLC',
'Midcontinent Media Inc',
'Middle Michigan Network for Educational Telecommun',
'Mikrotec Internet Services',
'Milleni.com',
'Millington Catv Inc',
'Minet',
'MLS Projetos de Informatica',
'Mobile Interim Co -1- Sal',
'Mobile Services',
'Mobily Corp.',
'MOBISTAR',
'Mobitel',
'Monroe County Library System',
'Montage Beverly Hills',
'Montana Sky Networks',
'Moonbeam Equipment Communicati',
'Mora Telematika Indonesia Pt',
'Moretrench American Corporation',
'Morgan Building & Spa Manufacturing Corporation',
'Morrow-Meadows Corporation',
'Moscanet SAL',
'Moscow Institute of Physics and Technology',
'Motricity Inc',
'Mount Royal University',
'Mount Sinai School of Medicine',
'Mountain Cablevision',
'MPInet',
'Mpower Communications Corp.',
'MSN Wireless',
'MSN Wireless Inc',
'MTN Business Solutions (Pty) Ltd',
'MTN Network Solutions Pty Ltd',
'Mto Telecom Inc',
'MTS Allstream',
'Multacom Corporation',
'Multi-Links Telecommunications Limited',
'Mumbai Network Operations',
'MWEB Connect',
'myLoc managed IT AG',
'nacamar GmbH',
'Namincheon Brodcasting Co., Ltd.',
'nandani house 58 cha 1',
'Nanosolar',
'National Informatics Centre',
'National Oilwell Varco',
'National Telecom Corporation',
'Navega.com S.A.',
'NC Numericable S.A.',
'Nebula Oy',
'NEC BIGLOBE Ltd.',
'Nec Corporation',
'Neda Gostar Saba Data Transfer Company Private Joi',
'Neostrada Plus',
'Neotel Ltd',
'Neotelekom Zao',
'Nerim SAS',
'Net Access Corporation',
'Net1',
'Net2Net Corp.',
'NetAccess Systems',
'Netco Solutions',
'Netcom Africa Limited',
'Netelligent Hosting Services',
'Netelligent Hosting Services Inc',
'Neterra Ltd.',
'Netia SA',
'netINS',
'NetNet',
'netpage inc',
'Netriplex LLC',
'Netscalibur UK Ltd',
'NetVision',
'Netvision\\'s BroadBand service',
'NetWest Online',
'Network Billing Systems LLC',
'Network For Net Based Firewall Service',
'Network Operations Center',
'Network Solutions LLC',
'Network Tallahassee',
'Network Technology (AUST) P/L',
'Networktel Telephone',
'New Age Consulting Service',
'New Bridge Technologies',
'New Edge Network',
'New England School of Law',
'New Technologies Group N.V.',
'New Wave Communications',
'New West Consumer ADSL',
'Newroz Telecom Ltd.',
'Newsat Ltd',
'nextera communications llc',
'Nextgen Communications SRL',
'Nextgen Networks',
'Nianet A/S',
'Nildram',
'Nildram IP\\'s',
'Nile Online',
'Nobis Technology Group, LLC',
'Nokia Corporation',
'Norfolk County Council',
'North American Telecommunications Corporation',
'North Central Communications',
'Northern Telecom',
'Northern Valley Communications',
'Northland Cable Television Inc',
'Northwood University',
'North_Central_Telephone_Cooperative',
'NOVIS TELECOM, S.A.',
'Novus Entertainment',
'NSS S.A.',
'NTT Communications',
'Ntt Communications Corporation',
'Ntt Singapore Pte Ltd',
'NuLink',
'Nysernet/WebGenesis',
'Oarnet',
'OC3 Networks & Web Solutions, LLC',
'Oglecom',
'OJSC MegaFon',
'OJSC North-West Telecom',
'OJSC Rostelecom',
'OK-NET Co,. Ltd',
'Oklahoma State Regents for Higher Education',
'Oktopusnet Ooo',
'Olypen',
'Omani Qatari Telecommunications Company SAOC',
'Omantel',
'Omnicom Group Inc',
'ON S.A.',
'One Communications Corporation',
'OneXS International B.V.',
'Onitelecom - Infocomunicacoes, S.A.',
'ONO',
'Onyx Internet Ltd',
'Open Computer Network',
'Opera Mini Proxies',
'Opera Software Asa',
'Operbes, S.A. de C.V.',
'Optimum Online',
'Optimum WiFi',
'Orange DOMINICANA',
'Orange Home UK',
'Orange mobile',
'Orange Moldova Network',
'Orange Uganda Ltd',
'Orange WBC Broadband',
'Orange-jordan',
'Orca Communications',
'Orcon Corporation',
'Oregon Steel Mills - Rock Mtn',
'Orion Telekom Tim ADSL Pool',
'Orion Telekom Tim Doo',
'Oshean Inc',
'osnatel GmbH',
'OTEnet S.A.',
'OVH',
'Ovh Systems',
'Ovi Services',
'Oxford County Telephone & Telegraph Company Inc',
'Ozburn Hessey',
'Pacific Coast Container',
'Pacific Internet (Australia) Pty Ltd',
'Pacific Internet Limited',
'Pacific One Net Limited',
'Packerland Broadband',
'Pacnet',
'Pacnet Ltd',
'Pacnet Services (Japan) Corp.',
'Paetec',
'PAETEC Communications',
'Paetec Communications Inc',
'Partner Communications',
'Pathway Communications',
'PCCW Business Internet Access',
'Peg Tech',
'PenTeleData',
'Peoples Communications',
'PERN-Pakistan Education & Research Network is an',
'Persona Communications',
'Persona Communications Inc',
'Petersburg Internet Network Llc',
'Philippine Long Distance Telephone',
'philippine long distance telephone company',
'Phonoscope',
'Pioneer Elabs Ltd.',
'Pioneer Long Distance',
'Pioneer Wireless',
'PJSC Badr Rayan Jonoob',
'PLDT Sampaloc',
'Pleasant Valley Baptist Church',
'Plexus',
'plot 325 lane 22 new dohs',
'Plusnet PLC',
'PlusNet plc.',
'PlusNet Technologies Ltd',
'PO TURBHE',
'Pocketinet Communications',
'Point To Point Broadband',
'Point to Point Links',
'Pool',
'pool of addresses assigned to dsl lines with',
'Popp.Com Inc',
'Posta dhe telekomi i Kosoves',
'PoundHost Internet Services',
'PowerNet',
'Prima S.A.',
'Prime Signal',
'Primus Telecommunications Canada',
'Primus Telecommunications Canada Inc',
'Private Joint Stock Company datagroup',
'Professional Communications',
'Project Mutual Telephone Cooperative Association',
'Pronea AS',
'Provider Lir',
'Provider SoluÃ§Ãµes TecnolÃ³gicas Ltda',
'Przedsiebiorstwo Uslug Specjalistycznych Alamein Sp Zoo',
'PT Excelcomindo Pratama',
'PT INDOSAT MEGA MEDIA',
'PT Indosat Tbk.',
'PT Jembatan Citra Nusantara',
'PT QIANDRA INFORMATION TECHNOLOGY',
'PT Telkom Divisi Regional V Jawa Timur',
'PT Telkom Indonesia',
'PT UNINET Media Sakti',
'PT Varnion Technology Semesta',
'PT. Comtronics Systems',
'PT. Core Mediatech (DNET)',
'PT. Khasanah Timur Indonesia',
'PT. Media Antar Nusa',
'PT. TELEKOMUNIKASI INDONESIA',
'PT. Wireless Indonesia',
'PTCL',
'Public Service Data',
'Publix Super Markets',
'Puerto Rico Telephone Company',
'Pune Network Operations',
'Putian City A Broadband',
'Pyramid.Net',
'Q9 Networks',
'Q9 Networks Inc.',
'Qrixseodaemuncable, Inc.',
'Qtel',
'Quadro Communications Co-Operative',
'Quantum Communications LLC',
'QuickNet AB',
'Quicksilver Resources',
'Qwest Communications',
'R Cable y Telecomunicaciones Galicia S.A.',
'Radiant Communications 32482',
'RADIOGRAFICA COSTARRICENSE',
'Railtel Corporati0n of India Ltd',
'Rainbow Broadband',
'Rainy Day Software Corp.',
'Ramapo College of New Jersey',
'RASER',
'Ratt Internet Kapacitet i Sverige AB',
'RAYA Telecom',
'RCOM-Static-DIA',
'Readylink Internet Services Pvt. Limited',
'Red Cientifica Peruana',
'Redstone Managed Solutions Ltd',
'REDtone',
'Reliablehosting.com',
'Reliance Communications',
'Reliance Communications Ltd',
'RENATER',
'Reserve Long Distance Company',
'Reserved for I-Way / Claranet Customers in Clarane',
'Residence Inn',
'Respina Networks & Beyond PJSC',
'Rio Grande Communications',
'RIOMEDIA Frydek Mistek',
'RKWL AUTOM/DS 3 INTERNET',
'Rm Education PLC',
'Road Runner',
'Robert Half International',
'Rock Hill Telephone Company Inc',
'Rogers Cable',
'Rolled Alloys',
'Romtelecom Data Network',
'romtelecom s.a',
'Routcom',
'Routit-wap-e',
'Rural Telephone Service Company',
'Rural Telephone Service Company Inc',
'Russian Central Telegraph, Moscow',
'SAC Affaires VL',
'Saddle Mountain Wireless',
'Saero Network Service LTD',
'Safaricom',
'Sago Networks',
'SAIC Inc',
'SAINET Internet',
'Salsgiver Engineering',
'Salt Palace Convention Center',
'SAN JOSE',
'Sandefjord, Norway',
'Sarl ICOSNET',
'Saskatchewan Telecommunications Holding Corporation',
'SaskTel',
'Saturn R Internet Ooo',
'Saturn R Internet Ooov',
'Satyam Infoway (P) Ltd.',
'SaudiNet, Saudi Telecom Company',
'Savage Communications',
'SAVVIS Communications Corporation',
'ScanSafe',
'ScanSafe COP',
'ScanSafe FRA',
'ScanSafe LON',
'ScanSafe PAR',
'ScopeSky Communication and Internet Ltd.',
'Secure-24 Inc',
'Select System Infrastructure of Sumperk region',
'SelectNet, Inc.',
'Seokyung Cable Television Co.. Ltd.',
'SERCOM de Honduras',
'Server Suites LLC',
'SFR',
'Shared-Fortigate-Project',
'SHATEL Ent. DSL Network',
'Shenandoah Cable Television LLC',
'Shrewsbury Electric & Community Cable',
'Si.mobil D.d.',
'Sierra Advantage',
'Sify Limited',
'sigecom llc',
'Silo Wireless',
'Simbanet (T) Ltd',
'Singapore Telecommunications',
'SingNet Pte Ltd',
'Singtel',
'SingTel Internet Exchange',
'SiOL d.o.o. (Slovenia Online)',
'Sistema Shyam Teleservices Ltd',
'SITA-Societe Internationale de Telecommunications',
'SITA-Societe Internationale de Telecommunications Aeronautiques',
'Sky Broadband',
'SkyBest Communications',
'Skylogic S.p.A.',
'Skynet Belgium',
'Skyriver Communications',
'Skytel Networks Ireland Ltd',
'Skyvision Global Networks Ltd',
'Skyway West',
'Slovak Telecom, a. s.',
'Slovanet a.s.',
'Smart Broadband Incorporated',
'Smart Telecom',
'Smart Telecom Pt',
'SmarTone Mobile Communications Ltd',
'Smitcoms N.v.',
'Snap Net',
'So-net Service',
'SOFTNET d.o.o.',
'Software Technology Parks of India',
'Solcon Internetdiensten B.V.',
'Solutions Manufacturing',
'Somerville Board of Education',
'SONATEL Societe Nationale Des Telecommunications D',
'Sonic.net',
'Sophidea',
'Source Cable',
'South Carolina Telecommunications Group Holding LLC',
'South Slope Coop Telephone Company',
'South West Communications Group Ltd',
'Southern Billing Service',
'South_Central_Rural_Telephone_Cooperative',
'Spansion LLC',
'Speakeasy Inc',
'Specialty Rental Tools & Supply',
'Spectra Isp Networks PVT Ltd',
'Spectranet Ltd',
'Speed Buggy',
'SpeedCast Limited',
'SPiDiGO',
'Spring City Cable',
'Sprint',
'Sprint/United Information Service',
'Sri Lanka Telecom',
'SRT Communications Inc',
'SSP Yhtiot Oy',
'St Mary\\'s University',
'St. Louis Customer Market Allocation',
'St.Petersburg',
'Stage Networks Llc',
'Starhub Broadband',
'Starhub SWE Business',
'State Street Investment Trust',
'Static Business - Cinergy MetroNet',
'Static Business Pool - Cinergy MetroNet',
'STE ISP Network 1',
'Steadfast Networks',
'Stratos Global Communications',
'STUDIO 6',
'Subscriber Block 2 (Dedicated for all H3G ROI serv',
'Sudatel',
'Suddenlink Communications',
'sungard availability services lp',
'SUNRISE',
'Super Broadband Network',
'Super iMax',
'Super Radiator Coils',
'SUPERNET Limited',
'SureWest Broadband',
'Surfcontrol',
'Surfnet',
'Surfnet Communications',
'Susquehanna Data Services Inc',
'SWAZILAND PTC',
'Swift Networks Limited',
'Swisscom Fixnet AG',
'Symbio Networks',
'Syrian Telecommunications Establishment ( STE)',
'Systemmetrics Corporation',
'T-2 Access Network',
'T-on Telecom Co Ltd',
'T-Online ADSL clients',
'T-Systems ITS, Internet',
'Talk Internet Limited',
'TalkTalk',
'TANZANIA TELECOMMUNICATIONS CO. LTD',
'Tata Communications',
'Tata Teleservices Limited -GSM Division',
'Tata Teleservices Maharashtra Ltd',
'Tbaytel',
'TDC BB-ADSL users',
'TDC Oy Finland',
'TDC Sverige AB',
'TDS Computing Services',
'TDS Telecom',
'TDS Telecommunication Corporation',
'TE Data',
'Technocraft Industries Ltd',
'TECINFO',
'Tek Channel Consulting LLC',
'Teklinks Inc',
'TekSavvy Solutions',
'Teksavvy Solutions Inc',
'Teksystems Inc',
'Telco In A Box',
'Telconet S.A',
'TelCove, Inc.',
'Tele Danmark',
'tele-fonika cable americas corporation',
'Tele-Media Corporation',
'Tele2 Mobile',
'Tele2 SWIPnet',
'Tele2/SWIPnet',
'TELEBUCARAMANGA S.A. E.S.P.',
'Telecom Algeria',
'Telecom Argentina S.A.',
'Telecom Corporation Of New Zealand Ltd',
'Telecom Italia',
'Telecom Italia NET',
'Telecom Italia S.p.A.',
'Telecom Italia S.p.A. TIN EASY LITE',
'Telecom Italia SPA',
'Telecom Italia Wireline Services',
'Telecommunication Company of Iran',
'Telecommunication Services of Trinidad and Tobago',
'telecomplus',
'Telecomputing Norway AS',
'TELEFLEX AEROSPACE MANUFACTURING GROUP (Sermatech',
'Telefonica Data S.A.',
'Telefonica de Argentina',
'Telefonica del Peru',
'Telefonica del Peru S.A.',
'Telefonica Empresas',
'Telefonica O2 UK',
'Telefonos del Noroeste, S.A. de C.V.',
'Telekom Austria',
'Telekom Malaysia Berhad',
'Telekom Slovenije D.D.',
'TELEKOM SRBIJA a.d.',
'Telenor Norge AS',
'Telepacific Communications',
'Telepak Networks',
'Telesat Canada',
'Teleset Servis Ooo',
'Telesphere Networks',
'Telewest Ltd',
'Telgua',
'TeliaSonera Finland Oyj',
'Telkom SA Limited',
'Telkom SA Ltd',
'Telkomsel',
'Tellcom Iletisim Hizmetleri A.s.',
'Telmex Chile Internet S.A.',
'Telmex Colombia S.A.',
'Telnes Broadband.-hq',
'Telnet Worldwide',
'Telone',
'Telone PVT Ltd',
'Telstra Internet',
'TelstraClear Ltd',
'Telus Communications',
'Telus Communications Inc',
'Telus Quebec',
'TeraGo Networks',
'Terago Networks Inc',
'TeraGo PTP Networks',
'Texas Broadband',
'Texas Health Resources',
'The Bahamas Telecommunications Company',
'The Cloud Networks Ltd',
'The Internet Connection',
'The Jackson Laboratory',
'The Middleby Corporation',
'The Narragansett Electric Company',
'The Noor Group',
'The Reynolds Company',
'The Venetian Macao-Resort-Hotel',
'This field was added to fix syntax error',
'This space is statically assigned.',
'Three Indonesia',
'Tikona Digital Networks Pvt. Ltd.',
'Tikona Infinet Ltd',
'TIME dotCom Berhad',
'TIME Telecommunications Sdn Bhd',
'time warner cable inc',
'Timico Limited',
'Tire-1 Ip Transit Provider Of Bangladesh - 1',
'TM VADS DC Hosting',
'TMNET',
'TMnet Telekom Malaysia',
'Tng Worldwide',
'TOKAI Corporation',
'TOT Public Company Limited',
'Totelcom Communications Llc',
'Towerstream I',
'Toyota Motor Corporation',
'TPG Internet Pty Ltd.',
'Traci Network Solutions Inc',
'Trane Company',
'Transit Wireless Llc',
'Transmision de Datos TELNOR',
'Transtelco Inc',
'Transvision Reseau',
'TRE-FOR Bredbaand A/S',
'Triple T Internet PCL',
'True Broadband',
'True Broadband by True Online',
'True Internet',
'True internet Co., Ltd.',
'True Internet, Ltd.',
'TT&T, Internet Service Provider, Bangkok, Thailand',
'Tullahoma Utilities Board',
'Turk Telekom',
'Turk Telekom ADSL-200K 2',
'Turkcell Internet',
'Turner Broadcasting System',
'Tussa IKT AS',
'TVCABO Mocambique',
'Tvnetwork Inc.',
'TW Fresno Customers',
'TW Houston Customers',
'TW Ontario Customers',
'TW Phoenix Customers',
'tw telecom holdings',
'U\\'s Communications Corp.',
'U-NET Internet Ltd',
'UAB Baltnetos komunikacijos',
'Ubiquity Server Solutions Chicago',
'Ubiquity Server Solutions Dallas',
'Ubiquity Server Solutions New York',
'Ubiquity Server Solutions Seattle',
'UBTANET',
'UCC Corporate Customer',
'UCN',
'Ucweb Technologies',
'Ucwebhost Inc',
'UKOnline DSL customers',
'Ultimate Internet Access',
'unallocated',
'Unet B.V.',
'Uni2',
'UNICOM ZheJiang Province Network',
'Uninet',
'Uninet S.A. de C.V.',
'United Technologies',
'United Telephone Company',
'University of Nebraska Medical Center',
'Unwired',
'Unwired Broadband',
'Unwired Broadband Inc',
'Upc Austria GmbH',
'UPC Ceska Republica, s.r.o.',
'UPC Ireland',
'UPC Norge',
'UPC Polska Sp. z o.o.',
'UPC Romania BUCURESTI FIBER',
'UPC Romania SRL',
'Upper Peninsula Telephone Company',
'US Department of Energy',
'US Signal Company, L.L.C.',
'USAi.net',
'USDA',
'used for static broadband customers in hyderabad',
'Utility Telephone',
'UUNET Non-Portable Customer Assignment',
'Vanco GmbH',
'Varna, Bulgaria',
'Vault Networks Inc',
'VDC',
'Vectra S.A.',
'Vegasnap Llc',
'Velocity Network Inc',
'Ventelo AS',
'Veraciti',
'Veracity Networks LLC',
'Verat DOO',
'Verizon Business',
'Verizon Communications',
'Verizon FiOS',
'Verizon Internet Services',
'Vermont Telephone Company',
'Versatel Deutschland',
'Videotron Ltee',
'Viettel Corporation',
'VimpelCom',
'Vineyard Christian Fellowship',
'Virgin Media',
'Virtela Technology Services Inc',
'Visafone Communications Limited',
'Vision Communications',
'Visionary Communications',
'visionary services inc',
'vividwireless Pty Ltd',
'Vizada Networks AS',
'VMware Inc',
'Vocus Pty Ltd',
'Vodacom',
'Vodacom Ltd',
'Vodafone Australia Pty.',
'Vodafone Data',
'Vodafone Essar Spacetel Ltd',
'Vodafone India',
'Vodafone ISP',
'Vodafone Italia',
'Vodafone New Zealand Broadband',
'Voicecom Telecommunications Llc',
'Volia',
'Voonami Inc',
'Vox Datapro',
'voxclever ltd',
'VTR Banda Ancha S.A.',
'VTX Communications',
'VTX Services SA',
'Wananchi Online Limited',
'Wandering WIFI',
'Warid Telecom Uganda',
'Wash NOC First Network',
'Washington State Board for Community & Technical C',
'Wataniya Telecom',
'Wateen Telecom Ltd',
'Wave Broadband',
'Wave-Speed Networks, Inc.',
'Wavespeed',
'Waveworks Limited',
'Web Africa',
'Web Force Systems',
'WEBPASS',
'webroot inc',
'Webroot Services Ltd',
'Webroot Software',
'Websense Hosted Security Network',
'Wells Fargo & Company',
'west ip communications inc',
'West Wisconsin Telcom Cooperative',
'Wharf T&T Limited',
'WideOpenWest',
'WightFibre',
'Wildblue Communications',
'Wilhelm.Tel GmbH',
'WiLine Networks',
'Wilkes Communications',
'willamette valley internet',
'Wilogic Inc',
'Wind Hellas Telecommunications SA',
'WIND Telecom S.A.',
'WIND Telecomunicazioni S.p.A',
'Windstream Communications',
'Windstream Communications Inc',
'Windstream Nuvox Inc',
'Wins, LLC',
'Wireless Broadband Access Network',
'Wireless Broadband of Oklahoma',
'Wireless Data Service Provider Corporation',
'Wireless Solution India Pvt Ltd.',
'Wireless-HSD',
'Wireless/Satellite Division of Day',
'Wisper Isp Inc',
'Wood County Telephone Company Inc',
'Woodforest National Bank',
'Woolstock Mutual Telephone Association',
'World Access / Planet Internet',
'World Phone Internet Services Private Limited',
'WorldNet Telecommunications',
'Worldpath Internet Services',
'WorldWide Web Services',
'www.funknetz.at GmbH',
'Wwz Telekom Ag',
'Wyoming.com',
'XO Communications',
'Xplornet Communications',
'Xplornet Communications Inc',
'Xpressweb Internet Services',
'XS4ALL Internet BV',
'XTom WebHosting LLC',
'Yatanarpon Teleport',
'YHC Corporation',
'YMCA',
'YOU Telecom India Pvt Ltd',
'YTL Communications Sdn Bhd',
'Zain Data-Jordan',
'ZAMTEL',
'Zen Internet',
'Ziggo BV',
'Zimmerman Communications',
'Zito Media',
'ZON TV Cabo',
'Zscaler',
'Zscaler Inc',
'zscaler inc.',
'[ CBB - IP pool for customers ]'

) ";

sub updateTable
{  
  $q = $_[0];
  #print "$q\n"; 
  my $sth = $dbh->prepare($q);
  if (!$sth->execute) { print "Error" . $dbh->errstr . "\n"; exit(0); }
  $sth->finish;
  sleep(1);
}   

            
$i=0;
open(wf, ">>$outfile")  || die (print "Could not open $outfile\n");

  $isp =~ s/^\s+//;
  $isp =~ s/\s+$//;
  $isp =~ tr/[A-Z]/[a-z]/; 
  print "\n\n$isp\n\n";

 #VTOOL
 updateTable("update vtool11_05  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_06  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_07  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_08  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_09  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_10  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_11  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool11_12  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_01  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_02  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_03  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_04  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_05  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_06  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_07  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_08  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_09  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_10  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_11  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool12_12  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_01  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_02  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_03  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_04  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_05  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_06  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_07  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_08  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_09  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_10  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_12  set isp='Y' where  $ORGS   "); 
 updateTable("update vtool13_12  set isp='Y' where  $ORGS   "); 
 
 
 updateTable("update tnetlogORGPS13_01   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_02   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_03   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_04   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_05   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_06   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_07   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_08   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_09   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_10   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_11   set isp='Y' where  $ORGS   ");           
 updateTable("update tnetlogORGPS13_12   set isp='Y' where  $ORGS   ");           


   
  # CATNAV 
  updateTable("update catnav_ipn".$year."_01  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_02  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_03  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_04  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_05  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_06  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_07  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_08  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_09  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_10  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_11  set isp='Y' where  $ORGS2   ");
  updateTable("update catnav_ipn".$year."_12  set isp='Y' where  $ORGS2   ");
 
 
  # NEWS 
  updateTable("update newsORGSITED$year    set isp='Y' where  $ORGS   and  $ADDDATE and oid>''");
  updateTable("update newsORGD$year        set isp='Y' where  $ORGS    and  $ADDDATE and acct>0    and oid>''");
  
  # TNET  
  updateTable("update  tnetlogORGSITED".$year."_01   set isp='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_02   set isp='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_03   set isp='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_04   set isp='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_05   set isp='Y' where  $ORGS    and  oid>''");
  updateTable("update  tnetlogORGSITED".$year."_06   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_07   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_08   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_09   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_10   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_11   set isp='Y' where  $ORGS    and  oid>''"); 
  updateTable("update  tnetlogORGSITED".$year."_12   set isp='Y' where  $ORGS    and  oid>''"); 
   
                                               
  updateTable("update  tnetlogORGD".$year."_01  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_02  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_03  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_04  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_05  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_06  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");  
  updateTable("update  tnetlogORGD".$year."_07  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_08  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_09  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_10  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_11  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");
  updateTable("update  tnetlogORGD".$year."_12  set isp='Y' where  $ORGS    and   $ADDDATE and acct>0    and oid>''");    
 

  updateTable("update tnetlogORGCATD".$year."_01    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_02    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_03    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_04    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_05    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_06    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_07    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_08    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_09    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_10    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_11    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  updateTable("update tnetlogORGCATD".$year."_12    set isp='Y' where  $ORGS    and   $ADDDATE and heading>0 and oid>''");
  
  updateTable("update tnetlogORGN$year  set isp='Y' where  $ORGS    and   $ADDDATE ");
  updateTable("update tnetlogORGCATN$year  set isp='Y' where  $ORGS    and   $ADDDATE ");
  updateTable("delete from tnetlogADviewsServerOrg$year  where  $ORGS   ");
  
  # Reach local
   updateTable("delete from Campaign_IP  where  $ORGS2   and universal_id >''");

 # news image
  updateTable("delete from adcvmaster where  $ORGS   ");
 
 
 # Visitor Tool
  updateTable("update visitor_tool     set isp='Y' where  $ORGS     and oid>''");
  updateTable("update visitor_cat_tool set isp='Y' where  $ORGS     and oid>''");

 updateTable("delete from tnetlogADviewsServerOrg$year  where  $ORGS  ");
    
close(wf);
  

print "\nDone...\n";

 



