#!/bin/sh
# 
 
echo "Cat" 
 
echo "1406"
./reloadextra.pl 1406 
echo "------------------------------------" 

echo "1405"
./reloadextra.pl 1405 
echo "------------------------------------" 
  
echo "1404"
./reloadextra.pl 1404
echo "------------------------------------" 

echo "1403"
./reloadextra.pl 1403   
echo "------------------------------------" 

echo "1402"
./reloadextra.pl 1402   
echo "------------------------------------" 
 
echo "1401"
./reloadextra.pl 1401   
echo "------------------------------------" 



echo "1312"
./reloadextra.pl 1312
echo "------------------------------------" 

echo "1311"
./reloadextra.pl 1311
echo "------------------------------------" 

echo "1310"
./reloadextra.pl 1310
echo "------------------------------------" 

echo "1309"
./reloadextra.pl 1309
echo "------------------------------------" 

echo "1308"
./reloadextra.pl 1308
echo "------------------------------------" 

echo "1307"
./reloadextra.pl 1307
echo "------------------------------------" 

echo "1306"
./reloadextra.pl 1306
echo "------------------------------------" 

echo "1305"
./reloadextra.pl 1305
echo "------------------------------------" 

echo "1304"
./reloadextra.pl 1304
echo "------------------------------------" 

echo "1303"
./reloadextra.pl 1303
echo "------------------------------------" 

echo "1302"
./reloadextra.pl 1302
echo "------------------------------------" 

echo "1301"
./reloadextra.pl 1301
echo "------------------------------------" 

echo "Done..."
echo ""




