#!/bin/sh
# 
# loads old wizard
# run as  ./load-tnet-org YYMM 
  
if [ -z $1 ]
 then
 echo ""
 echo "Missing date: YYMM"
 echo ""
 exit;
fi
 
FDATE=$1

YY=${FDATE:0:2}
MM=${FDATE:2:2}
 
echo ""
echo "Date: ${FDATE}"
echo ""
  
echo "Site + Site with Cov" 
./load-org-drill-tnet-site-new.pl ${FDATE}
echo "------------------------------------" # 

echo "Adv" 
./load-org-drill-tnet-adv.pl ${FDATE} 
echo ""
echo "------------------------------------" #
 
echo "Cat Wiz" 
./load-org-drill-tnet-cat-wiz.pl ${FDATE} 
echo ""
echo "------------------------------------" #
 
echo "News" 
./load-org-drill-news.pl ${FDATE} 
echo ""
echo "------------------------------------"

echo "Product Search" 
./load-org-drill-PS-adv.pl ${FDATE} 
echo ""
echo "------------------------------------"

echo "Flat Catnav" 
./load-org-drill-tnet-flatcatnav.pl ${FDATE} 
./catnav-visitor-combo-extra  ${FDATE}    # delete is already in script
echo "" 
echo "------------------------------------"
 
echo "Extra" 
./load-org-extra.pl ${FDATE} 
echo ""
echo "------------------------------------"
 
echo "visitortool"
cd /usr/tnetlogs/wt/visitortool  
./vtool ${FDATE}
cd /usr/tnetlogs/wt
echo ""
echo "------------------------------------"
 
echo "gzip txt files";
nice gzip /usr/tnetlogs/wt/20${YY}/*${FDATE}.txt  

./wiztest ${FDATE}

echo ""
echo "dump/post some data"
./dumpwizard ${FDATE}
./dumpwizard2 ${FDATE}
./dumpwizard3 ${FDATE}

echo ${FDATE} | mail -s "Script wizload finished for ${FDATE}   " robertf@c.net


echo "Done..."
echo ""


