#!/bin/sh
# 
#
 
LABEL="Webtraxs Cross - LOR"

 
echo "Running load-webtraxs1.pl"
./load-webtraxs1-test.pl

echo "Running load-webtraxs2.pl"
./load-webtraxs2.pl

echo "wt-orgs-block-NEW.pl" 
./wt-orgs-block-NEW.pl

echo "wt-orgs-flag-NEW.pl" 
./wt-orgs-flag-NEW.pl


echo "update thomwebtraxs_cross set vid=md5(concat(acct,visitor,city,state,country))" | mysql -As thomas 

 

            
echo ${LABEL} | mail -s "Script load-webtraxs has finished" robertf@c.net
