#!/usr/bin/perl
#

$fdate   = $ARGV[0];
if($fdate eq "") {print "\n\nForgot to add date yymm\n\n"; exit;}
 

$fyear     = "20" . substr($fdate, 0, 2);
$yy        =  substr($fdate, 0, 2);
$mm        =  substr($fdate, 2, 2);
 
$table     = "formers_visitor";

 
 
use DBI;
$dbh      = DBI->connect("", "", "");


 
$ORGS =" 
'(previously known as CyberWay Pte Ltd)',
'013 Netvision Ltd',
'1001943 Ontario Ltd',
'123.Net',
'15b 53 55 corporate drive bridgewater nj 08807 usa',
'24Online Broadband Server',
'2k transportation llc',
'3BB Broadband',
'3plus logistics company',
'a cooper logistics inc',
'Aamra Networks Limited',
'abc logistics corporation',
'Abissnet sh.a.',
'able transportation',
'able transportation inc',
'Abovenet Communications Inc',
'abs freight transportation',
'abx logistics ltd',
'Acantho S.p.a',
'Access Broadband',
'Access Kenya Group Ltd',
'accurate logistics llc',
'accurate logistics ltd',
'ACD.net',
'Ace',
'ace logistics inc',
'ace transportation company inc',
'action logistics inc',
'Adams CATV',
'Adept Internet (Pty) Ltd CT',
'Administracion Nacional de Telecomunicaciones',
'ads logistics company llc',
'Advanced Colocation',
'advanced logistics group sa',
'Advanced Tel Inc',
'advanced transportation',
'advantage ground transportation corporation',
'Aero Group Inc',
'aero transportation products inc',
'aerostar global logistics inc',
'af net',
'AF NET Internet Services',
'afc logistics inc',
'Aflac',
'afs logistics llc',
'Aftab IT Limited',
'Agence Tunisienne Internet - ATI',
'agility project logistics pte ltd',
'AGT',
'agunsa logistics & distribution inc',
'aim logistics inc',
'Air Advantage LLC',
'air ground transportation',
'air logistics inc',
'Airband Communications Inc',
'Airespring',
'Airtel',
'Airtel Broadband',
'Airwave Networks Incorporated',
'ait worldwide logistics inc',
'AJAY Syscon PVT Ltd',
'Alands Datakommunikation Ab',
'Alaska Communications Systems Group',
'Albtelecom Sh.a.',
'alco transportation inc',
'Alenco Communications',
'Alestra S. De RL De CV',
'Algerie Telecom - FAWRI',
'Alice DSL',
'all girls tranportation & logistics inc',
'all logistics cargo inc',
'all points logistics inc',
'all points logistics llc',
'Allendale Telephone Company',
'Allhostshop.com',
'Allied Stone',
'ALLTEL Corporation',
'allure transportation',
'Alpheus Data Services, L.L.C.',
'alpinos logistics and distribution inc',
'alte transportation sl',
'Alternate Access Inc',
'alternative logistics inc',
'Amazon.com',
'American Internet Services, LLC.',
'american logistics company llc',
'american logistics group inc',
'american logistics international llc',
'American Packaging Corporation',
'American Red Cross',
'american shipping & logistics group inc',
'american transportation inc',
'american transportation technology distribution corporation',
'amerifleet transportation inc',
'Amerisuites',
'Amnet Broadband Pty Ltd',
'Amnet Cable San Pedro Sula',
'AMNET TEL y cia S en C de C.V.',
'AMP Corporate Telecommunications',
'ams logistics inc',
'amware logistics',
'amware logistics services inc',
'anaheim transportation network',
'Anchorage Redback DSL Dynamic Pool',
'Anchorage Redback DSL Pool',
'andrews logistics inc',
'ANEKS d.o.o.',
'Antietam Cable Television Inc',
'apc postal logistics llc',
'apex global logistics inc',
'apl logistics inc',
'Apollo Telecom (Pvt.) Ltd.',
'apple transportation inc',
'Arab Company For Internet & Communications Service',
'archilla transportation',
'Arcor AG',
'ard logistics llc',
'ardmore power logistics llc',
'Areti Internet LLC',
'aries global logistics',
'armada logistics inc',
'armstrong transportation inc',
'Armstrong Utilities Inc',
'Arqiva Communications Ltd',
'ars transportation company',
'art logistics inc',
'Art Matrix - Lightlink',
'ARtelecom',
'asbury transportation company',
'Ascus Telecom GmbH',
'asf logistics llc',
'Asianet is a cable ISP providing',
'ASK4 Ltd',
'Aston University',
'AT&T',
'AT&T AMS GIDC External Range',
'AT&T Enhanced Network Services',
'AT&T Global Network Services',
'AT&T Global Network Services Asia Pacific',
'AT&T IDC Redditch',
'AT&T Internet Services',
'AT&T Managed Firewall Network Based - Sydney',
'AT&T Managed Firewall Services NB2',
'AT&T MFS-NB 2.0-- Mesa, AZ - Trial',
'AT&T Mobility LLC',
'AT&T Services',
'AT&T U-verse',
'AT&T Worldnet IP Services',
'AT&T Worldnet Services',
'atco structures & logistics inc',
'Athens',
'Atlanta Customer Market Allocation',
'Atlantic Broadband',
'Atlantic Telephone Membership Corp.',
'atlantic transportation services inc',
'atlantis logistics inc',
'atlas sn logistics inc',
'Atos IT Solutions and Services GmbH',
'Atria Convergence Technologies Pvt. Ltd.',
'ats logistics inc',
'Att Bco Mcrc',
'Att Corp-intra-legacy T Legal',
'atthowe transportation company inc',
'ATX Telecommunications Services',
'Augere Wireless Broadband Bangladesh Limited',
'Axis Telekom Indonesia Pt',
'AXTEL',
'Axtel, S.A.B. de C. V.',
'Axtel, S.A.B. de C.V.',
'b & b transportation inc',
'b & c transportation inc',
'b & g transportation inc',
'b2b transportation services inc',
'B2X Online',
'Bahnhof Internet AB',
'Bahrain Telecommunication Company',
'Baja Broadband',
'Baldwin County Internet',
'baldwin telecom inc',
'bandstra transportation systems ltd',
'bandwidth communications ltd',
'Bandwidth.com',
'Banglalion WiMAX',
'barnhart transportation llc',
'Barracuda Networks Inc',
'Batelco ADSL service',
'Batelco Jordan',
'Bayan Telecommunications Incorporated',
'Bayanat Al-Oula For Network Services',
'BB BROADBAND CO., LTD.',
'bb logistics inc',
'Bce',
'BCL EAST,Infinity Building, Tower One, 1st Floor',
'BDCOM Online Limited',
'Be Un Limited',
'Beam Telecom Pvt Ltd',
'Beam Telecom Pvt Ltd, Hyderabad',
'bear transportation services lp',
'becker logistics',
'Beehive Telephone Company',
'Beeline',
'Beijing Teletron Telecom Engineering Co., Ltd.',
'Belgacom Skynet',
'Belize Telemedia Ltd',
'Bell Aliant Inc',
'Bell Aliant Regional Communications Inc',
'Bell Canada',
'BellSouth.net',
'Ben Lomand Rural Telephone Coop Inc',
'Bend Cable Communications Inc',
'Bend Cable Communications, LLC',
'best transportation llc',
'best transportation services inc',
'bestocean worldwide logistics inc',
'better environmentally sound transportation',
'Bezeq',
'Bezeq International',
'bgi worldwide logistics inc',
'BH Telecom d.d. Sarajevo',
'Bharat Sanchar Nigam Ltd',
'Bharti Airtel Limited',
'Bharti Airtel Ltd.',
'Bharti Broadband',
'Bharti Infotel Ltd',
'Bharti Telenet Ltd. Tamilnadu',
'billet transportation inc',
'Birch Telecom Inc',
'bison global logistics',
'BitWise Systems',
'BKK Fiber AS',
'Bkk Marked AS',
'Black Oak Computers',
'Blackfoot Telephone Coop Inc',
'blackhawk logistics llc',
'Blackney Hayes Architects',
'blakeman transportation inc',
'Blink Communications',
'Blue Coat Systems Inc',
'BluesMedia InfoTech',
'bonded transportation solutions inc',
'border pro logistics llc',
'Botswana Telecommunications Corporation',
'bouchard transportation company inc',
'bounce logistics inc',
'Bouygues Telecom',
'bowen logistics inc',
'boyd brothers transportation inc',
'bradco transportation inc',
'Brainstorm Internet',
'Brandenburg_Telephone_Company',
'BRAS Pools - Charminar',
'Bredbandsbolaget AB',
'brenny transportation inc',
'Bresnan Communications LLC',
'Bridge Band Communications/At',
'bridge logistics llc',
'bridgeport transportation & warehousing inc',
'Bright House Networks',
'BrightHouse Networks Bakersfield',
'BrightHouse Networks Indianapolis',
'Brightview ltd',
'Bristol Tennessee Essential Services',
'British Broadcasting Corporation',
'British Telecommunications',
'Broadband for Schools project',
'Broadband VI LLC',
'broadrange logistics llc',
'Broadstripe',
'Broadview Networks',
'Broadview Networks Inc',
'brokerage and logistics solutions inc',
'brokerage transportation',
'Brooklyn Mutual Telecommunications Coop',
'broussard logistics llc',
'BruNet, Jabatan Telekom Brunei Darussalam',
'Brutele SC',
'BSNL',
'BT Communications Bangladesh Ltd',
'BT Corporate',
'Bt Latam Brasil Ltda',
'BT Ltd',
'BTC Broadband Service',
'Buckeye Cablevision Inc',
'builders transportation company llc',
'Bulgarian Telecommunications Company Plc.',
'bulk transportation',
'Bulloch Telephone',
'bullocks express transportation inc',
'Bullseye Telecom Inc',
'Burlington Telecom',
'burris logistics',
'Business Internet',
'Business Static Allocation',
'Business Static Service',
'busy bee transportation services inc',
'Buttrey Food & Drug',
'BZQINT-DC',
'c mac transportation llc',
'Cable & Wireless (Barbados) Limited',
'Cable & Wireless Americas Operations',
'Cable & Wireless Global',
'Cable & Wireless Jamaica Ltd',
'Cable & Wireless Ltd',
'Cable & Wireless Panama',
'Cable & Wireless Panama S.A.',
'Cable & Wireless Telecommunication Services GmbH',
'Cable and Wireless Jamaica',
'Cable Bahamas',
'Cable Bahamas Ltd',
'Cable Onda',
'Cable One',
'Cable One Inc',
'Cable Tica',
'Cable Tv Elpos Ltd.',
'Cablecom GmbH',
'Cablecom Networking Limited',
'Cablelink Internet Sservices Inc.',
'Cablemas Telecomunicaciones SA de CV',
'Cablevisión SA De CV',
'Cablevision S.A.',
'Cablevision Systems Corp.',
'cabrera logistics inc',
'CAIW Diensten B.V.',
'California Technology',
'calyx transportation group inc',
'Cameroon Telecommunications',
'campbell transportation company inc',
'Canaca-Com Inc',
'Canadian Department of Education',
'Canton Public Library',
'capital transportation inc',
'capital transportation logistics inc',
'capital transportation logistics llc',
'capital transportation sols',
'Capitol Construction',
'capricorn logistics inc',
'Caprock UK Limited ISP Infrastructure',
'Caprock UK Ltd',
'caravan logistics inc',
'cardinal logistics',
'cardinal logistics management corporation',
'cardinal logistics management inc',
'cargo cargo logistics inc',
'cargo logistics inc',
'cargo logistics network company',
'cargo one logistics llc',
'Caribou Coffee',
'carlile transportation systems inc',
'carroll fulmer logistics corporation',
'carter logistics llc',
'cas transportation inc',
'Cass Cable TV',
'CAT TELECOM Data Comm. Dept, Intrenet Office',
'CAT Telecom public company Ltd',
'Caucasus Online LLC',
'Caucasus Online Ltd.',
'Cavalier Telephone',
'cavalier transportation services inc',
'cavalry logistics llc',
'Cbeyond Communications',
'Cbeyond Communications LLC',
'cbsltransportation services inc',
'CC Communications',
'cds logistics management inc',
'Celcom Internet Service Provider',
'Cell C (Pty) Ltd',
'Cellular South Inc',
'Celtel Nigeria Limited t.a ZAIN',
'central jersey transportation inc',
'central states logistics inc',
'Central Wisconsin Communications LLC',
'Centrin Internet Service Provider',
'Century Link',
'century transportation inc',
'certified freight logistics inc',
'ceva logistics',
'ceva logistics netherlands bv',
'ceva logistics us inc',
'CEZ ICT Services a.s.',
'champagne logistics lp',
'champion logistics group inc',
'champion transportation service',
'Charlotte Customer Market Allocation',
'Charming Shoppes',
'Charter Communications',
'chela logistics inc',
'chemical logistics inc',
'chenega logistics llc',
'Chickasaw Nation',
'China Education and Research Network',
'China Mobile Communications Corporation',
'China Netcom Group Beijing Communication Company',
'CHINA RAILWAY TELECOMMUNICATIONS CENTER',
'China TieTong Telecommunications Corporation',
'China Unicom AnHui province network',
'China Unicom Beijing province network',
'China Unicom Fujian Province Network',
'China Unicom Guangdong province network',
'China Unicom Guangxi province network',
'China Unicom Hebei province network',
'China Unicom Heibei Province Network',
'China Unicom Henan province network',
'China Unicom IP network',
'China Unicom Jiangsu province network',
'China Unicom Liaoning province network',
'China Unicom Neimeng Province Network',
'China Unicom Shandong province network',
'China Unicom Shannxi Province Network',
'China Unicom Shanxi province network',
'China Unicom XinJiang province network',
'China Unicom Zhejiang Province Network',
'China United Telecommunications Corporation',
'CHINANET Anhui PROVINCE NETWORK',
'Chinanet Fujian Province Network',
'ChinaNet Guangdong Province Network',
'CHINANET hebei province network',
'CHINANET henan province network',
'Chinanet Hubei Province Network',
'Chinanet Hunan Province Network',
'Chinanet Jiangsu Province Network',
'Chinanet Jiangxi Province Network',
'CHINANET liaoning province network',
'Chinanet Shaanxi Province Network',
'CHINANET SHANDONG PROVINCE NETWORK',
'ChinaNet Shanghai Province Network',
'CHINANET SHANXI PROVINCE NETWORK',
'CHINANET Sichuan province network',
'Chinanet Tianjin Province Network',
'CHINANET Zhejiang province network',
'CHINANET-ZJ Hangzhou node network',
'CHINANET-ZJ Huzhou node network',
'CHINANET-ZJ Jiaxing node network',
'CHINANET-ZJ Jinhua node network',
'CHINANET-ZJ Ningbo node network',
'CHINANET-ZJ Shaoxing node network',
'CHINANET-ZJ Taizhou node network',
'CHINANET-ZJ Wenzhou node network',
'choice logistics inc',
'Choice One Communications',
'Choopa.com',
'chtl logistics llc',
'chung lung freight transportation co ltd',
'churchill transportation inc',
'Cia Proc. de Dados do Estado de S Paulo - Prodesp',
'CIK Telecom Inc',
'Cinergy Communications',
'Cinergy-metronet',
'circle 8 logistics inc',
'circle city logistics ltd inc',
'cita logistics llc',
'city logistics & transport inc',
'City of Albany Water, Gas & Light Commission',
'City of Alexandria',
'City of Burlington',
'City of Lebanon',
'City of Marietta',
'City of North Kansas City',
'City of Roseville',
'City of Troy',
'City of Wyandotte',
'City West Cable & Telephone Corp.',
'CityOnline Services Ltd',
'CJSC Comstar-Regions',
'CJSC ER-Telecom Holding',
'CL-TEEMSR-LACNIC',
'Claranet Ltd',
'classic transportation',
'clear wireless llc',
'Clearwire LLC.',
'CloudRadium L.L.C',
'CMA Cablevision',
'CMC Telecom Infrastructure Company',
'CNCGROUP Beijing province network',
'CNISP',
'coastal international logistics llc',
'coastal logistics',
'coastal logistics inc',
'Cogeco Cable',
'Cogeco Cable Inc',
'Cogent Communications',
'COLOMBIA TELECOMUNICACIONES S.A. ESP',
'COLT Technology Services Group Limited',
'Columbia Electric Supply',
'Columbus Communications Jamaica Limited',
'Columbus Communications Trinidad Limited.',
'Columbus Networks Panama',
'Com Hem AB',
'Comcast - Houston',
'Comcast Business Communications',
'Comcast Business Communications LLC',
'Comcast Cable',
'Comcast Of Houston LLC',
'COMCEL GUATEMALA S.A.',
'Comcen',
'command transportation llc',
'commodity logistics',
'Commonwealth of PA - OA / Integrated Network Manag',
'Community Antenna Service',
'community transportation association of america',
'Comnet Communications',
'Compañía Dominicana de Teléfonos, C. por A. - CODE',
'Complete Communication Systems Inc',
'complete transportation',
'complete transportation llc',
'COMPLETEL SAS France',
'Computer Centre Ngee Ann Polytechnic',
'Computer Sciences',
'Computer Sciences Corporation',
'Computer Sciences UK Ltd',
'computer transportation services ltd',
'ConnecTel Internet Service Provider',
'Conseils et Systemes Informatiques',
'Consolidated Communications',
'Consolidated Communications Inc',
'Consult Dynamics Inc',
'Content Service Provider Static Network',
'Continental Broadband Pennsylvania Inc',
'continental logistics',
'convoy logistics providers ltd',
'Conway Corporation',
'Coollink',
'corelink data centers llc',
'Cornerstone Telephone Company, LLC',
'CORPORACION NACIONAL DE TELECOMUNICACIONES - CNT E',
'CORPORACION NACIONAL DE TELECOMUNICACIONES CNT S.A',
'Corporate Leased Lines users',
'corporate transportation group ltd',
'corsair logistics inc',
'cortrans logistics llc',
'Cox Communications',
'coyote logistics llc',
'CP Internet',
'creative logistics',
'creative transportation',
'crestline transportation inc',
'crh transportation inc',
'Cricket Communications',
'Cricket Communications Inc',
'crossroads usa logistics inc',
'crowley logistics inc',
'crystal creek logistics llc',
'CS LoxInfo Public COmpany Limited',
'CTBC',
'ctc logistics inc',
'CTCCommunications',
'cts global logistics inc',
'cubic transportation systems ltd',
'Cumberland Technologies International',
'Customer Market Allocation',
'Customer Name',
'Customer P2P interface addresses in NL',
'Cutting Edge Communications',
'cw logistics llc',
'Cweb.com Inc',
'cwie llc',
'CyberGate Web Solutions',
'Cyberia',
'Cyberlink AG',
'Cybernet 1 Inc',
'Cybernet Communications',
'Cybersmart',
'Cynergycomm.net',
'Cyprus Telecommuncations Authority',
'Cyprus Telecommunications Authority',
'Dai IP su dung cho mang khach hang FTTH o HCMC',
'Daisy Communications Ltd',
'Dalton Utilities',
'Danica Computing',
'Darlington Borough Council',
'Data Matters',
'Data Networks',
'Data Networks Inc',
'Data Pro Business Online',
'Data Return',
'data2logistics europe bv',
'data2logistics llc',
'Datacom Caribe',
'Datavo',
'Dauphin Telecom',
'Davita',
'dawson logistics inc',
'Days Inn',
'dean transportation inc',
'dedicated logistics inc',
'Delphi Internet Services Corporation',
'Delta Cable Communications',
'Deltacom',
'denbeste transportation inc',
'dery telecom inc',
'design transportation',
'DetectNetwork.US',
'Detroit Public Schools',
'detroit transportation corporation',
'Deutsche Telekom AG',
'development logistics group',
'Dfw Internet Services Inc',
'Dialin fixed IP',
'Dialog Axiata Plc',
'Dialog Telecommunications',
'DiGi Telecommunications Sdn Bhd',
'Digial Nirvana',
'Digicel Jamaica',
'Digital Path',
'Digital Path Networks',
'Digital Telecommunications Philippines, Inc.',
'DigitelOne',
'DirectSpace Networks, LLC.',
'Dishnet Wireless Limited',
'Dishnet Wireless Ltd, India',
'Distributed Management Information Systems, Inc. (',
'Distributel Communications',
'Distributel Communications Ltd',
'diversified logistics inc',
'diversified transportation services inc',
'DKI Jakarta',
'Dodo Australia',
'Dogan Iletisim Elektronik Servis Hizmetleri ve Yay',
'Domain Tools LLC',
'donet inc',
'dot-line transportation inc',
'double d transportation company',
'douglas transportation inc',
'Doylestown Communications',
'Dr Horton',
'drive logistics ltd',
'driveforce transportation of tulsa',
'driveforce transportation services llc',
'drt transportation llc',
'DrukNet, Bhutan Telecom',
'dsc logistics inc',
'DSL Extreme',
'dws logistics inc',
'D',
'dynamic transportation llc',
'dynamic worldwide logistics',
'e & b transportation',
'E. Ritter Communications Inc',
'eagle transportation services inc',
'earl paddock transportation inc',
'EarthISP Net',
'EarthLink Ltd. Communications&Internet Services',
'EarthLink Ltd. Communications&Internet Services-Or',
'eastern logistics inc',
'Eastern Telecom Philippines Inc.',
'Eastern Telecoms Phils., Inc.',
'EastLink',
'Easynet',
'Easynet Limited',
'EasyTech',
'ec transportation corporation',
'Ecatel LTD',
'echo global logistics inc',
'ECL TELECOMMUNICATIONS LTD.',
'Eclipse Internet',
'Eclipse Networking',
'ecu-logistics nv',
'Edmonton Telephones Corporation',
'Eds-detroit Diesel',
'Education and Research Consortium of the Western C',
'Education Networks of America',
'Educational institution connected to SEKTORNET',
'EGIHosting',
'eGix',
'EgyNet',
'Egyptian Internet Services',
'Eircom',
'ej logistics',
'Elink Systems',
'Elion Enterprises Limited',
'Elisa Eesti AS',
'Elisa Oyj',
'elite logistics inc',
'Ellijay Telephone Company',
'Embarq Corporation',
'Embratel',
'EMC',
'Emerging Markets Communications Deutschland GmbH',
'Emirates Integrated Telecommunications Company PJS',
'Emirates Integrated Telecommunications Company Pjsc',
'Emirates Internet & Multimedia',
'Emirates Telecommunications Corporation',
'encompass global logistics llc',
'Energia Communications,Inc.',
'england logistics',
'england logistics inc',
'eno transportation foundation inc',
'Entreprise des Postes et Telecommunications',
'ep logistics llc',
'EPB Telecom',
'EPM Telecomunicaciones S.A. E.S.P.',
'Epm Telecomunicaciones SA E.S.P.',
'Equant Inc',
'Equinix Asia Pacific',
'Equinix Asia Pacific PTE Ltd',
'equs logistics llc',
'Erie 1 Boces',
'ESA/ESTEC DATAGrid network',
'Escape Communications Corporation',
'eSpeed - Broadband DSL',
'ETB - Colombia',
'Ethio Telecom',
'Ethiopian Telecommunication corporation',
'Etihad Atheeb Telecom Company',
'ETISALAT',
'Etisalat Lanka (Private) Limited.',
'Ets Telephone Company',
'Ettihad Etisalat',
'europroNET Bosnia d.o.o.',
'evans transportation service',
'evergreen systems logistics inc',
'evergreen transportation llc',
'Evergy S.A.',
'excel transportation inc',
'Excell Media Pvt Ltd',
'Execulink Telecom Inc',
'executive transportation service inc',
'Exetel',
'expedited logistics and freight services ltd',
'express logistics llc',
'express transportation services',
'extra mile transportation llc',
'Extreme Broadband Sdn. Bhd.',
'extron logistics llc',
'facilities logistics inc',
'Fairbanks Redback DSL Pool',
'Fairbanks Scales',
'Fairpoint Communications',
'Fairpoint Communications Inc',
'fairway logistics inc',
'falls transportation service',
'Farmers Mutual Telephone Company',
'Farmers Telephone Coop Inc',
'Faros Trading LLC',
'fashion logistics inc',
'fast lane transportation inc',
'Fast Telco Infra Structure IP space',
'Fast Telecommunications Company W.L.L.',
'Fastnet Corporation',
'fastrans logistics inc',
'Fasttrack Communications',
'Fastweb',
'fcc logistics inc',
'federated logistics inc',
'fetch logistics inc',
'Fiber Internet Center',
'Fibernetics Corporation',
'Fidelity Access Networks, LLC',
'Fidelity Communication International',
'first class logistics',
'First Media Pt Tbk',
'Fiserv',
'five star global logistics ll',
'Fixed Broadband - Dynamic Pool',
'Florida Hospital',
'florida marine transportation',
'FLOW',
'focus logistics inc',
'fontana logistics',
'forrest transportation service inc',
'fort transportation & service company',
'FORTHnet SA',
'four star transportation company',
'Four-U Technologies, LLC',
'fourstar transportation',
'fowler transportation ltd',
'Fox Valley Internet Inc',
'fpweb.net llc',
'France Telecom',
'Free SAS',
'freedom logistics inc',
'Freedom To Surf plc',
'freight management logistics llc',
'Frontier Communications',
'Frontier Communications of America Inc',
'Frontier Communications of the South LLC',
'frontline logistics inc',
'FRY Reglet Corporation',
'fst logistics inc',
'FTTH GTD MANQUEHUE',
'Fulnett Limited',
'Fuse Internet Access',
'Fuzhou City, Fujian Provincial Network Of Unicom',
'g & d transportation inc',
'Galaxy Backbone PLC',
'Gamtel Co',
'Gateway Telecoms Integrated Services Limited',
'gb logistics inc',
'GCOMM Pty Ltd',
'Geckotech LLC',
'Gemini Group',
'gencom transportation inc',
'General Insulation',
'general logistics systems netherlands bv',
'Genesis Net Limited',
'genesis transportation inc',
'Geneva Online Inc',
'Georgia Public Web',
'getgo transportation company llc',
'Ghana Telecom',
'Ghossain & Truelock Enterprises Inc',
'Ghossain &Amp; Truelock Enterprises Inc',
'Giglinx Inc',
'gilgen logistics ag',
'GITN Sdn. Berhad',
'Giza-Zone-DSL',
'Globacom Ltd',
'global alliance logistics inc',
'Global Crossing Comunicaciones Ecuador S.A.',
'global expo logistics',
'global group logistics llc',
'Global Internet Access',
'global link logistics inc',
'global logistics & distributor',
'global logistics inc',
'global logistics solutions inc',
'global marine logistics pte ltd',
'global shipping & logistics',
'Global Web Intact t/a Screamer Telecoms',
'globe logistics inc',
'Globe Telecom',
'Globe Telecom/Innove Communication',
'Globe Telecoms',
'GLW Broadband',
'gmg transportation corporation',
'Go P.L.C.',
'Golden Lines Cable',
'Golden Telekom Tov',
'Golden West Telecommunications',
'Good Communications Co.,Ltd.',
'Government of South Africa',
'gps logistics llc',
'grace blue logistics',
'gradwell dot com Limited',
'Grafton Technologies',
'Grand County Internet Services',
'Grande Communications',
'Grande Communications Inc',
'grane transportation lines ltd',
'Granite State Long Distance',
'gray transportation inc',
'Greenfield Communications',
'Greenlight',
'greystone logistics inc',
'grid 4 communications inc',
'Grid4 Communications',
'griffin & company logistics',
'Griffin Information Systems Limited',
'griffin information systems ltd',
'Griffith Company',
'grimes logistics services inc',
'groome transportation inc',
'gsl logistics corporation',
'Gsm Kazakhstan Ojsc kazakhtelecom Llp',
'gt logistics llc',
'GTEL MEXICALI',
'GTS Czech s.r.o.',
'GTS Slovakia, a.s.',
'Guadalupe Valley Telephone Coop Inc',
'Guadalupe Valley Telephone Cooperative',
'Gulfnet International Co.',
'GulfNet KSA',
'gulick freight service logistics inc',
'Guyana Telephone & Telegraph Co Ltd',
'Guyana Telephone & Telegraph Co.',
'GV/WFL BOCES Educational TechnologyService',
'Gvtc/gvcs-cable-cpe Dynamic Pool',
'GWI',
'h & m international transportation inc',
'ha logistics inc',
'ha-vel internet s.r.o.',
'Halton Borough Council',
'Hamamatsu Corporation',
'Hamilton Hydro / FibreWired',
'hampton roads transportation inc',
'Hanaro Telecom Inc.',
'Hanaro Telecom, Inc.',
'hanzo logistics inc',
'Hargray Communications Group Inc',
'Harrisonville Telephone Company',
'hartley transportation llc',
'hartt transportation systems',
'Hastingwood Securities Ltd.',
'Hathway Cable and Datacom Pvt Ltd',
'Hathway IP Over Cable Internet Access Service',
'havi logistics is gmbh',
'Haviland Telephone Company',
'Hawaiian Telcom Services Company Inc',
'haymarket transportation inc',
'Haynes Corporation',
'haynes transportation company',
'HEAnet Limited',
'Heartland-COG/North Central Ohio Computer Cooperat',
'hecny transportation inc',
'Heico Aerospace Corporation',
'helix logistics llc',
'Hellas On Line S.A.',
'hellmann worldwide logistics gmbh',
'hellmann worldwide logistics inc',
'hellmann worldwide logistics ltd',
'hellmann worldwide logistics sa',
'heniff transportation systems llc',
'henry county transportation',
'Hetzner Online AG',
'Hewlett-Packard Company',
'Hi3G Access AB',
'Hiawatha Broadband Communications Inc',
'Highland Network Ltd',
'highland transportation inc',
'hill brothers intermodal logistics inc',
'hill brothers transportation inc',
'Hilton Hotel Corporation',
'hodges transportation inc',
'hoekstra transportation inc',
'hoffman transportation',
'Holiday Inn Crowne Plaza',
'hollingsworth logistics management llc',
'holt logistics corporation',
'home delivery logistics inc',
'Home Telephone Company Inc',
'homecable-ap',
'Hong Kong Broadband Network Ltd',
'Hood Canal Communications',
'horizon north logistics inc',
'Horizon Telcom',
'Horry Telephone Coop Inc',
'Host Idaho',
'Hosting Services',
'Hosting Services Inc',
'hotfoot logistics llc',
'Hughes Network Systems',
'Hughes Network Systems LLC',
'Huron Telecommunications Cooperative Limited',
'Hurricane Electric',
'Hutchison Global Communications',
'Hutchison Max Telecom Limited',
'hybrid building logistics inc',
'hyder transportation llc',
'hydra transportation of louisville inc',
'Hydrosoft Internet',
'hyperlogistics group inc',
'HyperSurf Internet Services',
'HYUNDAI COMMUNICATIONS & NETWORK',
'IBM India PVT Ltd',
'ICA Canada On-Line',
'icat logistics inc',
'ICONZ',
'ICPNET Cable',
'IDEA ISP Subscriber IP Pool',
'iiNet Limited',
'illini logistics',
'Imagine Telecommunications Ltd',
'in-line transportation inc',
'Inap Zscaler',
'Inconet Data Management Sal',
'Ind. Company Cable Tv Inc',
'Indiana Fiber Network LLC',
'Indiana Fiber Network, LLC',
'Indonesia Online Access',
'Indosat Internet Service Provider',
'indosatm2 internet service provider',
'INDOSATnet Internet Service Provider',
'industrial transportation inc',
'INDUSTRIE',
'Industry I-Net',
'Infinity Developments Limited',
'infinity logistics inc',
'InfoChannel',
'Infocommunication Provider',
'Infocrossing',
'Infocrossing Inc',
'Infoline',
'Information Technology Company (ITC)',
'INFRA-AW',
'infrastructure in SPb',
'Inglis House',
'Inland Internet',
'inline transportation llc',
'InLink Communications Company',
'innovative logistics inc',
'Inoc, LLC',
'Insight Communications Company Inc',
'integra logistics',
'Integra Telecom',
'Integrated Digital Services',
'integrated logistics solu',
'integrated transportation solution',
'integration logistics llc',
'integrity logistics inc',
'Intelcom Group',
'Intelsat GlobalConnex Solutions',
'inter-logistics llc',
'Interbel Telephone Cooperative',
'interchez logistics systems inc',
'Interconnection with RAEI backbone',
'international logistics management inc',
'international marine transportation ltd',
'international procurement and logistics ltd',
'international transportation service inc',
'Internet America Inc',
'Internet Cable Plus C. A.',
'Internet Connect Inc',
'Internet Initiative Japan',
'Internet Service Provider',
'Internet Solutions',
'Internet technologies Namibia',
'Interneta pasaule SIA',
'INTERNEXA S.A. E.S.P',
'Internode',
'Interoute Deutschland GmbH',
'interport logistics llc',
'interstar transportation services inc',
'interstate logistics inc',
'Interstate Telecommunications Cooperative',
'interturbine logistics solutions gmbh',
'Intervolve',
'Intred S.p.A.',
'Invitel Tavkozlesi Zrt.',
'IO Data Centers',
'ioplus logistics llc',
'Ip Apple Computer Ro19',
'Ip House',
'IP Matrix, S.A. de C.V.',
'IPNetZone',
'IRECTONPC--ISP-NETBLK',
'Iseek Communications Pty Ltd',
'isg transportation inc',
'island transportation corporation',
'ISN Communications',
'ISP',
'ISP Alliance',
'Ispn Inc',
'ital logistics ltd',
'ITC Deltacom',
'itochu logistics corporation',
'iwd transportation llc',
'IWeb Technologies',
'j & l transportation inc',
'j.v. transportation consultants inc',
'Jacobs Engineering',
'Jamii Telecommunications Limited',
'Japan Network Information Center',
'Jazz Telecom S.A.',
'Jb Wireless Inc',
'JCI Jones Chemicals Inc',
'jd logistics inc',
'Jervis B Webb Company Ltd',
'jimmy cowart transportation services llc',
'jj son & logistics inc',
'jka logistics llc',
'Jones Lang Lasalle',
'jrc transportation inc',
'js logistics corporation',
'JSC Ukrtelecom',
'JTGlobal',
'Jump Network Services S.R.L.',
'justina dunn transportation services',
'jw logistics llc',
'k & k transportation inc',
'k line logistics inc',
'k line logistics ltd',
'Kabel Baden-Wuerttemberg GmbH & Co. KG',
'kace logistics llc',
'Kansas City Customer Market Allocation',
'Kaplan Telephone Company',
'Karaamin Shiraz ADSL ussrs Pool',
'Karib-cable-kelcom-international-slu',
'kayla logistics corporation',
'kc transportation inc',
'KC Web',
'kce logistics inc',
'Kcom',
'KDDI CORPORATION',
'kenco logistics',
'Kenya Data Networks',
'Kenya Education Network',
'Kenyan Post & Telecommunications Company / Telkom',
'keppel logistics pte ltd',
'keystone dedicated logistics company llc',
'Keyways',
'Kinex Networking Solutions',
'King County Library System',
'KISTI',
'kk integrated logistics inc',
'kl harring transportation llc',
'Klein Independent School District',
'knapp logistics automation inc',
'knichel logistics',
'Knology',
'Knology Inc',
'Korea Telecom',
'krystal logistics usa inc',
'ksc commercial internet co. ltd',
'KSC Commercial Internet Co. Ltd.',
'ktl transportation corporation',
'kuecker logistics group inc',
'kuehne nagel logistics bv',
'Kuentos Communications',
'Kujtesa Internet Services',
'Kuwait Electronic and Messaging Services Company',
'Kuwait Telecommunication Company (Under Associatio',
'L-3 Communications',
'l.w. miller transportation inc',
'lacny logistics inc',
'lady logistics corporation',
'lakeside logistics inc',
'lakeside transportation company',
'Lambeau Telecom',
'langham logistics inc',
'lantrax logistics ltd',
'latek logistics usa inc',
'latisys-chicago llc',
'Laurel Highland Telephone Company',
'lawrence transportation',
'leading edge logistics llc',
'Leased Line customers',
'Leased Line- LAN Range',
'LeaseWeb B.V.',
'legacy transportation services inc',
'LEK Internet Services',
'lemmen transportation company',
'lesaint logistics llc',
'Level 3 Communications',
'lewis transportation group llc',
'lexington logistics llc',
'Lg Powercomm',
'LGfL Internet J',
'Libantelecom',
'Liberty Bell Telecom, LLC',
'liberty transportation inc',
'Libyan Telecom and Technology',
'lien transportation company',
'life science logistics llc',
'lightning logistics llc',
'Ligtel Communications',
'Limestone Cable Vision',
'linc logistics company',
'linehaul logistics inc',
'Ling Wang Internet Co',
'Link Egypt',
'LINKdotNET Telecom Limited',
'Linkem SPA',
'LinkLINE Communications',
'Linkoping',
'Linode',
'Linode, LLC',
'lionheart project logistics inc',
'lmd integrated logistics services inc',
'load delivered logistics llc',
'Local Infrastructure Expansion For Dsl (pppoe)',
'LocalNet',
'LocalTel Communications',
'lodestar logistics corporation',
'Lodgenet',
'Logan_Telephone_Cooperative',
'logistics insight corporation',
'logistics international inc',
'logistics international llc',
'logistics management',
'logistics management information',
'logistics management institute',
'logistics management resources inc',
'logistics management solutions inc',
'logistics plus inc',
'logistics worldwide usa inc',
'Logix Communications',
'Logix Communications Lp',
'Logosoft OnLine ISP',
'lone star transportation llc',
'longistics transportation inc',
'Los Angeles Unified School District',
'Louisiana Board of Regents/Louisiana Optical Netwo',
'lp transportation inc',
'lta logistics inc',
'lth logistics',
'lth logistics pte ltd',
'luckey logistics llc',
'LUMOS Networks',
'lumos networks corporation',
'Lutheran Medical Center',
'lynden international logistics company',
'm & w transportation company inc',
'M1 Connect Pte Ltd',
'M1 Ltd',
'Madison Telephone Company',
'maersk logistics usa inc',
'Magyar Telekom plc.',
'Mahanagar Telephone Nigam Ltd',
'Maine Libraries/Dept. of Education',
'malark logistics inc',
'mallory alexander international logistics llc',
'mamo transportation inc',
'Manage5nines Ltd',
'Manitoba NetSet',
'marine transport logistics',
'marino transportation services',
'Maritime Telecommunications Network',
'marquette transportation company llc',
'marquis transportation llc',
'Massillon Cable Communications',
'material technology & logistics inc',
'materials transportation company',
'maxim transportation services inc',
'Maxis Broadband Sdn Bhd',
'mbm logistics inc',
'mcallister towing & transportation company inc',
'mch logistics llc',
'MCSNet',
'md logistics inc',
'Mediacom Communications Corp',
'Mediacom Communications Corporation',
'Medical and Educational Data Network',
'medical transportation management inc',
'Megalan Network Ltd.',
'Megapath',
'Melbourne Server Hosting Ltd',
'Melita Plc',
'Memphis Publishing Company',
'menlo logistics inc',
'mercury transportation inc',
'Meridian Business Centers',
'Meridian Telekoms Inc.',
'Meriplex Communications Ltd',
'Merit Network',
'Messagelabs Inc',
'MessageLabs Limited',
'MessageLabs Sydney',
'metro transportation inc',
'METRO-E PAMPANGA',
'MetroCast Cablevision',
'Metrocast Communications',
'Metronet (UK) Limited',
'MetroPCS Wireless',
'MetroPCS Wireless Inc',
'metropolitan transportation authority',
'metropolitan transportation inc',
'mexpress transportation inc',
'mgn logistics inc',
'miami warehouse logistics inc',
'Michelin Manufacture Francaise, Telecommunication',
'Michwave Technologies',
'Microsoft Bingbot',
'Microsoft Corporation',
'mid america freight logistics llc',
'mid-arctic transportation company ltd',
'Mid-mo Internet Solutions, LLC',
'Midcontinent Media Inc',
'Middle Michigan Network for Educational Telecommun',
'midwest specialized transportation inc',
'Mikrotec Internet Services',
'Milleni.com',
'Millington Catv Inc',
'milogistics llc',
'Minet',
'miq logistics llc',
'mitsubishi logistics corporation',
'MLS Projetos de Informatica',
'Mobile Interim Co -1- Sal',
'Mobile Services',
'Mobily Corp.',
'MOBISTAR',
'Mobitel',
'moe-mentum transportation inc',
'mohawk global logistics',
'Monroe County Library System',
'monroe transportation ltd',
'Montage Beverly Hills',
'Montana Sky Networks',
'montgomery transportation brokers inc',
'Moonbeam Equipment Communicati',
'moose logistics inc',
'Mora Telematika Indonesia Pt',
'moran transportation company',
'moran transportation corporation',
'Moretrench American Corporation',
'Morgan Building & Spa Manufacturing Corporation',
'Morrow-Meadows Corporation',
'Moscanet SAL',
'Moscow Institute of Physics and Technology',
'Motricity Inc',
'moulton logistics management',
'Mount Royal University',
'Mount Sinai School of Medicine',
'Mountain Cablevision',
'MPInet',
'Mpower Communications Corp.',
'MSN Wireless',
'MSN Wireless Inc',
'mtc logistics inc',
'MTN Business Solutions (Pty) Ltd',
'MTN Network Solutions Pty Ltd',
'Mto Telecom Inc',
'MTS Allstream',
'Multacom Corporation',
'multi group logistics inc',
'Multi-Links Telecommunications Limited',
'multi-mode logistics llc',
'Mumbai Network Operations',
'mv transportation',
'mvp logistics llc',
'mw logistics llc',
'MWEB Connect',
'myLoc managed IT AG',
'mystic logistics inc',
'n and d transportation company inc',
'n.c. logistics inc',
'naca logistics inc',
'nacamar GmbH',
'naegeli transportation inc',
'Namincheon Brodcasting Co., Ltd.',
'nandani house 58 cha 1',
'Nanosolar',
'napa transportation inc',
'National Informatics Centre',
'National Oilwell Varco',
'National Telecom Corporation',
'national transportation safety board',
'Navega.com S.A.',
'NC Numericable S.A.',
'Nebula Oy',
'NEC BIGLOBE Ltd.',
'Nec Corporation',
'nec logistics america inc',
'Neda Gostar Saba Data Transfer Company Private Joi',
'neighborhood logistics company inc',
'Neostrada Plus',
'Neotel Ltd',
'Neotelekom Zao',
'Nerim SAS',
'Net Access Corporation',
'Net1',
'Net2Net Corp.',
'NetAccess Systems',
'Netco Solutions',
'Netcom Africa Limited',
'Netelligent Hosting Services',
'Netelligent Hosting Services Inc',
'Neterra Ltd.',
'Netia SA',
'netINS',
'NetNet',
'netpage inc',
'Netriplex LLC',
'Netscalibur UK Ltd',
'NetVision',
'NetWest Online',
'Network Billing Systems LLC',
'Network For Net Based Firewall Service',
'network global logistics llc',
'Network Operations Center',
'Network Solutions LLC',
'Network Tallahassee',
'Network Technology (AUST) P/L',
'Networktel Telephone',
'New Age Consulting Service',
'new age transportation distribution and warehousing inc',
'new age transportation inc',
'New Bridge Technologies',
'new century transportation inc',
'New Edge Network',
'New England School of Law',
'New Technologies Group N.V.',
'New Wave Communications',
'New West Consumer ADSL',
'Newroz Telecom Ltd.',
'Newsat Ltd',
'nextera communications llc',
'Nextgen Communications SRL',
'Nextgen Networks',
'Nianet A/S',
'Nildram',
'Nile Online',
'nin logistics llc',
'Nobis Technology Group, LLC',
'noble supply & logistics',
'Nokia Corporation',
'norbert dentressangle logistics ltd',
'nordic logistics and warehousing llc',
'Norfolk County Council',
'North American Telecommunications Corporation',
'north arm transportation ltd',
'North Central Communications',
'north park transportation company inc',
'northern logistics inc',
'Northern Telecom',
'northern transportation company ltd',
'Northern Valley Communications',
'Northland Cable Television Inc',
'Northwood University',
'North_Central_Telephone_Cooperative',
'nova natie logistics nv',
'NOVIS TELECOM, S.A.',
'Novus Entertainment',
'nrs logistics',
'NSS S.A.',
'NTT Communications',
'Ntt Communications Corporation',
'Ntt Singapore Pte Ltd',
'nuclear logistics inc',
'NuLink',
'nuna logistics ltd',
'nyborg integrated logistics inc',
'Nysernet/WebGenesis',
'Oarnet',
'OC3 Networks & Web Solutions, LLC',
'odw logistics inc',
'Oglecom',
'OJSC MegaFon',
'OJSC North-West Telecom',
'OJSC Rostelecom',
'OK-NET Co,. Ltd',
'Oklahoma State Regents for Higher Education',
'Oktopusnet Ooo',
'Olypen',
'Omani Qatari Telecommunications Company SAOC',
'Omantel',
'omg logistics llc',
'omni logistics inc',
'Omnicom Group Inc',
'ON S.A.',
'One Communications Corporation',
'OneXS International B.V.',
'Onitelecom - Infocomunicacoes, S.A.',
'ONO',
'Onyx Internet Ltd',
'Open Computer Network',
'Opera Mini Proxies',
'Opera Software Asa',
'Operbes, S.A. de C.V.',
'Optimum Online',
'Optimum WiFi',
'Orange DOMINICANA',
'Orange Home UK',
'Orange mobile',
'Orange Moldova Network',
'Orange Uganda Ltd',
'Orange WBC Broadband',
'Orange-jordan',
'Orca Communications',
'Orcon Corporation',
'Oregon Steel Mills - Rock Mtn',
'Orion Telekom Tim ADSL Pool',
'Orion Telekom Tim Doo',
'orthman logistics company',
'Oshean Inc',
'osnatel GmbH',
'OTEnet S.A.',
'overdrive logistics inc',
'OVH',
'Ovh Systems',
'Ovi Services',
'Oxford County Telephone & Telegraph Company Inc',
'Ozburn Hessey',
'ozburn-hessey logistics llc',
'p & s transportation inc',
'p.a.m. transportation services inc',
'pacific air logistics inc',
'Pacific Coast Container',
'Pacific Internet (Australia) Pty Ltd',
'Pacific Internet Limited',
'pacific logistics corporation',
'Pacific One Net Limited',
'pacific rim transportation ltd',
'pacific transportation services inc',
'Packerland Broadband',
'Pacnet',
'Pacnet Ltd',
'Pacnet Services (Japan) Corp.',
'Paetec',
'PAETEC Communications',
'Paetec Communications Inc',
'pallet logistics inc',
'palmetto state transportation company inc',
'paramount transportation systems inc',
'park city transportation servi',
'park transportation inc',
'Partner Communications',
'pathfinder logistics inc',
'Pathway Communications',
'payment logistics llc',
'PCCW Business Internet Access',
'pds transportation',
'Peg Tech',
'pegasus transportation inc',
'penn transportation services inc',
'penske transportation holdings corporation',
'PenTeleData',
'Peoples Communications',
'performance logistics llc',
'perkins specialized transportation inc',
'PERN-Pakistan Education & Research Network is an',
'Persona Communications',
'Persona Communications Inc',
'Petersburg Internet Network Llc',
'petrologistics lp',
'pfs transportation inc',
'Philippine Long Distance Telephone',
'philippine long distance telephone company',
'phoenix logistics inc',
'phoenix transportation services llc',
'Phonoscope',
'Pioneer Elabs Ltd.',
'Pioneer Long Distance',
'Pioneer Wireless',
'PJSC Badr Rayan Jonoob',
'PLDT Sampaloc',
'Pleasant Valley Baptist Church',
'Plexus',
'plot 325 lane 22 new dohs',
'Plusnet PLC',
'PlusNet plc.',
'PlusNet Technologies Ltd',
'pm logistics & systems inc',
'pme logistics inc',
'PO TURBHE',
'Pocketinet Communications',
'Point To Point Broadband',
'Point to Point Links',
'polymer logistics inc',
'polymer logistics nv',
'Pool',
'pool of addresses assigned to dsl lines with',
'Popp.Com Inc',
'Posta dhe telekomi i Kosoves',
'PoundHost Internet Services',
'power one logistics',
'PowerNet',
'premier logistics inc',
'price busters transportation',
'price transportation inc',
'Prima S.A.',
'Prime Signal',
'Primus Telecommunications Canada',
'Primus Telecommunications Canada Inc',
'priority logistics inc',
'priority transportation group inc',
'Private Joint Stock Company datagroup',
'pro ag logistics llc',
'Professional Communications',
'progressive transportation services inc',
'Project Mutual Telephone Cooperative Association',
'prominent logistics inc',
'Pronea AS',
'propak logistics inc',
'prospect transportation inc',
'Provider Lir',
'Provider Soluções Tecnológicas Ltda',
'Przedsiebiorstwo Uslug Specjalistycznych Alamein Sp Zoo',
'PT Excelcomindo Pratama',
'PT INDOSAT MEGA MEDIA',
'PT Indosat Tbk.',
'PT Jembatan Citra Nusantara',
'PT QIANDRA INFORMATION TECHNOLOGY',
'PT Telkom Divisi Regional V Jawa Timur',
'PT Telkom Indonesia',
'PT UNINET Media Sakti',
'PT Varnion Technology Semesta',
'PT. Comtronics Systems',
'PT. Core Mediatech (DNET)',
'PT. Khasanah Timur Indonesia',
'PT. Media Antar Nusa',
'PT. TELEKOMUNIKASI INDONESIA',
'PT. Wireless Indonesia',
'PTCL',
'public logistics inc',
'Public Service Data',
'Publix Super Markets',
'Puerto Rico Telephone Company',
'Pune Network Operations',
'Putian City A Broadband',
'pyramid logistics services inc',
'pyramid transportation systems inc',
'Pyramid.Net',
'Q9 Networks',
'Q9 Networks Inc.',
'qhub logistics corporation',
'Qrixseodaemuncable, Inc.',
'Qtel',
'Quadro Communications Co-Operative',
'quality logistics inc',
'Quantum Communications LLC',
'queensland health server purchasing and logistics',
'QuickNet AB',
'Quicksilver Resources',
'quik x transportation inc',
'Qwest Communications',
'r & k logistics inc',
'r & m logistics corporation',
'r & m logistics inc',
'r & r transportation inc',
'R Cable y Telecomunicaciones Galicia S.A.',
'r.j.s. logistics inc',
'r2 logistics inc',
'Radiant Communications 32482',
'radiant logistics inc',
'RADIOGRAFICA COSTARRICENSE',
'Railtel Corporati0n of India Ltd',
'Rainbow Broadband',
'Rainy Day Software Corp.',
'Ramapo College of New Jersey',
'ramp logistics',
'RASER',
'Ratt Internet Kapacitet i Sverige AB',
'RAYA Telecom',
'RCOM-Static-DIA',
'rcs logistics inc',
're transportation inc',
'Readylink Internet Services Pvt. Limited',
'reckart logistics inc',
'Red Cientifica Peruana',
'redhawk transportation inc',
'redline logistics inc',
'Redstone Managed Solutions Ltd',
'REDtone',
'regency transportation inc',
'regional integrated logistics inc',
'regional transportation district',
'reinauer transportation companies llc',
'reliable transportation solutions llc',
'reliable transportation specialists inc',
'Reliablehosting.com',
'Reliance Communications',
'Reliance Communications Ltd',
'remote logistics inc',
'renaissance global logistics llc',
'RENATER',
'Reserve Long Distance Company',
'Reserved for I-Way / Claranet Customers in Clarane',
'Residence Inn',
'resource logistics inc',
'Respina Networks & Beyond PJSC',
'retail logistics llc',
'riegel transportation inc',
'riley transportation inc',
'Rio Grande Communications',
'RIOMEDIA Frydek Mistek',
'RKWL AUTOM/DS 3 INTERNET',
'rld transportation inc',
'rle logistics llc',
'Rm Education PLC',
'rm logistics',
'ro-mar transportation systems inc',
'Road Runner',
'roadco transportation services inc',
'roadtex transportation corporation',
'roane transportation services llc',
'roar logistics inc',
'robart transportation inc',
'Robert Half International',
'Rock Hill Telephone Company Inc',
'Rogers Cable',
'Rolled Alloys',
'romark logistics of texas inc',
'rome transportation inc',
'Romtelecom Data Network',
'romtelecom s.a',
'rose chauffeured transportation ltd',
'Routcom',
'Routit-wap-e',
'royal cargo combined logistics inc',
'rr donnelley logistics services worldwide inc',
'rsc transportation',
'ruan transportation management systems inc',
'Rural Telephone Service Company',
'Rural Telephone Service Company Inc',
'rush transportation inc',
'Russian Central Telegraph, Moscow',
'ryan transportation service inc',
'ryder crsa logistics',
'SAC Affaires VL',
'Saddle Mountain Wireless',
'Saero Network Service LTD',
'Safaricom',
'Sago Networks',
'SAIC Inc',
'SAINET Internet',
'sales transportation inc',
'Salsgiver Engineering',
'salson logistics inc',
'Salt Palace Convention Center',
'sammons transportation inc',
'samples transportation service',
'SAN JOSE',
'Sandefjord, Norway',
'sanyo logistics corporation',
'Sarl ICOSNET',
'Saskatchewan Telecommunications Holding Corporation',
'SaskTel',
'Saturn R Internet Ooo',
'Saturn R Internet Ooov',
'Satyam Infoway (P) Ltd.',
'SaudiNet, Saudi Telecom Company',
'sav logistics inc',
'Savage Communications',
'SAVVIS Communications Corporation',
'ScanSafe',
'ScanSafe COP',
'ScanSafe FRA',
'ScanSafe LON',
'ScanSafe PAR',
'scanwell logistics inc',
'scanwell logistics pvt ltd',
'schilli transportation services inc',
'schmidt transportation inc',
'schumacher cargo logistics inc',
'ScopeSky Communication and Internet Ltd.',
'scott logistics corporation',
'scr medical transportation inc',
'sdv logistics inc',
'seal transportation inc',
'sealaska global logistics llc',
'secure transportation and relocation international inc',
'secure transportation company inc',
'Secure-24 Inc',
'Select System Infrastructure of Sumperk region',
'select transportation inc',
'SelectNet, Inc.',
'sentinel transportation llc',
'Seokyung Cable Television Co.. Ltd.',
'SERCOM de Honduras',
'Server Suites LLC',
'service first logistics corporation',
'SFR',
'sh cogent logistics pte ltd',
'shanahan transportation systems inc',
'Shared-Fortigate-Project',
'SHATEL Ent. DSL Network',
'Shenandoah Cable Television LLC',
'shoreline transportation inc',
'Shrewsbury Electric & Community Cable',
'Si.mobil D.d.',
'Sierra Advantage',
'Sify Limited',
'sigecom llc',
'Silo Wireless',
'silverline transportation ltd',
'Simbanet (T) Ltd',
'simplified logistics llc',
'Singapore Telecommunications',
'SingNet Pte Ltd',
'Singtel',
'SingTel Internet Exchange',
'SiOL d.o.o. (Slovenia Online)',
'Sistema Shyam Teleservices Ltd',
'SITA-Societe Internationale de Telecommunications',
'SITA-Societe Internationale de Telecommunications Aeronautiques',
'Sky Broadband',
'SkyBest Communications',
'skye logistics llc',
'skyline transportation inc',
'Skylogic S.p.A.',
'Skynet Belgium',
'Skyriver Communications',
'Skytel Networks Ireland Ltd',
'Skyvision Global Networks Ltd',
'Skyway West',
'sl source logistics laredo llc',
'sloan transportation products inc',
'Slovak Telecom, a. s.',
'Slovanet a.s.',
'Smart Broadband Incorporated',
'Smart Telecom',
'Smart Telecom Pt',
'SmarTone Mobile Communications Ltd',
'Smitcoms N.v.',
'Snap Net',
'So-net Service',
'SOFTNET d.o.o.',
'Software Technology Parks of India',
'Solcon Internetdiensten B.V.',
'Solutions Manufacturing',
'Somerville Board of Education',
'SONATEL Societe Nationale Des Telecommunications D',
'Sonic.net',
'Sophidea',
'Source Cable',
'South Carolina Telecommunications Group Holding LLC',
'south coast logistics',
'south coast transportation & distribution inc',
'South Slope Coop Telephone Company',
'South West Communications Group Ltd',
'Southern Billing Service',
'southland logistics company inc',
'South_Central_Rural_Telephone_Cooperative',
'Spansion LLC',
'Speakeasy Inc',
'specialized transportation for outpatient services inc',
'Specialty Rental Tools & Supply',
'Spectra Isp Networks PVT Ltd',
'Spectranet Ltd',
'spectrum transportation services llc',
'Speed Buggy',
'SpeedCast Limited',
'speedmark air transportation pte ltd',
'SPiDiGO',
'spirit logistics llc',
'Spring City Cable',
'Sprint',
'Sprint/United Information Service',
'Sri Lanka Telecom',
'SRT Communications Inc',
'SSP Yhtiot Oy',
'St. Louis Customer Market Allocation',
'St.Petersburg',
'Stage Networks Llc',
'standard transportation services inc',
'Starhub Broadband',
'Starhub SWE Business',
'State Street Investment Trust',
'states logistics services inc',
'Static Business - Cinergy MetroNet',
'Static Business Pool - Cinergy MetroNet',
'STE ISP Network 1',
'Steadfast Networks',
'steelman transportation inc',
'sterling transportation service',
'stevens global logistics inc',
'stonearch logistics llc',
'stoneland global logistics inc',
'strategic logistics solutions inc',
'Stratos Global Communications',
'STUDIO 6',
'styer transportation company',
'styles logistics inc',
'Subscriber Block 2 (Dedicated for all H3G ROI serv',
'Sudatel',
'Suddenlink Communications',
'suffolk transportation service',
'summit logistics inc',
'sungard availability services lp',
'SUNRISE',
'sunset pacific transportation inc',
'sunset transportation inc',
'sunshine logistics inc',
'Super Broadband Network',
'Super iMax',
'Super Radiator Coils',
'superior logistics services inc',
'superior nationwide logistics ltd',
'SUPERNET Limited',
'SureWest Broadband',
'Surfcontrol',
'Surfnet',
'Surfnet Communications',
'Susquehanna Data Services Inc',
'SWAZILAND PTC',
'Swift Networks Limited',
'swift transportation',
'swift transportation company',
'Swisscom Fixnet AG',
'syfan logistics inc',
'Symbio Networks',
'Syrian Telecommunications Establishment ( STE)',
'system logistics corporation',
'Systemmetrics Corporation',
'T-2 Access Network',
'T-on Telecom Co Ltd',
'T-Online ADSL clients',
'T-Systems ITS, Internet',
't.a.g. logistics llc',
't.g.r. logistics inc',
'Talk Internet Limited',
'TalkTalk',
'talon logistics inc',
'tandem logistics inc',
'TANZANIA TELECOMMUNICATIONS CO. LTD',
'Tata Communications',
'Tata Teleservices Limited -GSM Division',
'Tata Teleservices Maharashtra Ltd',
'Tbaytel',
'tbb global logistics inc',
'tcl logistics',
'TDC BB-ADSL users',
'TDC Oy Finland',
'TDC Sverige AB',
'TDS Computing Services',
'tds logistics inc',
'TDS Telecom',
'TDS Telecommunication Corporation',
'TE Data',
'Technocraft Industries Ltd',
'TECINFO',
'Tek Channel Consulting LLC',
'tek transportation inc',
'Teklinks Inc',
'TekSavvy Solutions',
'Teksavvy Solutions Inc',
'Teksystems Inc',
'Telco In A Box',
'Telconet S.A',
'TelCove, Inc.',
'Tele Danmark',
'tele-fonika cable americas corporation',
'Tele-Media Corporation',
'Tele2 Mobile',
'Tele2 SWIPnet',
'Tele2/SWIPnet',
'TELEBUCARAMANGA S.A. E.S.P.',
'Telecom Algeria',
'Telecom Argentina S.A.',
'Telecom Corporation Of New Zealand Ltd',
'Telecom Italia',
'Telecom Italia NET',
'Telecom Italia S.p.A.',
'Telecom Italia S.p.A. TIN EASY LITE',
'Telecom Italia SPA',
'Telecom Italia Wireline Services',
'Telecommunication Company of Iran',
'Telecommunication Services of Trinidad and Tobago',
'telecomplus',
'Telecomputing Norway AS',
'TELEFLEX AEROSPACE MANUFACTURING GROUP (Sermatech',
'Telefonica Data S.A.',
'Telefonica de Argentina',
'Telefonica del Peru',
'Telefonica del Peru S.A.',
'Telefonica Empresas',
'Telefonica O2 UK',
'Telefonos del Noroeste, S.A. de C.V.',
'Telekom Austria',
'Telekom Malaysia Berhad',
'Telekom Slovenije D.D.',
'TELEKOM SRBIJA a.d.',
'Telenor Norge AS',
'Telepacific Communications',
'Telepak Networks',
'Telesat Canada',
'Teleset Servis Ooo',
'Telesphere Networks',
'Telewest Ltd',
'Telgua',
'TeliaSonera Finland Oyj',
'Telkom SA Limited',
'Telkom SA Ltd',
'Telkomsel',
'Tellcom Iletisim Hizmetleri A.s.',
'Telmex Chile Internet S.A.',
'Telmex Colombia S.A.',
'Telnes Broadband.-hq',
'Telnet Worldwide',
'Telone',
'Telone PVT Ltd',
'Telstra Internet',
'TelstraClear Ltd',
'Telus Communications',
'Telus Communications Inc',
'Telus Quebec',
'TeraGo Networks',
'Terago Networks Inc',
'TeraGo PTP Networks',
'Texas Broadband',
'Texas Health Resources',
'The Bahamas Telecommunications Company',
'The Cloud Networks Ltd',
'the complete logistics company',
'the gateway logistics group inc',
'The Internet Connection',
'The Jackson Laboratory',
'The Middleby Corporation',
'The Narragansett Electric Company',
'The Noor Group',
'The Reynolds Company',
'the rk logistics group inc',
'The Venetian Macao-Resort-Hotel',
'the walsh transportation group inc',
'This field was added to fix syntax error',
'This space is statically assigned.',
'Three Indonesia',
'thurman transportation inc',
'tiffany transportation company inc',
'tigers logistics group ltd',
'Tikona Digital Networks Pvt. Ltd.',
'Tikona Infinet Ltd',
'timberland transportation inc',
'timco logistics systems inc',
'TIME dotCom Berhad',
'time logistics inc',
'TIME Telecommunications Sdn Bhd',
'time warner cable inc',
'Timico Limited',
'Tire-1 Ip Transit Provider Of Bangladesh - 1',
'titanium logistics inc',
'TM VADS DC Hosting',
'TMNET',
'TMnet Telekom Malaysia',
'tmsi logistics',
'Tng Worldwide',
'TOKAI Corporation',
'tonami transportation co ltd',
'top logistics llc',
'top shelf logistics llc',
'TOT Public Company Limited',
'total logistics',
'total logistics group inc',
'total transportation & distribution inc',
'total transportation concept',
'total transportation corporation',
'total transportation services inc',
'total transportation services llc',
'total transportation solutions inc',
'Totelcom Communications Llc',
'Towerstream I',
'toyo logistics co ltd',
'toyo logistics pte ltd',
'Toyota Motor Corporation',
'TPG Internet Pty Ltd.',
'Traci Network Solutions Inc',
'tradewinds transportation llc',
'trancy logistics america corporation',
'Trane Company',
'trans global logistics llc',
'trans global logistics ltd',
'trans gulf transportation inc',
'trans logistics international inc',
'trans pacific logistics llc',
'trans-national transportation service inc',
'Transit Wireless Llc',
'translink transportation inc',
'Transmision de Datos TELNOR',
'transolutions & logistics llc',
'transportation & industrial services inc',
'transportation & insurance consultants inc',
'transportation & warehouse services inc',
'transportation bureau city of nagoya',
'transportation collaborative inc',
'transportation consultants inc',
'transportation corridor agencies',
'transportation demand management inc',
'transportation department public',
'transportation equipment inc',
'transportation management dynamics inc',
'transportation marketing services',
'transportation parts unlimited',
'transportation research corporation',
'transportation security administration',
'transportation services inc',
'transportation solutions group llc',
'transportation specialists inc',
'transportation structures inc',
'transportation supply depot inc',
'transportation technology center inc',
'transtar executive transportation service inc',
'transtar transportation inc',
'Transtelco Inc',
'Transvision Reseau',
'TRE-FOR Bredbaand A/S',
'treasure transportation inc',
'trinity transportation inc',
'triple r transportation inc',
'Triple T Internet PCL',
'triumph logistics inc',
'True Broadband',
'True Broadband by True Online',
'True Internet',
'True internet Co., Ltd.',
'True Internet, Ltd.',
'TT&T, Internet Service Provider, Bangkok, Thailand',
'Tullahoma Utilities Board',
'Turk Telekom',
'Turk Telekom ADSL-200K 2',
'Turkcell Internet',
'Turner Broadcasting System',
'turner logistics corporation',
'Tussa IKT AS',
'TVCABO Mocambique',
'Tvnetwork Inc.',
'TW Fresno Customers',
'TW Houston Customers',
'TW Ontario Customers',
'TW Phoenix Customers',
'tw telecom holdings',
'U-NET Internet Ltd',
'UAB Baltnetos komunikacijos',
'Ubiquity Server Solutions Chicago',
'Ubiquity Server Solutions Dallas',
'Ubiquity Server Solutions New York',
'Ubiquity Server Solutions Seattle',
'UBTANET',
'UCC Corporate Customer',
'UCN',
'Ucweb Technologies',
'Ucwebhost Inc',
'UKOnline DSL customers',
'Ultimate Internet Access',
'ultimate logistics',
'ultimate na transportation equiptment llc',
'ultra logistics inc',
'unallocated',
'Unet B.V.',
'Uni2',
'unico logistics usa inc',
'UNICOM ZheJiang Province Network',
'unimasters logistics scs eood',
'Uninet',
'Uninet S.A. de C.V.',
'united global logistics inc',
'united logistics solutions',
'United Technologies',
'United Telephone Company',
'united transportation group inc',
'universal logistics group inc',
'University of Nebraska Medical Center',
'Unwired',
'Unwired Broadband',
'Unwired Broadband Inc',
'Upc Austria GmbH',
'UPC Ceska Republica, s.r.o.',
'UPC Ireland',
'UPC Norge',
'UPC Polska Sp. z o.o.',
'UPC Romania BUCURESTI FIBER',
'UPC Romania SRL',
'Upper Peninsula Telephone Company',
'urban logistics kk',
'US Department of Energy',
'us logistics inc',
'us messenger & logistics inc',
'US Signal Company, L.L.C.',
'us transportation llc',
'USAi.net',
'uscom logistics inc',
'USDA',
'used for static broadband customers in hyderabad',
'uti canada contract logistics inc',
'uti integrated logistics inc',
'uti integrated logistics llc',
'uti logistics ag',
'Utility Telephone',
'UUNET Non-Portable Customer Assignment',
'Vanco GmbH',
'Varna, Bulgaria',
'Vault Networks Inc',
'VDC',
'Vectra S.A.',
'Vegasnap Llc',
'Velocity Network Inc',
'Ventelo AS',
'venture logistics inc',
'venture transport logistics llc',
'veolia transportation',
'Veraciti',
'Veracity Networks LLC',
'Verat DOO',
'Verizon Business',
'Verizon Communications',
'Verizon FiOS',
'Verizon Internet Services',
'Vermont Telephone Company',
'Versatel Deutschland',
'veterans transportation llc',
'victory worldwide transportation',
'victory worldwide transportation inc',
'Videotron Ltee',
'Viettel Corporation',
'VimpelCom',
'Vineyard Christian Fellowship',
'Virgin Media',
'Virtela Technology Services Inc',
'Visafone Communications Limited',
'Vision Communications',
'Visionary Communications',
'visionary services inc',
'vitran logistics ltd',
'vividwireless Pty Ltd',
'Vizada Networks AS',
'vizion logistics llc',
'VMware Inc',
'vocar transportation services llc',
'Vocus Pty Ltd',
'Vodacom',
'Vodacom Ltd',
'Vodafone Australia Pty.',
'Vodafone Data',
'Vodafone Essar Spacetel Ltd',
'Vodafone India',
'Vodafone ISP',
'Vodafone Italia',
'Vodafone New Zealand Broadband',
'Voicecom Telecommunications Llc',
'Volia',
'Voonami Inc',
'vouk transportation inc',
'Vox Datapro',
'voxclever ltd',
'vsf transportation inc',
'VTR Banda Ancha S.A.',
'VTX Communications',
'VTX Services SA',
'w logistics inc',
'wallenius wilhelmsen logistics',
'wallenius wilhelmsen logistics ab',
'wallenius wilhelmsen logistics americas llc',
'wallenius wilhelmsen logistics as',
'Wananchi Online Limited',
'Wandering WIFI',
'ward transport & logistics corporation',
'Warid Telecom Uganda',
'wasatch transportation inc',
'Wash NOC First Network',
'Washington State Board for Community & Technical C',
'Wataniya Telecom',
'Wateen Telecom Ltd',
'Wave Broadband',
'Wave-Speed Networks, Inc.',
'Wavespeed',
'Waveworks Limited',
'wca logistics llc',
'Web Africa',
'Web Force Systems',
'WEBPASS',
'webroot inc',
'Webroot Services Ltd',
'Webroot Software',
'Websense Hosted Security Network',
'well worldwide energy logistics inc',
'Wells Fargo & Company',
'west ip communications inc',
'West Wisconsin Telcom Cooperative',
'western installation and logistics inc',
'Wharf T&T Limited',
'whatcom transportation authority',
'white eagle transportation inc',
'wide range transportation services inc',
'WideOpenWest',
'WightFibre',
'Wildblue Communications',
'wildernest logistics solutions inc',
'Wilhelm.Tel GmbH',
'WiLine Networks',
'Wilkes Communications',
'willamette valley internet',
'Wilogic Inc',
'wilson transportation inc',
'Wind Hellas Telecommunications SA',
'WIND Telecom S.A.',
'WIND Telecomunicazioni S.p.A',
'Windstream Communications',
'Windstream Communications Inc',
'Windstream Nuvox Inc',
'Wins, LLC',
'Wireless Broadband Access Network',
'Wireless Broadband of Oklahoma',
'Wireless Data Service Provider Corporation',
'Wireless Solution India Pvt Ltd.',
'Wireless-HSD',
'Wireless/Satellite Division of Day',
'wisconsin international services logistics inc',
'Wisper Isp Inc',
'Wood County Telephone Company Inc',
'Woodforest National Bank',
'Woolstock Mutual Telephone Association',
'World Access / Planet Internet',
'world logistics inc',
'World Phone Internet Services Private Limited',
'WorldNet Telecommunications',
'Worldpath Internet Services',
'worldwide logistics inc',
'WorldWide Web Services',
'wright transportation inc',
'www.funknetz.at GmbH',
'Wwz Telekom Ag',
'Wyoming.com',
'xcelerated transportation group llc',
'XO Communications',
'Xplornet Communications',
'Xplornet Communications Inc',
'xpo logistics canada inc',
'Xpressweb Internet Services',
'XS4ALL Internet BV',
'XTom WebHosting LLC',
'Yatanarpon Teleport',
'yellow transportation inc',
'YHC Corporation',
'yhl logistics inc',
'YMCA',
'YOU Telecom India Pvt Ltd',
'YTL Communications Sdn Bhd',
'yusen logistics inc',
'yusen logistics ltd',
'yusen logistics pty ltd',
'Zain Data-Jordan',
'ZAMTEL',
'Zen Internet',
'Ziggo BV',
'Zimmerman Communications',
'zip logistics llc',
'zipline logistics llc',
'Zito Media',
'ZON TV Cabo',
'Zscaler',
'Zscaler Inc',
'zscaler inc.',
'zuniga logistics ltd',
'[ CBB - IP pool for customers ]',
'Cooperative de cablodistribution de l\\'arriere-pays',
'Fasthosts Internet Limited - UK\\'s largest web host',
'ISHAN\\'S IP POOL',                                   
'ISP Cote d\\'Ivoire',                                 
'Netvision\\'s BroadBand service ',                    
'Nildram IP\\'s',                                      
'St Mary\\'s University',                             
'U\\'s Communications Corp.'
 ";
 

sub updateTable
{  
  $q = $_[0];
  #print "\n\n$q\n\n"; 
  my $sth = $dbh->prepare($q);
  if (!$sth->execute) { print "Error" . $dbh->errstr . "\n"; exit(0); }
  $sth->finish;
  sleep(1);
}   

           


updateTable("delete from $table where org in ( $ORGS )   ");


 
print "\nDone...\n";

 



