#!/bin/sh
#
# process ip addresses from dbaseNetAcuityIP, these include CAD, CATNAV & News loaded monthly
#


echo "Stopped March 2017";
echo
exit;

source /usr/wt/reload.sh

date
echo 
echo "Processing IPs";
echo 

php -q netacuity-lookup.php 
 
date
echo
 
mysqlimport -rL thomas  ${DIR}/netacuity/netacuityIPresolved.txt
echo
  

UDATE=`date +%s`
Q="UPDATE dbaseNetAcuityIP SET created = '${UDATE}' WHERE created=0";
echo "Manual Update when ready: ${Q}";
echo

echo NetAcuity | mail -s "Script netacuity-load finished    " robertf@c.net
 
date
echo
echo "Done...";
